- platform: template
  covers:
    office_blinds:
      friendly_name: Office Blinds
      unique_id: office_blinds
      device_class: blind
      availability_template: "{{ states('cover.office_blinds_front') not in ['unavailable', 'unknown'] and states('cover.office_blinds_side') not in ['unavailable', 'unknown'] }}"
      position_template: "{{ 100 - (state_attr('cover.office_blinds_front', 'current_position') | int(0)) }}"
      open_cover:
        service: cover.close_cover
        entity_id: 
          - cover.office_blinds_front
          - cover.office_blinds_side
      close_cover:
        service: cover.open_cover
        entity_id: 
          - cover.office_blinds_front
          - cover.office_blinds_side
      stop_cover:
        service: cover.stop_cover
        entity_id: 
          - cover.office_blinds_front
          - cover.office_blinds_side
      set_cover_position:
        service: cover.set_cover_position
        entity_id: 
          - cover.office_blinds_front
          - cover.office_blinds_side
        data:
          position: "{{ 100 - position }}"
    
    office_blind_front_inverted:
      friendly_name: Front Blind
      unique_id: office_blind_front_inverted
      device_class: blind
      availability_template: "{{ states('cover.office_blinds_front') not in ['unavailable', 'unknown'] }}"
      position_template: "{{ 100 - (state_attr('cover.office_blinds_front', 'current_position') | int(0)) }}"
      open_cover:
        service: cover.close_cover
        entity_id: cover.office_blinds_front
      close_cover:
        service: cover.open_cover
        entity_id: cover.office_blinds_front
      stop_cover:
        service: cover.stop_cover
        entity_id: cover.office_blinds_front
      set_cover_position:
        service: cover.set_cover_position
        entity_id: cover.office_blinds_front
        data:
          position: "{{ 100 - position }}"

    office_blind_side_inverted:
      friendly_name: Side Blind
      unique_id: office_blind_side_inverted
      device_class: blind
      availability_template: "{{ states('cover.office_blinds_side') not in ['unavailable', 'unknown'] }}"
      position_template: "{{ 100 - (state_attr('cover.office_blinds_side', 'current_position') | int(0)) }}"
      open_cover:
        service: cover.close_cover
        entity_id: cover.office_blinds_side
      close_cover:
        service: cover.open_cover
        entity_id: cover.office_blinds_side
      stop_cover:
        service: cover.stop_cover
        entity_id: cover.office_blinds_side
      set_cover_position:
        service: cover.set_cover_position
        entity_id: cover.office_blinds_side
        data:
          position: "{{ 100 - position }}"