- platform: template
  covers:
    garage_door:
      friendly_name: Garage Door
      device_class: garage
      value_template: >-
        {{ is_state('binary_sensor.garage_door', 'on') }}
      open_cover:
        - condition: state
          entity_id: binary_sensor.garage_door
          state: "off"
        - service: switch.turn_on
          entity_id: switch.garage_door_relay
      close_cover:
        - condition: state
          entity_id: binary_sensor.garage_door
          state: "on"
        - service: switch.turn_on
          entity_id: switch.garage_door_relay
      stop_cover:
        service: switch.turn_on
        entity_id: switch.garage_door_relay
    
    # Inverted so that open/close voice commands make sense
    # Open -> Blind is up, Close -> Blind is down
    office_blinds:
      friendly_name: Office Blinds
      unique_id: office_blinds
      device_class: blind
      availability_template: "{{ states('cover.office_blinds_front') not in ['unavailable', 'unknown'] and states('cover.office_blinds_side') not in ['unavailable', 'unknown'] }}"
      position_template: "{{ 100 - (state_attr('cover.office_blinds_front', 'current_position') | int(0)) }}"
      open_cover:
        service: cover.close_cover
        entity_id: 
          - cover.office_blinds_front
          - cover.office_blinds_side
      close_cover:
        service: cover.open_cover
        entity_id: 
          - cover.office_blinds_front
          - cover.office_blinds_side
      stop_cover:
        service: cover.stop_cover
        entity_id: 
          - cover.office_blinds_front
          - cover.office_blinds_side
      set_cover_position:
        service: cover.set_cover_position
        entity_id: 
          - cover.office_blinds_front
          - cover.office_blinds_side
        data:
          position: "{{ 100 - position }}"
      