- platform: template
  covers:
    garage_door_left:
      friendly_name: Left Garage Door
      device_class: garage
      value_template: "{{ is_state('binary_sensor.garage_door_left', 'on') }}"
      open_cover:
        service: switch.turn_on
        entity_id: switch.garage_door_relay_left
      close_cover:
        service: switch.turn_on
        entity_id: switch.garage_door_relay_left
      stop_cover:
        service: switch.turn_on
        entity_id: switch.garage_door_relay_left

    garage_door_right:
      friendly_name: Right Garage Door
      device_class: garage
      value_template: "{{ is_state('binary_sensor.garage_door_right', 'on') }}"
      open_cover:
        service: switch.turn_on
        entity_id: switch.garage_door_relay_right
      close_cover:
        service: switch.turn_on
        entity_id: switch.garage_door_relay_right
      stop_cover:
        service: switch.turn_off
        entity_id: switch.garage_door_relay_right
    
    # Inverted so that open/close voice commands make sense
    # Open -> Blind is up, Close -> Blind is down
    office_blinds:
      friendly_name: Office Blinds
      unique_id: office_blinds
      device_class: blind
      availability_template: "{{ states('cover.office_blinds_front') not in ['unavailable', 'unknown'] and states('cover.office_blinds_side') not in ['unavailable', 'unknown'] }}"
      position_template: "{{ 100 - (state_attr('cover.office_blinds_front', 'current_position') | int(0)) }}"
      open_cover:
        service: cover.close_cover
        entity_id: 
          - cover.office_blinds_front
          - cover.office_blinds_side
      close_cover:
        service: cover.open_cover
        entity_id: 
          - cover.office_blinds_front
          - cover.office_blinds_side
      stop_cover:
        service: cover.stop_cover
        entity_id: 
          - cover.office_blinds_front
          - cover.office_blinds_side
      set_cover_position:
        service: cover.set_cover_position
        entity_id: 
          - cover.office_blinds_front
          - cover.office_blinds_side
        data:
          position: "{{ 100 - position }}"
      