- platform: template
  covers:
    garage_door:
      friendly_name: Garage Door
      device_class: garage
      value_template: >-
        {{ is_state('binary_sensor.garage_door', 'on') }}
      open_cover:
        - condition: state
          entity_id: binary_sensor.garage_door
          state: "off"
        - service: switch.turn_on
          entity_id: switch.garage_door_relay
      close_cover:
        - condition: state
          entity_id: binary_sensor.garage_door
          state: "on"
        - service: switch.turn_on
          entity_id: switch.garage_door_relay
      stop_cover:
        service: switch.turn_on
        entity_id: switch.garage_door_relay
    
    # Inverted so that open/close voice commands make sense
    # Open -> Blind is up, Close -> Blind is down
    blinds_gameroom_alexa:
      friendly_name: Game Room Blinds
      unique_id: blinds_gameroom_alexa
      device_class: blind
      availability_template: "{{ not is_state('cover.blinds_gameroom', 'unavailable') }}"
      position_template: "{{ 100 - state_attr('cover.blinds_gameroom', 'current_position') }}"
      open_cover:
        service: cover.close_cover
        entity_id: cover.blinds_gameroom
      close_cover:
        service: cover.open_cover
        entity_id: cover.blinds_gameroom
      stop_cover:
        service: cover.stop_cover
        entity_id: cover.blinds_gameroom
      set_cover_position:
        service: cover.set_cover_position
        entity_id: cover.blinds_gameroom
        data:
          position: "{{ 100 - position }}"