- platform: template
  covers:
    garage_door:
      friendly_name: "Garage Door"
      value_template: "{{ is_state('binary_sensor.garage_door', 'on') }}"
      open_cover: 
        - condition: state
          entity_id: binary_sensor.garage_door
          state: 'off'
        - service: switch.turn_on
          entity_id: switch.garage_door_relay
      close_cover: 
        - condition: state
          entity_id: binary_sensor.garage_door
          state: 'on'
        - service: switch.turn_on
          entity_id: switch.garage_door_relay
      stop_cover:
        service: switch.turn_on
        entity_id: switch.garage_door_relay
      
