- platform: smtp
  name: email
  server: smtp.gmail.com
  port: 587
  timeout: 15
  sender: !secret email_sender
  encryption: starttls
  username: !secret email_address
  password: !secret gmail_pass
  recipient: !email_address
  sender_name: Home Assistant