- platform: template
  sensors:
    hvac_cool_on:
      entity_id: climate.honeywell_thermostat
      value_template: "{{ is_state_attr('climate.honeywell_thermostat', 'hvac_action', 'cooling') }}"
    hvac_heat_on:
      entity_id: climate.honeywell_thermostat
      value_template: "{{ is_state_attr('climate.honeywell_thermostat', 'hvac_action', 'heating') }}"
    hvac_only_fan_on:
      entity_id: climate.honeywell_thermostat
      value_template: "{{ is_state_attr('climate.honeywell_thermostat', 'hvac_action', 'idle') and is_state_attr('climate.honeywell_thermostat', 'fan_action', 'Running') }}"
    