- platform: template
  sensors:
    livingroom_roku_media_active:
      value_template: "{{ is_state('media_player.livingroom_tv', 'on') and is_state_attr('media_player.livingroom_tv', 'source', 'HDMI_IN_3') }}"
    livingroom_roku_available:
      value_template: "{{ not is_state('media_player.livingroom_tv', 'unavailable') and not is_state('media_player.livingroom_roku', 'unavailable') }}"