- platform: template
  sensors:
    basement_motion:
      value_template: "{{ is_state('sensor.basement_motion', '8') }}"
    bedroom_motion:
      value_template: "{{ is_state('sensor.bedroom_motion', '8') }}"
    dining_room_motion:
      value_template: "{{ is_state('sensor.dining_room_motion', '8') }}"
    office_motion:
      value_template: "{{ is_state('sensor.office_motion', '8') }}"