- platform: template
  sensors:
    basement_occupied:
      entity_id:
        - sensor.basement_sensor_burglar
        - input_boolean.workout_mode
      value_template: "{{ is_state('sensor.basement_sensor_burglar', '8') or is_state('input_boolean.workout_mode', 'on') }}"