- platform: mqtt
  name: sliding_side_door
  state_topic: rtl_433/+/devices/Generic-Remote/65022/cmd
  device_class: door
  payload_off: 14
  payload_on: 10

- platform: mqtt
  name: patio_door
  state_topic: rtl_433/+/devices/Generic-Remote/668/cmd
  device_class: door
  payload_off: 14
  payload_on: 10

- platform: mqtt
  name: hot_tub_cover
  state_topic: rtl_433/+/devices/Generic-Remote/17322/cmd
  device_class: door
  payload_off: 14
  payload_on: 10

- platform: mqtt
  name: bedroom_door
  state_topic: rtl_433/+/devices/Generic-Remote/5948/cmd
  device_class: door
  payload_off: 14
  payload_on: 10

- platform: mqtt
  name: laundryroom_door
  state_topic: rtl_433/+/devices/Generic-Remote/26300/cmd
  device_class: door
  payload_off: 14
  payload_on: 10

- platform: mqtt
  name: laundryroom_motion
  state_topic: rtl_433/+/devices/Kerui-Security/635232/motion
  device_class: motion
  payload_on: 1
  off_delay: 15