- platform: template
  sensors:
    someone_is_sleeping:
      delay_off: 
        minutes: 5
      entity_id: binary_sensor.sleepnumber_master_bed_mike_is_in_bed
      value_template: "{{ is_state('binary_sensor.sleepnumber_master_bed_mike_is_in_bed', 'on') }}"