- platform: template
  sensors:
    bed_occupied:
      value_template: "{{ is_state('binary_sensor.sleepnumber_master_bed_mike_is_in_bed', 'on') or is_state('binary_sensor.binary_sensor.sleepnumber_master_bed_guest_is_in_bed', 'on') }}"