- platform: template
  sensors:
    basement_humidity_above_threshold:
      value_template: "{{ states('sensor.basement_humidity')|float > states('input_number.dehumidifier_on_threshold')|float }}"
      entity_id:
        - sensor.basement_humidity
        - input_number.dehumidifier_on_threshold
    basement_humidity_below_threshold:
      value_template: "{{ states('sensor.basement_humidity')|float < states('input_number.dehumidifier_off_threshold')|float }}"
      entity_id:
        - sensor.basement_humidity
        - input_number.dehumidifier_off_threshold
    