- platform: template
  sensors:
    grafana_update_available:
      value_template: "{{ states('sensor.grafana_latest_version') != state_attr('sensor.docker_grafana', 'image').split(':')[1] }}"
    unifi_update_available:
      value_template: "{{ states('sensor.unifi_latest_version') != state_attr('sensor.docker_unifi', 'image').split(':')[1] }}"
    zwavejs2mqtt_update_available:
      value_template: "{{ states('sensor.zwavejs2mqtt_latest_version') != state_attr('sensor.office_raspi4_zwavejs', 'image').split(':')[1] }}"