- platform: template
  sensors:
    zwavejs2mqtt_update_available:
      value_template: "{{ state_attr('sensor.zwavejs2mqtt', 'latest_release_tag') != 'v' + state_attr('sensor.office_raspi4_zwavejs', 'image').split(':')[1] }} "