automation:

  - alias: Bedroom - Close Shades at Sunset
    id: bedroom_close_shades_at_sunset
    mode: queued
    triggers:
      - trigger: sun
        event: sunset
    actions:
      - action: cover.close_cover
        entity_id: cover.bedroom_side_window_shade

  - alias: Bedroom - Open Shades at Sunrise
    id: bedroom_open_shades_at_sunrise
    mode: queued
    triggers:
      - trigger: sun
        event: sunrise
    actions:
      - action: cover.open_cover
        entity_id: cover.bedroom_side_window_shade