automation:
  - alias: Pantry - Light
    id: pantry_light
    mode: queued
    triggers:
      - trigger: state
        entity_id: binary_sensor.kitchen_back_presence_pantry_zone
        to: "on"
      - trigger: state
        entity_id: binary_sensor.kitchen_back_presence_pantry_zone
        to: "off"
        for:
          seconds: "{{ states('input_number.pantry_light_timeout') | int(10) }}"
    actions:
      - action: light.turn_{{ trigger.to_state.state }}
        entity_id: light.pantry

input_number:
  pantry_light_timeout:
    min: 0
    max: 600
    mode: box
    unit_of_measurement: s