automation:
  - alias: Pantry - Light
    id: pantry_light
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_back_presence_pantry_zone
        to: "on"
      - platform: state
        entity_id: binary_sensor.kitchen_back_presence_pantry_zone
        to: "off"
        for:
          seconds: "{{ states('input_number.pantry_light_timeout') | int(10) }}"
    action:
      service: light.turn_{{ trigger.to_state.state }}
      entity_id: light.pantry

input_number:
  pantry_light_timeout:
    min: 0
    max: 600
    mode: box
    unit_of_measurement: s