automation:

  - alias: Kitchen Tablet - Turn On Charging
    id: kitchen_tablet_turn_on_charging
    triggers:
      - platform: numeric_state
        entity_id: sensor.kitchen_tablet_battery
        below: input_number.kitchen_tablet_charging_threshold_low
    actions:
      - action: switch.turn_on
        entity_id: switch.kitchen_tablet_charging_switch

  - alias: Kitchen Tablet - Turn Off Charging
    id: kitchen_tablet_turn_off_charging
    triggers:
      - platform: numeric_state
        entity_id: sensor.kitchen_tablet_battery
        above: input_number.kitchen_tablet_charging_threshold_high
    actions:
      - action: switch.turn_off
        entity_id: switch.kitchen_tablet_charging_switch

  - alias: Kitchen Tablet - Screen
    id: kitchen_tablet_screen
    mode: queued
    triggers:
      - platform: state
        entity_id: group.presence_kitchen
        to: 'on'
      - platform: state
        entity_id: group.presence_kitchen
        to: 'off'
        for:
          seconds: "{{ states('input_number.kitchen_tablet_screen_timeout') | int(5) }}"
    actions:
      - action: switch.turn_{{ trigger.to_state.state }}
        entity_id: switch.kitchen_tablet_screen

  - alias: Kitchen Tablet - Fix for Screen Turning On Randomly
    id: kitchen_tablet_fix_for_screen_turning_on_randomly
    mode: queued
    triggers:
      - platform: state
        entity_id: switch.kitchen_tablet_screen
        to: 'on'
    conditions:
      - condition: state
        entity_id: group.presence_kitchen
        state: 'off'
    actions:
      - action: switch.turn_off
        entity_id: switch.kitchen_tablet_screen

input_number:

  kitchen_tablet_charging_threshold_high:
    min: 0
    max: 100
    mode: box
    unit_of_measurement: "%"

  kitchen_tablet_charging_threshold_low:
    min: 0
    max: 100
    mode: box
    unit_of_measurement: "%"

  kitchen_tablet_screen_timeout:
    min: 0
    max: 600
    mode: box
    unit_of_measurement: s
