automation:
  - alias: Kitchen Tablet - Charging
    id: kitchen_tablet_charging
    mode: queued
    triggers:
      - platform: state
        entity_id: sensor.kitchen_tablet_battery
    actions:
      - variables:
          battery_level: "{{ trigger.to_state.state | int }}"
          low_threshold: "{{ states('input_number.kitchen_tablet_charging_threshold_low') | int }}"
          high_threshold: "{{ states('input_number.kitchen_tablet_charging_threshold_high') | int }}"
          switch_entity: switch.kitchen_tablet_charging_switch
      - choose:
          - conditions: "{{ battery_level < low_threshold and is_state(switch_entity, 'off') }}"
            sequence:
              - action: switch.turn_on
                target:
                  entity_id: "{{ switch_entity }}"
          - conditions: "{{ battery_level > high_threshold and is_state(switch_entity, 'on') }}"
            sequence:
              - action: switch.turn_off
                target:
                  entity_id: "{{ switch_entity }}"

  - alias: Kitchen Tablet - Screen
    id: kitchen_tablet_screen
    mode: queued
    triggers:
      - platform: state
        entity_id: group.presence_kitchen
        to: 'on'
      - platform: state
        entity_id: group.presence_kitchen
        to: 'off'
        for:
          seconds: "{{ states('input_number.kitchen_tablet_screen_timeout') | int(5) }}"
    actions:
      - action: switch.turn_{{ trigger.to_state.state }}
        entity_id: switch.kitchen_tablet_screen

  - alias: Kitchen Tablet - Fix for Screen Turning On Randomly
    id: kitchen_tablet_fix_for_screen_turning_on_randomly
    mode: queued
    triggers:
      - platform: state
        entity_id: switch.kitchen_tablet_screen
        to: 'on'
    conditions:
      - condition: state
        entity_id: group.presence_kitchen
        state: 'off'
    actions:
      - action: switch.turn_off
        entity_id: switch.kitchen_tablet_screen

input_number:

  kitchen_tablet_charging_threshold_high:
    min: 0
    max: 100
    mode: box
    unit_of_measurement: "%"

  kitchen_tablet_charging_threshold_low:
    min: 0
    max: 100
    mode: box
    unit_of_measurement: "%"

  kitchen_tablet_screen_timeout:
    min: 0
    max: 600
    mode: box
    unit_of_measurement: s
