automation:
  - alias: Garage inner scene main button - toggle arcade
    id: garage_inner_scene_main_button_toggle_arcade
    trigger:
      platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 4
        property_key: "005"
        value: KeyPressed
    action:
      service: switch.toggle
      entity_id: switch.arcade_cabinet_power_strip

  - alias: Garage switches - toggle air hockey fan
    id: garage_switches_toggle_air_hockey_fan
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 4
          property_key: "002"
          value: KeyPressed
    action:
      service: switch.toggle
      entity_id: switch.air_hockey_table_fan