automation:

  - alias: Hall of Holes - Add Player
    id: hall_of_holes_add_player
    mode: queued
    trigger:
      - platform: state
        entity_id: input_button.hall_of_holes_add_player
    action:
      - variables:
          new_name: "{{ states('input_text.hall_of_holes_add_player_name') }}"
      - service: notify.hall_of_holes_db
        data:
          message: "CREATE TABLE IF NOT EXISTS players (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(64))"
      - service: mysql_query.query
        response_variable: existing_players_query
        data:
          query: SELECT player FROM players
      - condition: template
        value_template: >
          {% set existing_players = existing_players_query | map(attribute='player') %}
          {{ new_name in existing_players }}
      - service: notify.hall_of_holes_db
        data:
          message: "INSERT INTO players (name) VALUES ('{{ new_name }}')"

input_button:
  hall_of_holes_add_player:
    name: Add Player
    icon: mdi:handball

input_text:
  hall_of_holes_add_player_name: