auth:
config:
conversation:
history:
logbook:
media_source:
mobile_app:
sun:
system_health:
wake_on_lan:

calendar:
  - platform: todoist
    token: !secret TODOIST_API_TOKEN

frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /local/community/custom-brand-icons/custom-brand-icons.js
  themes: !include_dir_merge_named themes

homeassistant:
  packages: !include_dir_named packages

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24
    - 172.0.0.0/8

proximity:
  mikes_house:
    zone: home
    devices: person.mike
  sarahs_house:
    zone: sarah_remote_home
    devices: person.mike

recorder:
  db_url: !secret RECORDER_DB_URL

spotcast:
  sp_dc: !secret SPOTIFY_SP_DC
  sp_key: !secret SPOTIFY_SP_KEY
  country: US

alexa: !include misc/alexa.yaml
automation: !include automations.yaml
automation manual: !include_dir_merge_list automation/
binary_sensor: !include_dir_merge_list binary_sensor/
cover: !include misc/cover.yaml
group: !include misc/group.yaml
input_boolean: !include input/input_boolean.yaml
input_datetime: !include input/input_datetime.yaml
input_number: !include input/input_number.yaml
input_select: !include input/input_select.yaml
light: !include_dir_merge_list light/
lovelace: !include lovelace/config.yaml
media_player: !include_dir_merge_list media_player/
monitor_docker: !include misc/monitor_docker.yaml
mqtt: !include_dir_named mqtt/
person: !include misc/person.yaml
rest_command: !include misc/rest_command.yaml
script: !include_dir_named script/
sensor: !include_dir_merge_list sensor/
shell_command: !include misc/shell_command.yaml
switch: !include_dir_merge_list switch/
template: !include_dir_merge_list template/
