auth:
config:
history:
logbook:
media_source:
mobile_app:
python_script:
sun:
system_health:
updater:
wake_on_lan:
  
frontend:
  themes: !include_dir_merge_named themes

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxies
    
sleepiq:
  username: !secret email_address
  password: !secret sleepiq_pass
    
zwave:
  config_path: /zwave-config
  usb_path: !secret zwave_usb_path
  polling_interval: 30000

alexa: !include misc/alexa.yaml
automation: !include_dir_merge_list automation/
binary_sensor: !include_dir_merge_list binary_sensor/
camera: !include misc/camera.yaml
cover: !include misc/garage_door_cover.yaml
device_tracker: !include misc/device_tracker.yaml
group: !include misc/group.yaml
influxdb: !include misc/influxdb.yaml
input_boolean: !include input/input_boolean.yaml
input_datetime: !include input/input_datetime.yaml
input_number: !include input/input_number.yaml
input_select: !include input/input_select.yaml
light: !include_dir_merge_list light/
lovelace: !include lovelace-config.yaml
media_player: !include_dir_merge_list media_player/
monitor_docker: !include misc/monitor_docker.yaml
notify: !include misc/notify.yaml
person: !include misc/person.yaml
proximity: !include misc/proximity.yaml
recorder: !include misc/recorder.yaml
script: !include_dir_named script/
sensor: !include_dir_merge_list sensor/
shell_command: !include misc/shell_command.yaml
switch: !include_dir_merge_list switch/
webostv: !include misc/webostv.yaml
zone: !include misc/zone.yaml