auth:
config:
discovery:
history:
logbook:
media_source:
mobile_app:
sun:
system_health:
wake_on_lan:

camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.47
    token: ${XIAOMI_VACUUM_TOKEN}
    username: ${XIAOMI_VACUUM_USERNAME}
    password: '${XIAOMI_VACUUM_PASSWORD}'
    draw: ['all']
    attributes:
      - calibration_points

frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
  themes: !include_dir_merge_named themes

google:
  client_id: ${GOOGLE_CALENDAR_CLIENT_ID}
  client_secret: ${GOOGLE_CALENDAR_CLIENT_SECRET}

homeassistant:
  packages: !include_dir_named packages

http:
  use_x_forwarded_for: true
  trusted_proxies: ${HASS_TRUSTED_PROXIES}

sleepiq:
  username: ${SLEEPIQ_USERNAME}
  password: ${SLEEPIQ_PASSWORD}

spotify:
  client_id: ${SPOTIFY_CLIENT_ID}
  client_secret: ${SPOTIFY_CLIENT_SECRET}

alexa: !include misc/alexa.yaml
automation: !include_dir_merge_list automation/
binary_sensor: !include_dir_merge_list binary_sensor/
cover: !include misc/garage_door_cover.yaml
device_tracker: !include misc/device_tracker.yaml
group: !include misc/group.yaml
input_boolean: !include input/input_boolean.yaml
input_datetime: !include input/input_datetime.yaml
input_number: !include input/input_number.yaml
input_select: !include input/input_select.yaml
light: !include_dir_merge_list light/
lovelace: !include lovelace/config.yaml
media_player: !include_dir_merge_list media_player/
monitor_docker: !include misc/monitor_docker.yaml
person: !include misc/person.yaml
recorder: !include misc/recorder.yaml
script: !include_dir_named script/
sensor: !include_dir_merge_list sensor/
shell_command: !include misc/shell_command.yaml
switch: !include_dir_merge_list switch/
template: !include_dir_merge_list template/
