assist_pipeline:
auth:
backup:
battery_notes:
config:
conversation:
dhcp:
grad_vol:
history:
homeassistant_alerts:
image_upload:
logbook:
lovelace:
media_source:
mobile_app:
my:
ssdp:
stream:
sun:
system_health:
usb:
wake_on_lan:
webhook:
zeroconf:

frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /local/community/custom-brand-icons/custom-brand-icons.js
    - /hacsfiles/kiosk-mode/kiosk-mode.js

homeassistant:
  packages: !include_dir_named packages

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24
    - 172.0.0.0/8

remote_homeassistant:
  instances:

spotcast:
  sp_dc: !secret SPOTIFY_SP_DC
  sp_key: !secret SPOTIFY_SP_KEY
  country: US

automation: !include_dir_merge_list automation/
binary_sensor: !include_dir_merge_list binary_sensor/
input_number: !include input/input_number.yaml
input_select: !include input/input_select.yaml
media_player: !include_dir_merge_list media_player/
monitor_docker: !include misc/monitor_docker.yaml
mqtt: !include_dir_named mqtt/
person: !include misc/person.yaml
sensor: !include_dir_merge_list sensor/
switch: !include_dir_merge_list switch/
template: !include_dir_merge_list template/