auth:
backup:
battery_notes:
config:
conversation:
history:
logbook:
media_source:
mobile_app:
sun:
system_health:
wake_on_lan:

frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /local/community/custom-brand-icons/custom-brand-icons.js

homeassistant:
  packages: !include_dir_named packages

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24
    - 172.0.0.0/8

lovelace:
  mode: yaml
  dashboards:
    guest-room-single:
      mode: yaml
      filename: dashboards/guest-room-single.yaml
      title: Guest Room (Single)

spotcast:
  sp_dc: !secret SPOTIFY_SP_DC
  sp_key: !secret SPOTIFY_SP_KEY
  country: US

automation: !include_dir_merge_list automation/
binary_sensor: !include_dir_merge_list binary_sensor/
cover: !include misc/cover.yaml
group: !include misc/group.yaml
input_boolean: !include input/input_boolean.yaml
input_number: !include input/input_number.yaml
input_select: !include input/input_select.yaml
media_player: !include_dir_merge_list media_player/
monitor_docker: !include misc/monitor_docker.yaml
mqtt: !include_dir_named mqtt/
person: !include misc/person.yaml
script: !include_dir_named script/
sensor: !include_dir_merge_list sensor/
switch: !include_dir_merge_list switch/
template: !include_dir_merge_list template/
