views:
  - icon: mdi:home
    type: custom:grid-layout
    layout:
      grid-template-columns: 20% 40% 40%
      grid-template-rows: 20% 20% 20% 20% 20%
      grid-template-areas: |
        "btn1 thermostat ."
        "btn2 thermostat ."
        "btn3 . ."
        "btn4 . ."
        "btn5 . ."
    cards:
      - type: button
        entity: switch.entry_light
        view_layout:
          grid-area: btn1
      - type: button
        entity: light.livingroom_lamp
        view_layout:
          grid-area: btn2
      - type: button
        entity: light.diningroom
        view_layout:
          grid-area: btn3
      - type: button
        entity: cover.garage_door
        view_layout:
          grid-area: btn4
      - type: button
        entity: group.update_available
        view_layout:
          grid-area: btn5
      - !include lovelace/thermostat.yaml
