button_card_templates:
  left_col_buttons:
    styles:
      card:
        - height: 150px
        - width: 150px
  btn_separator:
    color_type: blank-card
    styles:
      card:
        - height: 50px
        - width: 150px
views:
  - title: custom grid layout
    type: custom:grid-layout
    layout:
      grid-template-columns: 10% 30% 60%
      grid-template-rows: auto
      grid-template-areas: |
        "btn1 col2 ."
        "btn2 col2 ."
        "btn3 col2 ."
        "btn4 col2 ."
        "btn5 col2 ."
    cards:
      - type: custom:button-card
        entity: switch.entry_light
        template: left_col_buttons
        view_layout:
          grid-area: btn1
      - type: custom:button-card
        entity: light.livingroom_lamp
        template: left_col_buttons
        view_layout:
          grid-area: btn2
      - type: custom:button-card
        entity: light.diningroom
        template: left_col_buttons
        view_layout:
          grid-area: btn3
      - type: custom:button-card
        entity: cover.garage_door
        template: left_col_buttons
        view_layout:
          grid-area: btn4
      - type: custom:button-card
        entity: group.update_available
        template: left_col_buttons
        view_layout:
          grid-area: btn5
      - type: vertical-stack
        view_layout:
          grid-area: col2
        cards:
          - !include lovelace/thermostat.yaml
  - title: horizontal stack
    panel: true
    cards:
      - type: horizontal-stack
        cards:
          - type: grid
            columns: 2
            cards:
              - type: button
                entity: switch.entry_light
              - type: button
                entity: light.livingroom_lamp
              - type: button
                entity: light.diningroom
              - type: button
                entity: cover.garage_door
              - type: button
                entity: group.update_available
              - type: button
                entity: switch.livingroom_netflix
              - type: button
                entity: switch.livingroom_hulu
              - type: button
                entity: switch.livingroom_ps4
              - type: button
                entity: switch.livingroom_steam
              - type: button
                entity: input_boolean.workout_mode
          - type: vertical-stack
            cards:
              - !include lovelace/thermostat.yaml
              - type: weather-forecast
                entity: weather.home
          - type: vertical-stack
            cards:
              - !include lovelace/todays_exercise.yaml
            
