title: Overlord
background: var(--background-image)
views:
  - icon: mdi:home
    cards:
      - type: custom:simple-thermostat
        entity: climate.honeywell_thermostat
        show_header: false
        decimals: 0
        step_size: 1
        step_layout: row
        control:
          _headings: false
          hvac: 
            "off": 
              name: false
            heat:
              name: false
            cool:
              name: false
          fan: true
      - type: entities
        title: Bedroom
        entities:
          - type: section
            label: Bedroom
          - type: buttons
            entities:
              - entity: light.bedroom_light
                name: Overhead
              - entity: light.bedroom_lamps
                name: Lamps
              - entity: switch.bedroom_fan
                icon: mdi:fan
                show_name: false
          - type: custom:paper-buttons-row
            buttons:
              - icon: mdi:bed-empty
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.bed_presets
                    option: Flat
              - icon: mdi:television
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.bed_presets
                    option: Watch TV
              - icon: mdi:book-open
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.bed_presets
                    option: Read
          - type: custom:slider-entity-row
            entity: input_number.bed_sleep_number_left
            hide_state: false
            name: Left
          - type: custom:slider-entity-row
            entity: input_number.bed_sleep_number_right
            hide_state: false
            name: Right
      - type: entities
        title: Basement
        entities:
          - type: buttons
            entities:
              - entity: light.basement_light
                show_name: false
              - entity: switch.basement_stereo
                icon: mdi:audio-video
                show_name: false
              - entity: media_player.basement_tv
                show_name: false
              - entity: media_player.playstation_4_basement
                icon: mdi:sony-playstation
                show_name: false
              - entity: input_boolean.workout_mode
                icon: mdi:weight-lifter
                show_name: false
      - type: entities
        title: Living Room
        entities:
          - type: buttons
            entities:
              - entity: media_player.livingroom_media
                icon: mdi:cast
                show_name: false
              - entity: light.dining_room_light
                name: Dining Room
              - entity: switch.entry_light
                name: Entry
                icon: mdi:lightbulb
              - entity: light.living_room_lamp
                name: Lamp
          - type: custom:paper-buttons-row
            buttons:
              - icon: mdi:sony-playstation
                tap_action:
                  action: fire-event
                  event_type: MEDIA_CONTROLLER_COMMAND
                  event_data:
                    room: livingroom
                    source: ps4
                hold_action:
                  action: more-info
                  entity: media_player.playstation_4_office
              - icon: mdi:steam
                tap_action:
                  action: fire-event
                  event_type: MEDIA_CONTROLLER_COMMAND
                  event_data:
                    room: livingroom
                    source: steam
              - icon: mdi:netflix
                tap_action:
                  action: fire-event
                  event_type: MEDIA_CONTROLLER_COMMAND
                  event_data:
                    room: livingroom
                    source: netflix
              - icon: mdi:hulu
                tap_action:
                  action: fire-event
                  event_type: MEDIA_CONTROLLER_COMMAND
                  event_data:
                    room: livingroom
                    source: hulu
              - icon: mdi:plex
                tap_action:
                  action: fire-event
                  event_type: MEDIA_CONTROLLER_COMMAND
                  event_data:
                    room: livingroom
                    source: plex
              - icon: mdi:youtube
                tap_action:
                  action: fire-event
                  event_type: MEDIA_CONTROLLER_COMMAND
                  event_data:
                    room: livingroom
                    source: youtube
          - type: conditional
            conditions:
              - entity: media_player.livingroom_receiver
                state: 'on'
            row:
              type: custom:slider-entity-row
              entity: light.living_room_volume
              icon: mdi:volume-high
              full_row: true
              step: 1
              max: 45
      - type: entities
        title: Game Room
        entities:
          - type: buttons
            entities:
              - entity: light.game_room_light
                show_name: false
              - entity: media_player.gameroom_tv
                show_name: false
          - type: conditional
            conditions:
              - entity: media_player.gameroom_receiver
                state: 'on'
            row:
              type: custom:slider-entity-row
              entity: light.game_room_volume
              icon: mdi:volume-high
              full_row: true
              step: 1
              min: 20
              max: 100
      - type: entities
        title: Upstairs Bathroom
        entities:
          - type: buttons
            entities:
              - entity: light.upstairs_bathroom_light
                show_name: false
              - entity: switch.upstairs_bathroom_vent
                icon: mdi:fan
                show_name: false
      - type: entities
        entities:
          - type: custom:slider-entity-row
            entity: light.office_light
            name: Office
            toggle: true
          - type: custom:slider-entity-row
            entity: light.patio_light
            name: Patio
            toggle: true
          - cover.garage_door