title: Overlord
background: var(--background-image)
views:
  - icon: mdi:home
    cards:
      - type: custom:simple-thermostat
        entity: climate.honeywell_thermostat
        name: false
        decimals: 0
        step_size: 1
        step_layout: row
        control: false
        hide:
          temperature: true
          state: true
      - type: conditional
        conditions:
          - entity: media_player.livingroom_receiver
            state: "on"
        card:
           type: custom:mini-media-player
           entity: media_player.livingroom_media
           name: Living Room Media
           artwork: none
           volume_stateless: true
           source: full
      - type: entities
        entities:
          - light.basement_light
          - light.bedroom_lamps
          - light.bedroom_light
          - light.dining_room_light
          - switch.entry_light
          - light.game_room_light
          - light.living_room_lamp
          - light.office_light
          - light.patio_light
          - light.upstairs_bathroom_light
          - switch.bedroom_fan
          - switch.basement_stereo