background: var(--background-image)
views:
  - icon: mdi:home
    cards:
      - type: entities
        entities:
          - type: custom:simple-thermostat
            entity: climate.honeywell_thermostat
            canary_style:
              margin: '-20px -20px -20px -20px'
            no_card: true
            show_header: false
            decimals: 0
            step_size: 1
            step_layout: row
            control: false
          - type: custom:paper-buttons-row
            no_card: true
            base_config:
              style:
                button:
                  border-radius: 40px
            buttons:
              - entity: switch.hvac_off
                name: false
              - entity: switch.heat_mode
                name: false
                state_styles:
                  'on':
                    button:
                      background-color: orange
              - entity: switch.cool_mode
                name: false
                state_styles:
                  'on':
                    button:
                      background-color: var(--label-badge-blue)
          - type: custom:paper-buttons-row
            no_card: true
            canary_style:
              margin: '-30px 0px 0px'
            base_config:
              style:
                button:
                  border-radius: 20px
            buttons:
              - entity: switch.next_fan_mode
                name: false
              - entity: switch.fan_auto
                icon: false
              - entity: switch.fan_on
                icon: false
              - entity: switch.circulation
                icon: false
      - type: entities
        title: Bedroom
        entities:
          - type: custom:paper-buttons-row
            buttons:
              - entity: light.bedroom_light
                icon: mdi:ceiling-light
                name: false
              - entity: light.bedroom_lamps
                icon: mdi:lamps
                name: false
              - entity: switch.bedroom_fan
                icon: mdi:fan
                name: false
              - icon: mdi:bed-empty
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.bed_presets
                    option: Flat
              - icon: mdi:television
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.bed_presets
                    option: Watch TV
              - icon: mdi:book-open
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.bed_presets
                    option: Read
          - type: custom:slider-entity-row
            entity: input_number.bed_sleep_number_left
            hide_state: false
            name: Left
          - type: custom:slider-entity-row
            entity: input_number.bed_sleep_number_right
            hide_state: false
            name: Right
      - type: entities
        title: Basement
        entities:
          - type: buttons
            entities:
              - entity: light.basement_light
                show_name: false
              - entity: switch.basement_stereo
                icon: mdi:audio-video
                show_name: false
              - entity: media_player.basement_tv
                show_name: false
              - entity: media_player.playstation_4_basement
                icon: mdi:sony-playstation
                show_name: false
              - entity: input_boolean.workout_mode
                icon: mdi:weight-lifter
                show_name: false
      - type: entities
        title: Living Room
        entities:
          - type: buttons
            entities:
              - entity: media_player.livingroom_media
                icon: mdi:cast
                show_name: false
              - entity: light.dining_room_light
                name: Dining Room
              - entity: switch.entry_light
                name: Entry
                icon: mdi:lightbulb
              - entity: light.living_room_lamp
                name: Lamp
          - type: custom:paper-buttons-row
            buttons:
              - icon: mdi:sony-playstation
                tap_action:
                  action: fire-event
                  event_type: MEDIA_CONTROLLER_COMMAND
                  event_data:
                    room: livingroom
                    source: ps4
                hold_action:
                  action: more-info
                  entity: media_player.playstation_4_office
              - icon: mdi:steam
                tap_action:
                  action: fire-event
                  event_type: MEDIA_CONTROLLER_COMMAND
                  event_data:
                    room: livingroom
                    source: steam
              - icon: mdi:netflix
                tap_action:
                  action: fire-event
                  event_type: MEDIA_CONTROLLER_COMMAND
                  event_data:
                    room: livingroom
                    source: netflix
              - icon: mdi:hulu
                tap_action:
                  action: fire-event
                  event_type: MEDIA_CONTROLLER_COMMAND
                  event_data:
                    room: livingroom
                    source: hulu
              - icon: mdi:plex
                tap_action:
                  action: fire-event
                  event_type: MEDIA_CONTROLLER_COMMAND
                  event_data:
                    room: livingroom
                    source: plex
              - icon: mdi:youtube
                tap_action:
                  action: fire-event
                  event_type: MEDIA_CONTROLLER_COMMAND
                  event_data:
                    room: livingroom
                    source: youtube
          - type: conditional
            conditions:
              - entity: media_player.livingroom_receiver
                state: 'on'
            row:
              type: custom:slider-entity-row
              entity: light.living_room_volume
              icon: mdi:volume-high
              full_row: true
              step: 1
              max: 45
      - type: entities
        title: Game Room
        entities:
          - type: buttons
            entities:
              - entity: light.gameroom_overhead
                show_name: false
              - entity: media_player.gameroom_tv
                show_name: false
          - type: conditional
            conditions:
              - entity: media_player.gameroom_receiver
                state: 'on'
            row:
              type: custom:slider-entity-row
              entity: light.game_room_volume
              icon: mdi:volume-high
              full_row: true
              step: 1
              min: 20
              max: 100
      - type: entities
        title: Upstairs Bathroom
        entities:
          - type: buttons
            entities:
              - entity: light.upstairs_bathroom_light
                show_name: false
              - entity: switch.upstairs_bathroom_vent
                icon: mdi:fan
                show_name: false
      - type: entities
        entities:
          - type: custom:slider-entity-row
            entity: light.office_light
            name: Office
            toggle: true
          - type: custom:slider-entity-row
            entity: light.patio_light
            name: Patio
            toggle: true
          - cover.garage_door
  - icon: mdi:auto-fix
    cards:
      - type: entities
        title: Sleep Mode
        entities:
          - entity: input_boolean.sleep_mode
            name: Sleep Mode
          - type: divider
          - automation.turn_off_sleep_mode
          - automation.turn_on_sleep_mode
          - type: divider
          - entity: input_datetime.keep_sleep_mode_on_until
            name: Keep On Until (Wakeup Time)
          - entity: input_datetime.turn_on_sleep_mode_after
            name: Turn On After (Bedtime)
          - entity: input_datetime.turn_off_sleep_mode_if_bed_unoccupied_for
            name: Turn Off If Bed Unoccupied For
      - type: entities
        title: Upstairs Bathroom 
        entities:
          - entity: input_number.upstairsbathroom_light_brightness
            name: Current Brightness
          - entity: input_number.upstairsbathroom_light_transition
            name: Transition
          - entity: input_number.upstairsbathroom_light_sleeping_brightness
            name: Sleeping Brightness
          - entity: input_number.upstairsbathroom_light_day_brightness
            name: Daytime Brightness
          - entity: input_number.upstairsbathroom_light_night_brightness
            name: Nighttime Brightness
          - type: section
            label: Door opens, turn off light if...
          - entity: input_datetime.upstairsbathroom_door_opened_motion_off_for
            name: Motion Off For 
          - entity: input_datetime.upstairsbathroom_door_opened_motion_off_timeout
            name: Motion Off Timeout
          - type: section
            label: Light off after no motion for...
          - entity: input_datetime.upstairsbathroom_light_off_door_open_for
            name: (Door Open)
          - entity: input_datetime.upstairsbathroom_light_off_door_closed_for
            name: (Door Closed)
