background: var(--background-image)
button_card_templates:
  standard:
    color_type: card
    size: 80%
    hold_action:
      action: more-info
    styles:
      card:
        - padding: 0.2em
        - '--mdc-ripple-color': yellow
        - '--mdc-ripple-press-opacity': 0.5
      icon:
        - opacity: 0.5
      name:
        - font-size: 0.65em
        - white-space: normal
      state:
        - font-size: 0.65em
        - white-space: normal
      label:
        - font-size: 0.4em
        - white-space: normal
  alerter:
    template: standard
    show_last_changed: true
    color_type: icon
    extra_styles: |
      [[[ return `
        @keyframes pulse {
          20% {
            background-color: ${variables.color};
          }
        }
      `]]]
    state:
      - value: 'on'
        id: value_on
        styles:
          card:
            - animation: pulse 1s infinite
views:
  - icon: mdi:home
    cards:
      - type: vertical-stack
        cards:
          - !include lovelace/thermostat.yaml
          - type: entities
            entities: 
              - cover.garage_door
          - type: entities
            title: Bedroom
            entities:
              - type: custom:paper-buttons-row
                buttons:
                  - entity: light.bedroom_overhead
                    icon: mdi:ceiling-light
                    name: false
                  - entity: light.bedroom_lamps
                    icon: mdi:lamps
                    name: false
                  - entity: switch.bedroom_fan
                    icon: mdi:fan
                    name: false
                  - icon: mdi:bed-empty
                    tap_action:
                      action: call-service
                      service: input_select.select_option
                      service_data:
                        entity_id: input_select.bed_presets
                        option: Flat
                  - icon: mdi:television
                    tap_action:
                      action: call-service
                      service: input_select.select_option
                      service_data:
                        entity_id: input_select.bed_presets
                        option: Watch TV
                  - icon: mdi:book-open
                    tap_action:
                      action: call-service
                      service: input_select.select_option
                      service_data:
                        entity_id: input_select.bed_presets
                        option: Read
              - type: custom:slider-entity-row
                entity: input_number.bed_sleep_number_left
                hide_state: false
                name: Left
              - type: custom:slider-entity-row
                entity: input_number.bed_sleep_number_right
                hide_state: false
                name: Right
          - type: entities
            title: Basement
            entities:
              - type: buttons
                entities:
                  - entity: light.basement
                    show_name: false
                  - entity: switch.basement_stereo
                    icon: mdi:audio-video
                    show_name: false
                  - entity: media_player.basement_tv
                    show_name: false
                  - entity: media_player.playstation_4_basement
                    icon: mdi:sony-playstation
                    show_name: false
                  - entity: input_boolean.workout_mode
                    icon: mdi:weight-lifter
                    show_name: false
      - type: vertical-stack
        cards:
          - !include lovelace/livingroom-controls.yaml
          - type: entities
            title: Game Room
            entities:
              - type: buttons
                entities:
                  - entity: light.gameroom_overhead
                    icon: mdi:ceiling-light
                    show_name: false
                  - entity: light.gameroom_lamp
                    icon: mdi:lamps
                    show_name: false
                  - entity: media_player.gameroom_tv
                    show_name: false
              - type: conditional
                conditions:
                  - entity: media_player.gameroom_receiver
                    state: 'on'
                row:
                  type: custom:slider-entity-row
                  entity: light.game_room_volume
                  icon: mdi:volume-high
                  full_row: true
                  step: 1
                  min: 20
                  max: 100
          - type: entities
            title: Upstairs Bathroom
            entities:
              - type: buttons
                entities:
                  - entity: light.upstairsbathroom
                    show_name: false
                  - entity: switch.upstairsbathroom_vent
                    icon: mdi:fan
                    show_name: false
          - type: entities
            entities:
              - type: custom:slider-entity-row
                entity: light.office
                name: Office
                toggle: true
              - type: custom:slider-entity-row
                entity: light.patio
                name: Patio
                toggle: true
  - icon: mdi:weight-lifter
    cards:
      - !include lovelace/todays_exercise.yaml
      - !include lovelace/garmin_challenges.yaml
      - type: custom:apexcharts-card
        graph_span: 7d
        y_axis_precision: 0
        header:
          title: Daily Mileage
          show: true
          standard_format: true
        all_series_config:
          type: column
          fill_raw: zero
          group_by:
            func: max
            duration: 1d
          show:
            legend_value: false
        series:
          - entity: sensor.run_mileage_today
            name: Run
          - entity: sensor.bike_mileage_today
            name: Bike
          - entity: sensor.walk_mileage_today
            name: Walk
  - icon: mdi:auto-fix
    cards:
      - type: entities
        title: Sleep Mode
        entities:
          - entity: input_boolean.sleep_mode
            name: Sleep Mode
          - type: divider
          - automation.turn_off_sleep_mode
          - automation.turn_on_sleep_mode
          - type: divider
          - entity: input_datetime.keep_sleep_mode_on_until
            name: Keep On Until (Wakeup Time) (hh:mm)
          - entity: input_datetime.turn_on_sleep_mode_after
            name: Turn On After (Bedtime) (hh:mm)
          - entity: input_datetime.turn_off_sleep_mode_if_bed_unoccupied_for
            name: Turn Off If Bed Unoccupied For (mm:ss)
      - type: custom:stack-in-card
        title: Climate
        cards:
          - type: entities
            entities:
              - automation.set_thermostat_temperature
              - type: divider
              - type: custom:multiple-entity-row
                name: Target Temperatures
                entity: sensor.target_temp_heating
                state_header: heat
                entities:
                  - entity: climate.thermostat
                    name: current
                  - entity: sensor.target_temp_cooling
                    name: cool
              - type: divider
          - type: horizontal-stack
            cards:
              - type: entities
                title: Heating
                entities:
                  - entity: input_number.climate_heat_away_temp
                    type: custom:numberbox-card
                  - entity: input_number.climate_heat_asleep_temp
                    type: custom:numberbox-card
                  - entity: input_number.climate_heat_home_temp
                    type: custom:numberbox-card
              - type: entities
                title: Cooling
                entities:
                  - entity: input_number.climate_cool_away_temp
                    type: custom:numberbox-card
                  - entity: input_number.climate_cool_asleep_temp
                    type: custom:numberbox-card
                  - entity: input_number.climate_cool_home_temp
                    type: custom:numberbox-card
          - type: custom:apexcharts-card
            graph_span: 14d
            y_axis_precision: 0
            stacked: true
            apex_config:
              grid:
                show: false
                padding:
                  left: 10
                  right: 10
              yaxis:
                show: false
              legend:
                position: top
            all_series_config:
              fill_raw: zero
              group_by:
                func: max
                duration: 1d
              show:
                legend_value: false
                datalabels: total
            series:
              - type: column
                entity: sensor.hvac_heat_on_today
                name: Heat
                color: orange
              - type: column
                entity: sensor.hvac_fan_only_on_today
                name: Fan
                color: yellow
              - type: column
                entity: sensor.hvac_cool_on_today
                name: Cool
                color: blue
      - type: entities
        title: Upstairs Bathroom
        entities:
          - type: buttons
            entities:
              - entity: binary_sensor.upstairsbathroom_motion
                show_name: false
              - entity: binary_sensor.upstairsbathroom_door
                show_name: false
              - entity: light.upstairsbathroom
                show_name: false
              - entity: switch.upstairsbathroom_vent
                icon: mdi:fan
                show_name: false
          - entity: input_number.upstairsbathroom_light_brightness
            name: Current Brightness
          - entity: input_number.upstairsbathroom_light_transition
            name: Transition
          - entity: input_number.upstairsbathroom_light_sleeping_brightness
            name: Sleeping Brightness
          - entity: input_number.upstairsbathroom_light_day_brightness
            name: Daytime Brightness
          - entity: input_number.upstairsbathroom_light_night_brightness
            name: Nighttime Brightness
          - type: section
            label: Door opens, turn off light if...
          - entity: input_datetime.upstairsbathroom_door_opened_motion_off_for
            name: Motion Off For (mm:ss)
          - entity: input_datetime.upstairsbathroom_door_opened_motion_off_timeout
            name: Motion Off Timeout (mm:ss)
          - type: section
            label: Light off after no motion for...
          - entity: input_datetime.upstairsbathroom_light_off_door_open_for
            name: Door Open (mm:ss)
          - entity: input_datetime.upstairsbathroom_light_off_door_closed_for
            name: Door Closed (mm:ss)
  - icon: mdi:cctv
    panel: true
    cards:
      - type: picture-entity
        entity: camera.driveway
        camera_view: live
  - icon: mdi:home-alert
    cards:
      - type: vertical-stack
        cards:
          - type: custom:button-card
            entity: switch.entry_light
          - type: custom:button-card
            entity: light.livingroom_lamp
          - type: custom:button-card
            entity: light.diningroom
          - type: custom:button-card
            entity: cover.garage_door
          - type: custom:button-card
            entity: group.update_available
            template: alerter
            variables:
              color: blue


      