background: var(--background-image)
button_card_templates:
  standard:
    color_type: card
    size: 80%
    hold_action:
      action: more-info
    styles:
      card:
        - padding: 0.2em
        - '--mdc-ripple-color': yellow
        - '--mdc-ripple-press-opacity': 0.5
      icon:
        - opacity: 0.5
      name:
        - font-size: 0.65em
        - white-space: normal
      state:
        - font-size: 0.65em
        - white-space: normal
      label:
        - font-size: 0.4em
        - white-space: normal
  alerter:
    template: standard
    show_last_changed: true
    color_type: icon
    extra_styles: |
      [[[ return `
        @keyframes pulse {
          20% {
            background-color: ${variables.color};
          }
        }
      `]]]
    state:
      - value: 'on'
        id: value_on
        styles:
          card:
            - animation: pulse 1s infinite
views:
  - icon: mdi:home
    cards:
      - type: vertical-stack
        cards:
          - !include lovelace/cards/thermostat.yaml
          - type: entities
            entities: 
              - cover.garage_door
          - type: entities
            title: Bedroom
            entities:
              - type: custom:paper-buttons-row
                buttons:
                  - entity: light.bedroom_overhead
                    icon: mdi:ceiling-light
                    name: false
                  - entity: light.bedroom_lamps
                    icon: mdi:lamps
                    name: false
                  - entity: switch.bedroom_fan
                    icon: mdi:fan
                    name: false
                  - icon: mdi:bed-empty
                    tap_action:
                      action: call-service
                      service: input_select.select_option
                      service_data:
                        entity_id: input_select.bed_presets
                        option: Flat
                  - icon: mdi:television
                    tap_action:
                      action: call-service
                      service: input_select.select_option
                      service_data:
                        entity_id: input_select.bed_presets
                        option: Watch TV
                  - icon: mdi:book-open
                    tap_action:
                      action: call-service
                      service: input_select.select_option
                      service_data:
                        entity_id: input_select.bed_presets
                        option: Read
              - type: custom:slider-entity-row
                entity: input_number.bed_sleep_number_left
                hide_state: false
                name: Left
              - type: custom:slider-entity-row
                entity: input_number.bed_sleep_number_right
                hide_state: false
                name: Right
          - type: entities
            title: Basement
            entities:
              - type: buttons
                entities:
                  - entity: light.basement
                    show_name: false
                  - entity: switch.basement_stereo
                    icon: mdi:audio-video
                    show_name: false
                  - entity: media_player.basement_tv
                    show_name: false
                  - entity: media_player.playstation_4_basement
                    icon: mdi:sony-playstation
                    show_name: false
                  - entity: input_boolean.workout_mode
                    icon: mdi:weight-lifter
                    show_name: false
      - type: vertical-stack
        cards:
          - !include lovelace/cards/livingroom-controls.yaml
          - type: entities
            title: Game Room
            entities:
              - type: buttons
                entities:
                  - entity: light.gameroom_overhead
                    icon: mdi:ceiling-light
                    show_name: false
                  - entity: light.gameroom_lamp
                    icon: mdi:lamps
                    show_name: false
                  - entity: media_player.gameroom_tv
                    show_name: false
              - type: conditional
                conditions:
                  - entity: media_player.gameroom_receiver
                    state: 'on'
                row:
                  type: custom:slider-entity-row
                  entity: light.game_room_volume
                  icon: mdi:volume-high
                  full_row: true
                  step: 1
                  min: 20
                  max: 100
          - type: entities
            title: Upstairs Bathroom
            entities:
              - type: buttons
                entities:
                  - entity: light.upstairsbathroom
                    show_name: false
                  - entity: switch.upstairsbathroom_vent
                    icon: mdi:fan
                    show_name: false
          - type: entities
            entities:
              - type: custom:slider-entity-row
                entity: light.office
                name: Office
                toggle: true
              - type: custom:slider-entity-row
                entity: light.patio
                name: Patio
                toggle: true
  - icon: mdi:weight-lifter
    cards:
      - !include lovelace/cards/exercise.yaml
      - type: custom:apexcharts-card
        graph_span: 14d
        y_axis_precision: 0
        stacked: true
        apex_config:
          grid:
            show: false
            padding:
              left: 10
              right: 10
          yaxis:
            show: false
          legend:
            position: top
          dataLabels:
            background:
              enabled: false
            style:
              colors: ['#FF2D00', '#FF2D00', '#FF2D00']
        header:
          title: Daily Mileage
          show: true
          standard_format: true
        all_series_config:
          type: column
          fill_raw: zero
          group_by:
            func: max
            duration: 1d
          show:
            legend_value: false
            datalabels: total
        series:
          - entity: sensor.run_mileage_today
            name: Run
          - entity: sensor.bike_mileage_today
            name: Bike
          - entity: sensor.walk_mileage_today
            name: Walk
  - icon: mdi:auto-fix
    cards:
      - type: entities
        title: Sleep Mode
        show_header_toggle: false
        entities:
          - entity: input_boolean.sleep_mode
            name: Sleep Mode
          - type: divider
          - automation.turn_off_sleep_mode
          - automation.turn_on_sleep_mode
          - type: divider
          - entity: input_datetime.keep_sleep_mode_on_until
            name: Keep On Until (Wakeup Time) (hh:mm)
          - entity: input_datetime.turn_on_sleep_mode_after
            name: Turn On After (Bedtime) (hh:mm)
          - entity: input_datetime.turn_off_sleep_mode_if_bed_unoccupied_for
            name: Turn Off If Bed Unoccupied For (mm:ss)
      - type: custom:stack-in-card
        title: Climate
        cards:
          - type: entities
            entities:
              - automation.set_thermostat_temperature
              - type: divider
              - type: custom:multiple-entity-row
                name: Target Temperatures
                entity: sensor.target_temp_heating
                state_header: heat
                entities:
                  - entity: climate.thermostat
                    name: current
                  - entity: sensor.target_temp_cooling
                    name: cool
              - type: divider
          - type: horizontal-stack
            cards:
              - type: entities
                title: Heating
                entities:
                  - entity: input_number.climate_heat_away_temp
                    type: custom:numberbox-card
                  - entity: input_number.climate_heat_asleep_temp
                    type: custom:numberbox-card
                  - entity: input_number.climate_heat_home_temp
                    type: custom:numberbox-card
              - type: entities
                title: Cooling
                entities:
                  - entity: input_number.climate_cool_away_temp
                    type: custom:numberbox-card
                  - entity: input_number.climate_cool_asleep_temp
                    type: custom:numberbox-card
                  - entity: input_number.climate_cool_home_temp
                    type: custom:numberbox-card
          - name: Usage (2 weeks)
            type: custom:mini-graph-card
            aggregate_func: max
            hours_to_show: 336
            decimals: 0
            group_by: date
            show:
              state: false
              icon: false
              legend: false
              labels: true
            entities:
              - entity: sensor.hvac_heat_on_today
                color: red
              - entity: sensor.hvac_cool_on_today
                color: blue
              - entity: sensor.hvac_fan_only_on_today
                color: yellow
      - type: entities
        title: Upstairs Bathroom
        entities:
          - type: buttons
            entities:
              - entity: binary_sensor.upstairsbathroom_motion
                show_name: false
              - entity: input_boolean.upstairsbathroom_occupancy
                show_name: false
              - entity: binary_sensor.upstairsbathroom_door
                show_name: false
              - entity: light.upstairsbathroom
                show_name: false
              - entity: switch.upstairsbathroom_vent
                icon: mdi:fan
                show_name: false
          - entity: input_number.upstairsbathroom_light_brightness
            name: Current Brightness
          - entity: input_number.upstairsbathroom_light_transition
            name: Transition
          - entity: input_number.upstairsbathroom_light_sleeping_brightness
            name: Sleeping Brightness
          - entity: input_number.upstairsbathroom_light_day_brightness
            name: Daytime Brightness
          - entity: input_number.upstairsbathroom_light_night_brightness
            name: Nighttime Brightness
          - type: divider
          - entity: input_number.upstairsbathroom_occupancy_timeout_min
            name: Occupancy Timeout (min)
            type: custom:numberbox-card
          - entity: input_number.upstairsbathroom_occupancy_timeout_sec
            name: Occupancy Timeout (sec)
            type: custom:numberbox-card
          - entity: input_number.upstairsbathroom_no_motion_timeout_min
            name: No Motion Timeout (min)
            type: custom:numberbox-card
      - type: entities
        title: Dehumidifier
        show_header_toggle: false
        entities:
          - sensor.basement_humidity
          - switch.dehumidifier
          - sensor.dehumidifier_power
          - input_number.dehumidifier_off_threshold
          - input_number.dehumidifier_on_threshold
          - automation.turn_on_dehumidifier_if_above_threshold
          - automation.turn_off_dehumidifier_if_below_threshold_or_basement_occupied
      - type: entities
        title: Vacuum
        show_header_toggle: false
        entities:
          - entity: sensor.vacuum_next_room_to_clean
            name: Next Room to Vacuum
          - entity: input_number.vacuum_rooms_cleaned_since_being_emptied
            name: Rooms Cleaned Since Being Emptied
          - entity: input_number.vacuum_max_rooms_cleaned_before_emptying
            type: custom:numberbox-card
            name: Max Rooms Cleaned Before Emptying
          - entity: input_number.run_vacuum_after_away_min
            type: custom:numberbox-card
            name: Run Vacuum After Away For... (Minutes)
          - entity: input_boolean.vacuum_enable_all_rooms
            name: All Rooms
          - type: divider
          - type: custom:multiple-entity-row
            name: Game Room
            entity: input_boolean.vacuum_gameroom_16_enable
            toggle: true
            entities:
              - entity: input_datetime.vacuum_gameroom_16_last_cleaned
                name: false
          - type: custom:multiple-entity-row
            name: Hallway
            entity: input_boolean.vacuum_hallway_17_enable
            toggle: true
            entities:
              - entity: input_datetime.vacuum_hallway_17_last_cleaned
                name: false
          - type: custom:multiple-entity-row
            name: Bedroom
            entity: input_boolean.vacuum_bedroom_18_enable
            toggle: true
            entities:
              - entity: input_datetime.vacuum_bedroom_18_last_cleaned
                name: false
          - type: custom:multiple-entity-row
            name: Living Room
            entity: input_boolean.vacuum_livingroom_19_enable
            toggle: true
            entities:
              - entity: input_datetime.vacuum_livingroom_19_last_cleaned
                name: false
          - type: custom:multiple-entity-row
            name: Kitchen
            entity: input_boolean.vacuum_kitchen_20_enable
            toggle: true
            entities:
              - entity: input_datetime.vacuum_kitchen_20_last_cleaned
                name: false
          - type: custom:multiple-entity-row
            name: Dining Room
            entity: input_boolean.vacuum_diningroom_21_enable
            toggle: true
            entities:
              - entity: input_datetime.vacuum_diningroom_21_last_cleaned
                name: false
          - type: custom:multiple-entity-row
            name: Office
            entity: input_boolean.vacuum_office_22_enable
            toggle: true
            entities:
              - entity: input_datetime.vacuum_office_22_last_cleaned
                name: false
          - type: custom:multiple-entity-row
            name: Upstairs Bathroom
            entity: input_boolean.vacuum_upstairsbathroom_23_enable
            toggle: true
            entities:
              - entity: input_datetime.vacuum_upstairsbathroom_23_last_cleaned
                name: false
  - icon: mdi:cctv
    panel: true
    cards:
      - type: custom:webrtc-camera
        entity: camera.driveway
  - icon: mdi:home-alert
    cards:
      - type: entities
        title: Doors
        entities:
          - entity: binary_sensor.basement_door
          - entity: binary_sensor.bedroom_door
            name: Bedroom Door
          - entity: binary_sensor.front_door
          - entity: binary_sensor.garage_door
          - entity: binary_sensor.garage_inner_door
          - entity: binary_sensor.garage_outer_door
          - entity: binary_sensor.laundryroom_door
            name: Laundry Room Door
          - entity: binary_sensor.patio_door
            name: Patio Door
          - entity: binary_sensor.sliding_side_door
            name: Sliding Side Door
          - entity: binary_sensor.upstairsbathroom_door
      - type: entities
        title: Windows
        entities:
          - entity: binary_sensor.bedroom_window_back
            name: Bedroom Window (Back)
          - entity: binary_sensor.bedroom_window_side
            name: Bedroom Window (Side)
          - entity: binary_sensor.front_bay_window_left
            name: Front Bay Window (Left)
          - entity: binary_sensor.front_bay_window_right
            name: Front Bay Window (Right)
          - entity: binary_sensor.gameroom_window_side
            name: Game Room Window (Side)
          - entity: binary_sensor.kitchen_window
            name: Kitchen Window
          - entity: binary_sensor.office_window
            name: Office Window
      - type: entities
        title: Motion
        entities:
          - binary_sensor.basement_motion
          - entity: binary_sensor.diningroom_motion_1
            name: Dining Room Motion (Above Fridge)
          - entity: binary_sensor.laundryroom_motion
            name: Laundry Room Motion
          - entity: binary_sensor.patio_motion_1
            name: Patio Motion (Above Sliding Door)
          - entity: binary_sensor.upstairsbathroom_motion
            name: Upstairs Bathroom Motion


      