background: var(--background-image)
button_card_templates:
  standard:
    color_type: card
    size: 80%
    hold_action:
      action: more-info
    styles:
      card:
        - padding: 0.2em
        - "--mdc-ripple-color": yellow
        - "--mdc-ripple-press-opacity": 0.5
      icon:
        - opacity: 0.5
      name:
        - font-size: 0.65em
        - white-space: normal
      state:
        - font-size: 0.65em
        - white-space: normal
      label:
        - font-size: 0.4em
        - white-space: normal
  alerter:
    template: standard
    show_last_changed: true
    color_type: icon
    extra_styles: |
      [[[ return `
        @keyframes pulse {
          20% {
            background-color: ${variables.color};
          }
        }
      `]]]
    state:
      - value: "on"
        id: value_on
        styles:
          card:
            - animation: pulse 1s infinite
views:
  - icon: mdi:home
    cards:
      - type: vertical-stack
        cards:
          - !include lovelace/cards/thermostat.yaml
          - type: entities
            entities:
              - cover.garage_door
          - type: entities
            title: Bedroom
            entities:
              - type: custom:paper-buttons-row
                buttons:
                  - entity: light.bedroom_overhead
                    icon: mdi:ceiling-light
                    name: false
                  - entity: light.bedroom_lamps
                    icon: mdi:lamps
                    name: false
                  - entity: switch.bedroom_fan
                    icon: mdi:fan
                    name: false
                  - icon: mdi:bed-empty
                    tap_action:
                      action: call-service
                      service: input_select.select_option
                      service_data:
                        entity_id: input_select.bed_presets
                        option: Flat
                  - icon: mdi:television
                    tap_action:
                      action: call-service
                      service: input_select.select_option
                      service_data:
                        entity_id: input_select.bed_presets
                        option: Watch TV
                  - icon: mdi:book-open
                    tap_action:
                      action: call-service
                      service: input_select.select_option
                      service_data:
                        entity_id: input_select.bed_presets
                        option: Read
              - type: custom:slider-entity-row
                entity: input_number.bed_sleep_number_left
                hide_state: false
                name: Left
              - type: custom:slider-entity-row
                entity: input_number.bed_sleep_number_right
                hide_state: false
                name: Right
          - type: entities
            title: Basement
            entities:
              - type: buttons
                entities:
                  - entity: light.basement
                    show_name: false
                  - entity: switch.basement_stereo
                    icon: mdi:audio-video
                    show_name: false
                  - entity: media_player.basement_tv
                    show_name: false
                  - entity: media_player.playstation_4_basement
                    icon: mdi:sony-playstation
                    show_name: false
                  - entity: input_boolean.workout_mode
                    icon: mdi:weight-lifter
                    show_name: false
      - type: vertical-stack
        cards:
          - !include lovelace/cards/livingroom-controls.yaml
          - type: entities
            title: Game Room
            entities:
              - type: buttons
                entities:
                  - entity: light.gameroom_overhead
                    icon: mdi:ceiling-light
                    show_name: false
                  - entity: light.gameroom_lamp
                    icon: mdi:lamps
                    show_name: false
                  - entity: media_player.gameroom_tv
                    show_name: false
              - type: conditional
                conditions:
                  - entity: media_player.gameroom_receiver
                    state: "on"
                row:
                  type: custom:slider-entity-row
                  entity: light.game_room_volume
                  icon: mdi:volume-high
                  full_row: true
                  step: 1
                  min: 20
                  max: 100
          - type: entities
            title: Upstairs Bathroom
            entities:
              - type: buttons
                entities:
                  - entity: light.upstairsbathroom
                    show_name: false
                  - entity: switch.upstairsbathroom_vent
                    icon: mdi:fan
                    show_name: false
          - type: entities
            entities:
              - type: custom:slider-entity-row
                entity: light.office
                name: Office
                toggle: true
              - type: custom:slider-entity-row
                entity: light.patio
                name: Patio
                toggle: true
  - icon: mdi:server
    cards:
      - type: horizontal-stack
        title: Home Assistant Deployment
        cards:
          - type: custom:button-card
            entity: input_select.hass_deployment_status
            color_type: icon
            icon: mdi:autorenew
            color: yellow
            show_name: false
            show_state: true
            state:
              - value: Up To Date
                icon: mdi:check-circle
                color: green
              - value: Error
                icon: mdi:alert-circle
                color: red
                styles:
                  icon:
                    - animation:
                      - blink 1s linear infinite
              - value: Checking Configuration
                spin: true
              - value: Deploying Configuration
                spin: true
              - value: Restarting Server
                spin: true
        
  - icon: mdi:auto-fix
    cards:
      - !include lovelace/cards/automation_config/vacuum.yaml
      - !include lovelace/cards/automation_config/single_occupancy_mode.yaml
      - !include lovelace/cards/automation_config/climate.yaml
      - !include lovelace/cards/room_config/upstairsbathroom.yaml
      - !include lovelace/cards/automation_config/dehumidifier.yaml
      - !include lovelace/cards/recent_automations.yaml
  - icon: mdi:cctv
    panel: true
    cards:
      - type: picture-entity
        entity: camera.driveway
        camera_view: live
  - icon: mdi:home-alert
    cards:
      - type: entities
        title: Doors
        entities:
          - entity: binary_sensor.basement_door
          - entity: binary_sensor.bedroom_door
            name: Bedroom Door
          - entity: binary_sensor.front_door
          - entity: binary_sensor.garage_door
          - entity: binary_sensor.garage_inner_door
          - entity: binary_sensor.garage_outer_door
          - entity: binary_sensor.laundryroom_door
            name: Laundry Room Door
          - entity: binary_sensor.patio_door
            name: Patio Door
          - entity: binary_sensor.sliding_side_door
            name: Sliding Side Door
          - entity: binary_sensor.upstairsbathroom_door
      - type: entities
        title: Windows
        entities:
          - entity: binary_sensor.bedroom_window_back
            name: Bedroom Window (Back)
          - entity: binary_sensor.bedroom_window_side
            name: Bedroom Window (Side)
          - entity: binary_sensor.front_bay_window_left
            name: Front Bay Window (Left)
          - entity: binary_sensor.front_bay_window_right
            name: Front Bay Window (Right)
          - entity: binary_sensor.gameroom_window_side
            name: Game Room Window (Side)
          - entity: binary_sensor.kitchen_window
            name: Kitchen Window
          - entity: binary_sensor.office_window
            name: Office Window
      - type: entities
        title: Motion
        entities:
          - sensor.last_occupied_room
          - group.basement_occupancy
          - group.bedroom_occupancy
          - group.diningroom_occupancy
          - group.gameroom_occupancy
          - group.garage_occupancy
          - group.kitchen_occupancy
          - group.laundryroom_occupancy
          - group.livingroom_occupancy
          - group.office_occupancy
          - group.patio_occupancy
          - group.upstairsbathroom_occupancy
