views:
  - icon: mdi:home
    cards:
      - type: vertical-stack
        cards:
          - !include lovelace/cards/thermostat.yaml
          - type: history-graph
            entities:
              - sensor.diningroom_temperature
              - sensor.masterbedroom_temperature
              - sensor.office_temperature
              - sensor.pantry_temperature
              - sensor.overlord_apparent_temperature
            hours_to_show: 36
            title: Room Temperatures
          - type: entities
            title: Bedroom
            entities:
              - type: custom:paper-buttons-row
                buttons:
                  - entity: light.bedroom_lamps
                    icon: mdi:lamps
                    name: false
                  - icon: mdi:bed-empty
                    tap_action:
                      action: call-service
                      service: select.select_option
                      service_data:
                        entity_id: select.sleepnumber_master_bed_foundation_preset
                        option: Flat
                  - icon: mdi:television
                    tap_action:
                      action: call-service
                      service: select.select_option
                      service_data:
                        entity_id: select.sleepnumber_master_bed_foundation_preset
                        option: Watch TV
                  - icon: mdi:book-open
                    tap_action:
                      action: call-service
                      service: select.select_option
                      service_data:
                        entity_id: select.sleepnumber_master_bed_foundation_preset
                        option: Read
              - type: custom:slider-entity-row
                entity: number.sleepnumber_master_bed_guest_firmness
                hide_state: false
                name: Left
              - type: custom:slider-entity-row
                entity: number.sleepnumber_master_bed_mike_firmness
                hide_state: false
                name: Right
  - icon: mdi:server
    cards:
      - type: grid
        title: Home Assistant Deployment
        square: true
        columns: 2
        cards:
          - type: custom:button-card
            entity: sensor.mfugate1_home_assistant_config_issues
            name: Open Issues
            show_state: true
            show_icon: false
            aspect_ratio: 1/1
          - type: custom:button-card
            entity: input_select.hass_deployment_status
            color_type: icon
            icon: mdi:autorenew
            aspect_ratio: 1/1
            color: yellow
            show_name: false
            show_state: true
            state:
              - value: Up To Date
                icon: mdi:check-circle
                color: green
              - value: Error
                icon: mdi:alert-circle
                color: red
                styles:
                  icon:
                    - animation:
                      - blink 1s linear infinite
              - value: Checking Configuration
                spin: true
              - value: Deploying Configuration
                spin: true
              - value: Restarting Server
                spin: true
        
  - icon: mdi:auto-fix
    cards:
      - !include lovelace/cards/automation_config/vacuum.yaml
      - !include lovelace/cards/tasks.yaml
      - !include lovelace/cards/automation_config/single_occupancy_mode.yaml
      - !include lovelace/cards/automation_config/climate.yaml
      - !include lovelace/cards/room_config/firstfloorbathroom.yaml
      - !include lovelace/cards/automation_config/dehumidifier.yaml
      - !include lovelace/cards/recent_automations.yaml
  - icon: mdi:cctv
    panel: true
    cards:
      - type: picture-entity
        entity: camera.driveway
        camera_view: live
  - icon: mdi:home-alert
    cards:
      - type: entities
        title: Doors
        entities:
          - entity: binary_sensor.basement_door
          - entity: binary_sensor.bedroom_door
            name: Bedroom Door
          - entity: binary_sensor.front_door
          - entity: binary_sensor.garage_door
          - entity: binary_sensor.garage_inner_door
          - entity: binary_sensor.garage_outer_door
          - entity: binary_sensor.laundryroom_door
            name: Laundry Room Door
          - entity: binary_sensor.patio_door
            name: Patio Door
          - entity: binary_sensor.sliding_side_door
            name: Sliding Side Door
          - entity: binary_sensor.upstairsbathroom_door
      - type: entities
        title: Windows
        entities:
          - entity: binary_sensor.bedroom_window_back
            name: Bedroom Window (Back)
          - entity: binary_sensor.bedroom_window_side
            name: Bedroom Window (Side)
          - entity: binary_sensor.front_bay_window_left
            name: Front Bay Window (Left)
          - entity: binary_sensor.front_bay_window_right
            name: Front Bay Window (Right)
          - entity: binary_sensor.gameroom_window_side
            name: Game Room Window (Side)
          - entity: binary_sensor.kitchen_window
            name: Kitchen Window
          - entity: binary_sensor.office_window
            name: Office Window
      - type: custom:stack-in-card
        title: Occupancy
        cards:
          - type: glance
            columns: 3
            entities:
              - person.mike
              - group.guest_devices
              - binary_sensor.someone_is_home
          - type: grid
            square: false
            columns: 2
            cards:
              - type: entities
                entities:
                  - type: custom:multiple-entity-row
                    canary_style:
                      margin: 0px -15px
                    name: Office 1
                    entity: binary_sensor.office_aqara_fp1_presence
                    state_color: true
                    show_state: false
                    secondary_info:
                      entity: sensor.office_aqara_fp1_presence_event
                      name: false
                  - type: custom:multiple-entity-row
                    canary_style:
                      margin: 0px -15px
                    name: Office 2
                    entity: binary_sensor.office_aqara_fp1_2_presence
                    state_color: true
                    show_state: false
                    secondary_info:
                      entity: sensor.office_aqara_fp1_2_presence_event
                      name: false
                  - type: custom:multiple-entity-row
                    canary_style:
                      margin: 0px -15px
                    name: Game Room
                    entity: binary_sensor.gameroom_aqara_fp1_presence
                    state_color: true
                    show_state: false
                    secondary_info:
                      entity: sensor.gameroom_aqara_fp1_presence_event
                      name: false
                  - type: custom:multiple-entity-row
                    canary_style:
                      margin: 0px -15px
                    name: Dining Room
                    entity: binary_sensor.diningroom_aqara_fp1_presence
                    state_color: true
                    show_state: false
                    secondary_info:
                      entity: sensor.diningroom_aqara_fp1_presence_event
                      name: false
              - type: entities
                entities:
                  - type: custom:multiple-entity-row
                    canary_style:
                      margin: 0px -15px
                    name: Bedroom
                    entity: binary_sensor.bedroom_aqara_fp1_presence
                    state_color: true
                    show_state: false
                    secondary_info:
                      entity: sensor.bedroom_aqara_fp1_presence_event
                      name: false
                  - type: custom:multiple-entity-row
                    canary_style:
                      margin: 0px -15px
                    name: Upstairs Bathroom
                    entity: binary_sensor.upstairsbathroom_aqara_fp1_presence
                    state_color: true
                    show_state: false
                    secondary_info:
                      entity: sensor.upstairsbathroom_aqara_fp1_presence_event
                      name: false
                  - type: custom:multiple-entity-row
                    canary_style:
                      margin: 0px -15px
                    name: Basement
                    entity: binary_sensor.basement_aqara_fp1_presence
                    state_color: true
                    show_state: false
                    secondary_info:
                      entity: sensor.basement_aqara_fp1_presence_event
                      name: false
                  - type: custom:multiple-entity-row
                    canary_style:
                      margin: 0px -15px
                    name: Laundry Room
                    entity: binary_sensor.laundryroom_aqara_fp1_presence
                    state_color: true
                    show_state: false
                    secondary_info:
                      entity: sensor.laundryroom_aqara_fp1_presence_event
                      name: false
