group:
  office_music_presence:
    entities:
      - binary_sensor.master_bathroom_presence_all_zones
      - binary_sensor.master_bedroom_presence_all_zones
      - binary_sensor.office_presence_all_zones
      - binary_sensor.guest_room_single_presence_all_zones
      - binary_sensor.guest_room_double_presence_all_zones

automation:
  - alias: Office - Music - Adjust Volume For Presence
    id: office_music_adjust_volume_for_presence
    mode: queued
    triggers:
      - trigger: state
        entity_id: binary_sensor.office_presence_all_zones
        to:
          - 'off'
          - 'on'
    conditions:
      - condition: state
        entity_id: media_player.office_wiim
        state: playing
      - condition: state
        entity_id: media_player.office_wiim
        attribute: source
        state: Spotify
    actions:
      - action: grad_vol.set_volume
        target:
          entity_id: media_player.office_wiim
        data:
          duration: "{{ states('input_number.office_music_adjust_volume_for_presence_duration') | int(5) }}"
          volume: "{{ states('input_number.office_music_adjust_volume_for_presence_level_' + trigger.to_state.state) | float / 100 }}"

  - alias: Office - Music - Save Volume Adjustments
    id: office_music_save_volume_adjustments
    mode: queued
    triggers:
      - trigger: state
        entity_id: media_player.office_wiim
        attribute: volume_level
    actions:
      - action: input_number.set_value
        target:
          entity_id: input_number.office_music_adjust_volume_for_presence_level_{{ states('binary_sensor.office_presence_all_zones') }}
        data:
          value: "{{ state_attr('media_player.office_wiim', 'volume_level') | float * 100 }}"

script:
  office_audio_pc:
    alias: Office Audio - PC
    mode: queued
    sequence:
      - action: switch.turn_on
        entity_id: switch.office_speakers
      - action: media_player.unjoin
        target:
          entity_id: media_player.office_wiim
      - action: media_player.select_source
        target:
          entity_id: media_player.office_wiim
        data:
          source: "{{ states('input_text.office_linkplay_pc_source') }}"

input_number:
  office_music_adjust_volume_for_presence_duration:
    min: 0
    max: 30
    mode: box
    unit_of_measurement: s
  office_music_adjust_volume_for_presence_level_off: &level
    min: 0
    max: 100
    mode: box
  office_music_adjust_volume_for_presence_level_on: *level

input_text:
  office_pc_source:

template:
  - select:
    - name: office_pc_source
      unique_id: office_pc_source
      state: "{{ states('input_text.office_pc_source') }}"
      options: "{{ state_attr('media_player.office_wiim', 'source_list') }}"
      select_option:
        action: input_text.set_value
        entity_id: input_text.office_pc_source
        data:
          value: "{{ option }}"