group:
  office_music_presence:
    entities:
      - binary_sensor.master_bathroom_presence_all_zones
      - binary_sensor.master_bedroom_presence_all_zones
      - binary_sensor.office_presence_all_zones
      - binary_sensor.guest_room_single_presence_all_zones
      - binary_sensor.guest_room_double_presence_all_zones

automation:
  - alias: Office - Music - Adjust Volume
    id: office_music_adjust_volume
    mode: queued
    triggers:
      - trigger: state
        entity_id: sensor.office_audio_volume_level
      - trigger: state
        entity_id: binary_sensor.office_music_playing
        to: 'on'
    conditions:
      - condition: state
        entity_id: binary_sensor.office_music_playing
        state: 'on'
    actions:
      - action: grad_vol.set_volume
        target:
          entity_id: media_player.office_wiim
        data:
          duration: >
            {% if is_state('assist_satellite.home_assistant_voice_office_assist_satellite', 'idle') %}
              {{ states('input_number.office_music_adjust_volume_for_presence_duration') | int(5) }}
            {% else %}
              0
            {% endif %}
          volume: "{{ states('sensor.office_audio_volume_level') | float }}"

  - alias: Office - Music - Save Volume Adjustments
    id: office_music_save_volume_adjustments
    mode: queued
    triggers:
      - trigger: state
        entity_id: media_player.office_wiim
        attribute: volume_level
    conditions:
      - condition: state
        entity_id: assist_satellite.home_assistant_voice_office_assist_satellite
        state: idle
    actions:
      - action: input_number.set_value
        target:
          entity_id: input_number.office_music_adjust_volume_for_presence_level_{{ states('binary_sensor.office_presence_all_zones') }}
        data:
          value: "{{ state_attr('media_player.office_wiim', 'volume_level') | float * 100 }}"

script:
  office_audio_pc:
    alias: Office Audio - PC
    mode: queued
    sequence:
      - action: switch.turn_on
        entity_id: switch.office_speakers
      - action: linkplay.unjoin
        data:
          entity_id: media_player.office_wiim
      - action: media_player.select_source
        target:
          entity_id: media_player.office_wiim
        data:
          source: "{{ states('input_text.office_pc_source') }}"

conversation:
  intents:
    PCAudio:
      - "(switch|change|go) [to] [the] pc audio"
      - "(switch|change|go) [to] [the] line in"

intent_script:
  PCAudio:
    speech: 
      text: Audio switched to line in
    action:
      - action: script.turn_on
        target:
          entity_id: script.office_audio_pc

input_number:
  office_music_adjust_volume_for_presence_duration:
    min: 0
    max: 30
    mode: box
    unit_of_measurement: s
  office_music_adjust_volume_for_presence_level_off: &level
    min: 0
    max: 100
    mode: box
  office_music_adjust_volume_for_presence_level_on: *level
  office_music_adjust_volume_for_assist_active: *level

input_text:
  office_pc_source:

template:
  - binary_sensor:
    - name: office_music_playing
      state: "{{ is_state('media_player.office_wiim', 'playing') and is_state_attr('media_player.office_wiim', 'source', 'Spotify') }}"

  - sensor:
    - name: office_audio_volume_level
      state: >
        {% if not is_state('assist_satellite.home_assistant_voice_office_assist_satellite', 'idle') %}
          {% set entity = 'office_music_adjust_volume_for_assist_active' %}
        {% else %}
          {% set entity = 'office_music_adjust_volume_for_presence_level_' + states('binary_sensor.office_presence_all_zones') %}
        {% endif %}
        {{ states('input_number.' + entity) | float / 100 }}

  - select:
    - name: office_pc_source
      unique_id: office_pc_source
      state: "{{ states('input_text.office_pc_source') }}"
      options: "{{ state_attr('media_player.office_wiim', 'source_list') }}"
      select_option:
        action: input_text.set_value
        entity_id: input_text.office_pc_source
        data:
          value: "{{ option }}"