- platform: template
  lights:
    entry_light:
      friendly_name: Entry Light
      entity_id: switch.entry_light
      level_template: >-
        {% if is_state('switch.entry_light', 'on') %}
          100
        {% else %}
          0
        {% endif %}
      value_template: "{{ is_state('switch.entry_light', 'on') }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.entry_light
      turn_off:
        service: switch.turn_off
        entity_id: switch.entry_light
      set_level:
        service: switch.turn_on
        entity_id: switch.entry_light