- platform: template
  lights:
    game_room_volume:
      friendly_name: Volume
      level_template: >-
        {% if is_state('media_player.gameroom_receiver', 'on') %}
          {{ states.media_player.gameroom_receiver.attributes.volume_level | float * 80 }}
        {% else %}
          0
        {% endif %}
      value_template: >-
        {% if is_state('media_player.gameroom_receiver', 'on') %}
          {% if states.media_player.gameroom_receiver.attributes.is_volume_muted %}
            off
          {% else %}
            on
          {% endif %}
        {% else %}
          off
        {% endif %}
      turn_on:
        service: media_player.volume_mute
        entity_id: media_player.gameroom_receiver
        data:
          is_volume_muted: false
      turn_off:
        service: media_player.volume_mute
        entity_id: media_player.gameroom_receiver
        data:
          is_volume_muted: true
      set_level:
        service: media_player.volume_set
        entity_id: media_player.gameroom_receiver
        data:
          volume_level: "{{ (brightness / 255 * 100) | int / 80 }}"
    living_room_volume:
      friendly_name: Living Room Volume
      level_template: >-
        {% if is_state('media_player.livingroom_receiver', 'on') %}
          {{ states.media_player.livingroom_receiver.attributes.volume_level | float * 80 }}
        {% else %}
          0
        {% endif %}
      value_template: >-
        {% if is_state('media_player.livingroom_receiver', 'on') %}
          {% if states.media_player.livingroom_receiver.attributes.is_volume_muted %}
            off
          {% else %}
            on
          {% endif %}
        {% else %}
          off
        {% endif %}
      turn_on:
        service: media_player.volume_mute
        entity_id: media_player.livingroom_receiver
        data:
          is_volume_muted: false
      turn_off:
        service: media_player.volume_mute
        entity_id: media_player.livingroom_receiver
        data:
          is_volume_muted: true
      set_level:
        service: media_player.volume_set
        entity_id: media_player.livingroom_receiver
        data:
          volume_level: "{{ (brightness / 255 * 100) | int / 80 }}"