automation:

  - alias: First Floor Bathroom - Lights On
    id: first_floor_bathroom_lights_on
    max_exceeded: silent
    triggers:
      - trigger: state
        entity_id: binary_sensor.first_floor_bathroom_presence_all_zones
        to: 'on'
      - trigger: state
        entity_id: sensor.firstfloorbathroom_presence_sensor_presence_event
        to:
          - enter
          - approach
    actions:
      - action: light.turn_on
        entity_id: light.firstfloorbathroom
        data:
          brightness: "{{ states('sensor.firstfloorbathroom_light_brightness') | int(255) }}"
          transition: "{{ states('sensor.firstfloorbathroom_light_transition') | int(0) }}"
      - delay: 10
      - if:
          - condition: state
            entity_id: binary_sensor.first_floor_bathroom_presence_all_zones
            state: 'off'
        then:
          - action: automation.trigger
            entity_id: automation.first_floor_bathroom_lights_off

  - alias: First Floor Bathroom - Lights Off
    id: first_floor_bathroom_lights_off
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.first_floor_bathroom_presence_all_zones
        to: 'off'
    actions:
      - action: light.turn_off
        entity_id: light.firstfloorbathroom
        data:
          transition: "{{ states('sensor.firstfloorbathroom_light_transition') | int(0) }}"

template:
  - sensor:
    - name: firstfloorbathroom_light_brightness
      state: >-
        {% if is_state('sun.sun', 'above_horizon') %}
          {{ states('input_number.firstfloorbathroom_light_day_brightness') }}
        {% else %}
          {{ states('input_number.firstfloorbathroom_light_night_brightness') }}
        {% endif %}
    - name: firstfloorbathroom_light_transition
      state: >-
        {% if is_state('sun.sun', 'above_horizon') %}
          {{ states('input_number.firstfloorbathroom_light_day_transition') }}
        {% else %}
          {{ states('input_number.firstfloorbathroom_light_night_transition') }}
        {% endif %}

input_number:
  firstfloorbathroom_light_day_brightness:
    name: Daytime Brightness
    icon: mdi:brightness-5
    min: 1
    max: 255
    mode: box
  firstfloorbathroom_light_night_brightness:
    name: Nighttime Brightness
    icon: mdi:brightness-4
    min: 1
    max: 255
    mode: box
  firstfloorbathroom_light_day_transition:
    name: Daytime Transition
    icon: mdi:arrow-right
    min: 0
    max: 10
    mode: box
  firstfloorbathroom_light_night_transition:
    name: Nighttime Transition
    icon: mdi:arrow-right
    min: 0
    max: 10
    mode: box