- platform: template
  switches:
    circulation:
      friendly_name: Fan Circulation
      icon_template: mdi:fan
      value_template: "{{ is_state_attr('climate.honeywell_thermostat', 'fan_mode', 'Circulate') }}"
      turn_on:
        service: climate.set_fan_mode
        data:
          entity_id: climate.honeywell_thermostat
          fan_mode: Circulate
      turn_off:
        service: climate.set_fan_mode
        data:
          entity_id: climate.honeywell_thermostat
          fan_mode: Auto Low