- platform: template
  switches:
    circulation:
      friendly_name: Circulate
      icon_template: mdi:fan
      value_template: "{{ is_state_attr('climate.thermostat', 'fan_mode', 'Circulation') }}"
      availability_template: "{{ not is_state('climate.thermostat', 'unavailable') }}"
      turn_on:
        service: climate.set_fan_mode
        data:
          entity_id: climate.thermostat
          fan_mode: Circulation
      turn_off:
        service: climate.set_fan_mode
        data:
          entity_id: climate.thermostat
          fan_mode: Auto low
    fan_auto:
      friendly_name: Auto
      icon_template: mdi:fan
      value_template: "{{ is_state_attr('climate.thermostat', 'fan_mode', 'Auto low') }}"
      availability_template: "{{ not is_state('climate.thermostat', 'unavailable') }}"
      turn_on:
        service: climate.set_fan_mode
        data:
          entity_id: climate.thermostat
          fan_mode: Auto low
      turn_off:
        service: climate.set_fan_mode
        data:
          entity_id: climate.thermostat
          fan_mode: Auto low
    fan_on:
      friendly_name: 'On'
      icon_template: mdi:fan
      value_template: "{{ is_state_attr('climate.thermostat', 'fan_mode', 'Low') }}"
      availability_template: "{{ not is_state('climate.thermostat', 'unavailable') }}"
      turn_on:
        service: climate.set_fan_mode
        data:
          entity_id: climate.thermostat
          fan_mode: 'Low'
      turn_off:
        service: climate.set_fan_mode
        data:
          entity_id: climate.thermostat
          fan_mode: Auto low
    next_fan_mode:
      icon_template: mdi:fan
      value_template: false
      availability_template: "{{ not is_state('climate.thermostat', 'unavailable') }}"
      turn_on:
        service: climate.set_fan_mode
        data:
          entity_id: climate.thermostat
          fan_mode: >-
            {% if is_state_attr('climate.thermostat', 'fan_mode', 'Low') %}
              Circulation
            {% elif is_state_attr('climate.thermostat', 'fan_mode', 'Auto low') %}
              Low
            {% else %}
              Auto low
            {% endif %}
      turn_off:
        service: climate.set_fan_mode
        data:
          entity_id: climate.thermostat
          fan_mode: "{{ state_attr('climate.thermostat', 'fan_mode') }}"
    heat_mode:
      icon_template: mdi:fire
      value_template: "{{ is_state('climate.thermostat', 'heat') }}"
      availability_template: "{{ not is_state('climate.thermostat', 'unavailable') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.thermostat
          hvac_mode: heat
      turn_off:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.thermostat
          hvac_mode: 'off'
    cool_mode:
      icon_template: mdi:snowflake
      value_template: "{{ is_state('climate.thermostat', 'cool') }}"
      availability_template: "{{ not is_state('climate.thermostat', 'unavailable') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.thermostat
          hvac_mode: cool
      turn_off:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.thermostat
          hvac_mode: 'off'
    hvac_off:
      icon_template: mdi:power
      value_template: "{{ is_state('climate.thermostat', 'off') }}"
      availability_template: "{{ not is_state('climate.thermostat', 'unavailable') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.thermostat
          hvac_mode: 'off'
      turn_off:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.thermostat
          hvac_mode: 'off'
      