- platform: template
  switches:
    livingroom_disneyplus:
      friendly_name: Disney+
      icon_template: phu:disney-plus
      value_template: "{{ is_state('binary_sensor.livingroom_roku_media_active', 'on') and is_state_attr('media_player.livingroom_roku', 'source', 'Disney Plus') }}"
      availability_template: "{{ is_state('binary_sensor.livingroom_roku_available', 'on') }}"
      turn_on:
        - parallel:
          - service: script.select_livingroom_sources
            data:
              media_type: roku
          - service: media_player.select_source
            entity_id: media_player.livingroom_roku
            data:
              source: Disney Plus
      turn_off:
        - parallel:
          - service: remote.send_command
            entity_id: remote.livingroom_roku
            data:
              command:
                - home
          - service: media_player.turn_off
            entity_id: media_player.livingroom_tv
          - service: media_player.turn_off
            entity_id: media_player.livingroom_receiver
    
    livingroom_hbomax:
      friendly_name: HBO Max
      icon_template: phu:hbo-max
      value_template: "{{ is_state('binary_sensor.livingroom_roku_media_active', 'on') and is_state_attr('media_player.livingroom_roku', 'source', 'HBO Max') }}"
      availability_template: "{{ is_state('binary_sensor.livingroom_roku_available', 'on') }}"
      turn_on:
        - parallel:
          - service: script.select_livingroom_sources
            data:
              media_type: roku
          - service: media_player.select_source
            entity_id: media_player.livingroom_roku
            data:
              source: HBO Max
      turn_off:
        - parallel:
          - service: remote.send_command
            entity_id: remote.livingroom_roku
            data:
              command:
                - home
          - service: media_player.turn_off
            entity_id: media_player.livingroom_tv
          - service: media_player.turn_off
            entity_id: media_player.livingroom_receiver

    livingroom_hulu:
      friendly_name: Hulu
      icon_template: mdi:hulu
      value_template: "{{ is_state('binary_sensor.livingroom_roku_media_active', 'on') and is_state_attr('media_player.livingroom_roku', 'source', 'Hulu') }}"
      availability_template: "{{ is_state('binary_sensor.livingroom_roku_available', 'on') }}"
      turn_on:
        - parallel:
          - service: script.select_livingroom_sources
            data:
              media_type: roku
          - service: media_player.select_source
            entity_id: media_player.livingroom_roku
            data:
              source: Hulu
      turn_off:
        - parallel:
          - service: remote.send_command
            entity_id: remote.livingroom_roku
            data:
              command:
                - home
          - service: media_player.turn_off
            entity_id: media_player.livingroom_tv
          - service: media_player.turn_off
            entity_id: media_player.livingroom_receiver

    livingroom_music:
      friendly_name: Music
      icon_template: mdi:music
      value_template: "{{ is_state('media_player.livingroom_squeezebox', 'playing') and is_state('media_player.livingroom_receiver', 'on') and is_state_attr('media_player.livingroom_receiver', 'source', 'Video 2') }}"
      availability_template: "{{ not is_state('media_player.livingroom_receiver', 'unavailable') and not is_state('media_player.livingroom', 'unavailable') }}"
      turn_on:
        - parallel:
          - service: script.select_livingroom_sources
            data:
              media_type: music
          - service: rest_command.livingroom_squeezebox_liked_songs_playlist
        - service: media_player.volume_set
          entity_id: media_player.livingroom_receiver
          data:
            volume_level: 0.39
      turn_off:
        - parallel:
          - service: media_player.clear_playlist
            entity_id: media_player.livingroom_squeezebox
          - service: media_player.turn_off
            entity_id: media_player.livingroom_receiver

    livingroom_netflix:
      friendly_name: Netflix
      icon_template: mdi:netflix
      value_template: "{{ is_state('binary_sensor.livingroom_roku_media_active', 'on') and is_state_attr('media_player.livingroom_roku', 'source', 'Netflix') }}"
      availability_template: "{{ is_state('binary_sensor.livingroom_roku_available', 'on') }}"
      turn_on:
        - parallel:
          - service: script.select_livingroom_sources
            data:
              media_type: roku
          - service: media_player.select_source
            entity_id: media_player.livingroom_roku
            data:
              source: Netflix
      turn_off:
        - parallel:
          - service: remote.send_command
            entity_id: remote.livingroom_roku
            data:
              command:
                - home
          - service: media_player.turn_off
            entity_id: media_player.livingroom_tv
          - service: media_player.turn_off
            entity_id: media_player.livingroom_receiver

    livingroom_plex:
      friendly_name: Plex
      icon_template: mdi:plex
      value_template: "{{ is_state('binary_sensor.livingroom_roku_media_active', 'on') and is_state_attr('media_player.livingroom_roku', 'source', 'Plex - Free Movies & TV') }}"
      availability_template: "{{ is_state('binary_sensor.livingroom_roku_available', 'on') }}"
      turn_on:
        - parallel:
          - service: script.select_livingroom_sources
            data:
              media_type: roku
          - service: media_player.select_source
            entity_id: media_player.livingroom_roku
            data:
              source: "Plex - Free Movies & TV"
      turn_off:
        - parallel:
          - service: remote.send_command
            entity_id: remote.livingroom_roku
            data:
              command:
                - home
          - service: media_player.turn_off
            entity_id: media_player.livingroom_tv
          - service: media_player.turn_off
            entity_id: media_player.livingroom_receiver

    livingroom_ps4:
      friendly_name: PS4
      icon_template: mdi:sony-playstation
      value_template: "{{ not is_state('media_player.livingroom_ps4', 'standby') and not is_state('media_player.livingroom_ps4', 'off') and is_state('media_player.livingroom_tv', 'on') and is_state_attr('media_player.livingroom_tv', 'source', 'HDMI_IN_4') }}"
      availability_template: "{{ not is_state('media_player.livingroom_tv', 'unavailable') and not is_state('media_player.playstation_4_livingroom', 'unavailable') and not is_state('media_player.playstation_4_livingroom', 'unknown') }}"
      turn_on:
        - parallel:
          - service: media_player.turn_on
            entity_id: media_player.livingroom_ps4
          - service: script.select_livingroom_sources
            data:
              media_type: ps4
      turn_off:
        - parallel:
          - service: media_player.turn_off
            entity_id: media_player.livingroom_tv
          - service: media_player.turn_off
            entity_id: media_player.livingroom_receiver
          - service: media_player.turn_off
            entity_id: media_player.livingroom_ps4

    livingroom_steam:
      friendly_name: Steam
      icon_template: mdi:steam
      value_template: "{{ is_state('switch.pc', 'on') and is_state('media_player.livingroom_tv', 'on') and is_state_attr('media_player.livingroom_tv', 'source', 'HDMI_IN_1') }}"
      availability_template: "{{ not is_state('switch.pc', 'unavailable') and not is_state('media_player.livingroom_tv', 'unavailable') }}"
      turn_on:
        - parallel:
          - service: switch.turn_on
            entity_id: switch.pc
          - service: script.select_livingroom_sources
            data:
              media_type: steam
      turn_off:
        - parallel:
          - service: media_player.turn_off
            entity_id: media_player.livingroom_tv
          - service: media_player.turn_off
            entity_id: media_player.livingroom_receiver
          - service: switch.turn_off
            entity_id: switch.pc

    livingroom_youtube:
      friendly_name: YouTube
      icon_template: mdi:youtube
      value_template: "{{ is_state('binary_sensor.livingroom_roku_media_active', 'on') and is_state_attr('media_player.livingroom_roku', 'source', 'YouTube') }}"
      availability_template: "{{ is_state('binary_sensor.livingroom_roku_available', 'on') }}"
      turn_on:
        - parallel:
          - service: script.select_livingroom_sources
            data:
              media_type: roku
          - service: media_player.select_source
            entity_id: media_player.livingroom_roku
            data:
              source: YouTube
      turn_off:
        - parallel:
          - service: remote.send_command
            entity_id: remote.livingroom_roku
            data:
              command:
                - home
          - service: media_player.turn_off
            entity_id: media_player.livingroom_tv
          - service: media_player.turn_off
            entity_id: media_player.livingroom_receiver