- platform: template
  switches:
    livingroom_hulu:
      icon_template: mdi:hulu
      value_template: "{{ is_state('binary_sensor.livingroom_roku_media_active', 'on') and is_state_attr('media_player.livingroom_roku', 'source', 'Hulu') }}"
      availability_template: "{{ is_state('binary_sensor.livingroom_roku_available', 'on') }}"
      turn_on:
        - service: media_player.turn_on
          entity_id: media_player.livingroom_media
        - service: media_player.select_source
          entity_id: media_player.livingroom_roku
          data:
            source: Hulu
        - service: script.select_livingroom_sources
          data:
            media_type: roku
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.livingroom_media
    livingroom_netflix:
      icon_template: mdi:netflix
      value_template: "{{ is_state('binary_sensor.livingroom_roku_media_active', 'on') and is_state_attr('media_player.livingroom_roku', 'source', 'Netflix') }}"
      availability_template: "{{ is_state('binary_sensor.livingroom_roku_available', 'on') }}"
      turn_on:
        - service: media_player.turn_on
          entity_id: media_player.livingroom_media
        - service: media_player.select_source
          entity_id: media_player.livingroom_roku
          data:
            source: Netflix
        - service: script.select_livingroom_sources
          data:
            media_type: roku
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.livingroom_media
    livingroom_ps4:
      icon_template: mdi:sony-playstation
      value_template: "{{ not is_state('media_player.playstation_4_office', 'standby') and not is_state('media_player.playstation_4_office', 'off') and is_state('media_player.livingroom_tv', 'on') and is_state_attr('media_player.livingroom_tv', 'source', 'HDMI_IN_3') }}"
      availability_template: "{{ not is_state('media_player.livingroom_tv', 'unavailable') and not is_state('media_player.playstation_4_office', 'unavailable') }}"
      turn_on:
        - service: media_player.turn_on
          entity_id:
            - media_player.playstation_4_office
            - media_player.livingroom_media
        - service: script.select_livingroom_sources
          data:
            media_type: ps4
      turn_off:
        service: media_player.turn_off
        entity_id: 
          - media_player.playstation_4_office
          - media_player.livingroom_media
    livingroom_steam:
      icon_template: mdi:steam
      value_template: "{{ is_state('switch.pc', 'on') and is_state('media_player.livingroom_tv', 'on') and is_state_attr('media_player.livingroom_tv', 'source', 'HDMI_IN_1') }}"
      availability_template: "{{ not is_state('switch.pc', 'unavailable') and not is_state('media_player.livingroom_tv', 'unavailable') }}"
      turn_on:
        - service: homeassistant.turn_on
          entity_id:
            - switch.pc
            - media_player.livingroom_media
        - service: script.select_livingroom_sources
          data:
            media_type: steam