- platform: template
  switches:
    ps4:
      friendly_name: PS4
      icon_template: mdi:playstation
      value_template: "{{ is_state('media_player.playstation_4', 'idle') or is_state('media_player.playstation_4', 'playing') }}"
      entity_id: media_player.playstation_4
      turn_on:
        - service: media_player.turn_on
          entity_id: media_player.game_room_tv
        - delay: 00:00:07
        - service: media_player.turn_on
          entity_id: media_player.playstation_4
      turn_off:
        service: media_player.turn_off
        entity_id:
          - media_player.game_room_tv
          - media_player.playstation_4