- platform: template
  switches:
    vacuum_clean_all:
      value_template: "{{ is_state('vacuum.roborock_s6_pure', 'cleaning') }}"
      icon_template: mdi:robot-vacuum
      turn_on:
        service: xiaomi_miio.vacuum_clean_segment
        entity_id: vacuum.roborock_s6_pure
        data:
          segments: >-
            {% set ns = namespace(segments=[]) %}
            {% set time = 'day' if is_state('input_boolean.sleep_mode', 'off') else 'night' %}
            {% for state in states.input_boolean %}
              {% if state.entity_id.endswith(time + '_enable') and state.state == 'on' %}
                {% set room = state.entity_id.split('_')[2] %}
                {% set room_id = states('input_number.vacuum_' + room + '_id') | int %}
                {% set ns.segments = ns.segments + [room_id] %}
              {% endif %}
            {% endfor %}
            {{ ns.segments }}
      turn_off:
        - service: vacuum.stop
          entity_id: vacuum.roborock_s6_pure
        - service: vacuum.return_to_base
          entity_id: vacuum.roborock_s6_pure
    vacuum_run:
      value_template: "{{ is_state('vacuum.roborock_s6_pure', 'cleaning') }}"
      icon_template: mdi:robot-vacuum
      turn_on:
        service: automation.trigger
        entity_id: automation.vacuum_run
      turn_off:
        - service: vacuum.stop
          entity_id: vacuum.roborock_s6_pure
        - service: vacuum.return_to_base
          entity_id: vacuum.roborock_s6_pure
    vacuum_gameroom_night_enable:
      value_template: "{{ states('input_boolean.vacuum_gameroom_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if as_local(strptime(states('input_datetime.vacuum_gameroom_last_cleaned'), '%Y-%m-%d %H:%M:%S')) > now() - timedelta(days=1) else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        entity_id: input_boolean.vacuum_gameroom_night_enable
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.vacuum_gameroom_night_enable
    vacuum_hallway_night_enable:
      value_template: "{{ states('input_boolean.vacuum_hallway_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if as_local(strptime(states('input_datetime.vacuum_hallway_last_cleaned'), '%Y-%m-%d %H:%M:%S')) > now() - timedelta(days=1) else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        entity_id: input_boolean.vacuum_hallway_night_enable
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.vacuum_hallway_night_enable
    vacuum_bedroom_night_enable:
      value_template: "{{ states('input_boolean.vacuum_bedroom_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if as_local(strptime(states('input_datetime.vacuum_bedroom_last_cleaned'), '%Y-%m-%d %H:%M:%S')) > now() - timedelta(days=1) else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        entity_id: input_boolean.vacuum_bedroom_night_enable
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.vacuum_bedroom_night_enable
    vacuum_livingroom_night_enable:
      value_template: "{{ states('input_boolean.vacuum_livingroom_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if as_local(strptime(states('input_datetime.vacuum_livingroom_last_cleaned'), '%Y-%m-%d %H:%M:%S')) > now() - timedelta(days=1) else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        entity_id: input_boolean.vacuum_livingroom_night_enable
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.vacuum_livingroom_night_enable
    vacuum_kitchen_night_enable:
      value_template: "{{ states('input_boolean.vacuum_kitchen_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if as_local(strptime(states('input_datetime.vacuum_kitchen_last_cleaned'), '%Y-%m-%d %H:%M:%S')) > now() - timedelta(days=1) else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        entity_id: input_boolean.vacuum_kitchen_night_enable
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.vacuum_kitchen_night_enable
    vacuum_diningroom_night_enable:
      value_template: "{{ states('input_boolean.vacuum_diningroom_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if as_local(strptime(states('input_datetime.vacuum_diningroom_last_cleaned'), '%Y-%m-%d %H:%M:%S')) > now() - timedelta(days=1) else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        entity_id: input_boolean.vacuum_diningroom_night_enable
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.vacuum_diningroom_night_enable
    vacuum_office_night_enable:
      value_template: "{{ states('input_boolean.vacuum_office_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if as_local(strptime(states('input_datetime.vacuum_office_last_cleaned'), '%Y-%m-%d %H:%M:%S')) > now() - timedelta(days=1) else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        entity_id: input_boolean.vacuum_office_night_enable
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.vacuum_office_night_enable
    vacuum_upstairsbathroom_night_enable:
      value_template: "{{ states('input_boolean.vacuum_upstairsbathroom_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if as_local(strptime(states('input_datetime.vacuum_upstairsbathroom_last_cleaned'), '%Y-%m-%d %H:%M:%S')) > now() - timedelta(days=1) else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        entity_id: input_boolean.vacuum_upstairsbathroom_night_enable
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.vacuum_upstairsbathroom_night_enable
