- platform: template
  switches:
    vacuum_gameroom_16_night_enable:
      value_template: "{{ states('input_boolean.vacuum_gameroom_16_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_gameroom_16_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_gameroom_16_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_gameroom_16_night_enable
    vacuum_hallway_17_night_enable:
      value_template: "{{ states('input_boolean.vacuum_hallway_17_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_hallway_17_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_hallway_17_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_hallway_17_night_enable
    vacuum_bedroom_18_night_enable:
      value_template: "{{ states('input_boolean.vacuum_bedroom_18_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_bedroom_18_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_bedroom_18_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_bedroom_18_night_enable
    vacuum_livingroom_19_night_enable:
      value_template: "{{ states('input_boolean.vacuum_livingroom_19_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_livingroom_19_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_livingroom_19_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_livingroom_19_night_enable
    vacuum_kitchen_20_night_enable:
      value_template: "{{ states('input_boolean.vacuum_kitchen_20_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_kitchen_20_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_kitchen_20_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_kitchen_20_night_enable
    vacuum_diningroom_21_night_enable:
      value_template: "{{ states('input_boolean.vacuum_diningroom_21_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_diningroom_21_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_diningroom_21_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_diningroom_21_night_enable
    vacuum_office_22_night_enable:
      value_template: "{{ states('input_boolean.vacuum_office_22_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_office_22_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_office_22_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_office_22_night_enable
    vacuum_upstairsbathroom_23_night_enable:
      value_template: "{{ states('input_boolean.vacuum_upstairsbathroom_23_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_upstairsbathroom_23_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_upstairsbathroom_23_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_upstairsbathroom_23_night_enable