- platform: template
  switches:
    vacuum_clean_all:
      value_template: "{{ is_state('vacuum.roborock_s6_pure', 'cleaning') }}"
      icon_template: mdi:robot-vacuum
      turn_on:
        service: xiaomi_miio.vacuum_clean_segment
        target:
          entity_id: vacuum.roborock_s6_pure
        data:
          segments: >-
            {% set ns = namespace(segments=[]) %}
            {% set time = 'day' if is_state('input_boolean.sleep_mode', 'off') else 'night' %}
            {% for state in states.input_boolean %}
              {% if state.entity_id.endswith(time + '_enable') and state.state == 'on' %}
                {% set room = state.entity_id.split('_')[2] %}
                {% set room_id = states('input_number.vacuum_' + room + '_id') | int %}
                {% set ns.segments = ns.segments + [room_id] %}
              {% endif %}
            {% endfor %}
            {{ ns.segments }}
      turn_off:
        - service: vacuum.stop
          target:
            entity_id: vacuum.roborock_s6_pure
        - service: vacuum.return_to_base
          target:
            entity_id: vacuum.roborock_s6_pure
    vacuum_run:
      value_template: "{{ is_state('vacuum.roborock_s6_pure', 'cleaning') }}"
      icon_template: mdi:robot-vacuum
      turn_on:
        service: automation.trigger
        target:
          entity_id: automation.vacuum_run
      turn_off:
        - service: vacuum.stop
          target:
            entity_id: vacuum.roborock_s6_pure
        - service: vacuum.return_to_base
          target:
            entity_id: vacuum.roborock_s6_pure
    vacuum_gameroom_night_enable:
      value_template: "{{ states('input_boolean.vacuum_gameroom_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_gameroom_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_gameroom_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_gameroom_night_enable
    vacuum_hallway_night_enable:
      value_template: "{{ states('input_boolean.vacuum_hallway_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_hallway_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_hallway_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_hallway_night_enable
    vacuum_bedroom_night_enable:
      value_template: "{{ states('input_boolean.vacuum_bedroom_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_bedroom_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_bedroom_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_bedroom_night_enable
    vacuum_livingroom_night_enable:
      value_template: "{{ states('input_boolean.vacuum_livingroom_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_livingroom_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_livingroom_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_livingroom_night_enable
    vacuum_kitchen_night_enable:
      value_template: "{{ states('input_boolean.vacuum_kitchen_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_kitchen_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_kitchen_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_kitchen_night_enable
    vacuum_diningroom_night_enable:
      value_template: "{{ states('input_boolean.vacuum_diningroom_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_diningroom_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_diningroom_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_diningroom_night_enable
    vacuum_office_night_enable:
      value_template: "{{ states('input_boolean.vacuum_office_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_office_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_office_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_office_night_enable
    vacuum_upstairsbathroom_night_enable:
      value_template: "{{ states('input_boolean.vacuum_upstairsbathroom_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_upstairsbathroom_21_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_upstairsbathroom_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_upstairsbathroom_night_enable
