- platform: template
  switches:
    vacuum_run:
      value_template: "{{ is_state('vacuum.roborock_s6_pure', 'cleaning') }}"
      icon_template: mdi:robot-vacuum
      turn_on:
        service: automation.trigger
        target:
          entity_id: automation.vacuum_run
      turn_off:
        - service: vacuum.stop
          target:
            entity_id: vacuum.roborock_s6_pure
        - service: vacuum.return_to_base
          target:
            entity_id: vacuum.roborock_s6_pure
    vacuum_gameroom_23_night_enable:
      value_template: "{{ states('input_boolean.vacuum_gameroom_23_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_gameroom_23_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_gameroom_23_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_gameroom_23_night_enable
    vacuum_hallway_20_night_enable:
      value_template: "{{ states('input_boolean.vacuum_hallway_20_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_hallway_20_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_hallway_20_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_hallway_20_night_enable
    vacuum_bedroom_22_night_enable:
      value_template: "{{ states('input_boolean.vacuum_bedroom_22_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_bedroom_22_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_bedroom_22_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_bedroom_22_night_enable
    vacuum_livingroom_16_night_enable:
      value_template: "{{ states('input_boolean.vacuum_livingroom_16_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_livingroom_16_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_livingroom_16_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_livingroom_16_night_enable
    vacuum_kitchen_18_night_enable:
      value_template: "{{ states('input_boolean.vacuum_kitchen_18_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_kitchen_18_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_kitchen_18_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_kitchen_18_night_enable
    vacuum_diningroom_17_night_enable:
      value_template: "{{ states('input_boolean.vacuum_diningroom_17_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_diningroom_17_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_diningroom_17_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_diningroom_17_night_enable
    vacuum_office_19_night_enable:
      value_template: "{{ states('input_boolean.vacuum_office_19_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_office_19_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_office_19_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_office_19_night_enable
    vacuum_upstairsbathroom_21_night_enable:
      value_template: "{{ states('input_boolean.vacuum_upstairsbathroom_21_night_enable') }}"
      icon_template: "{{ 'mdi:checkbox-marked-circle' if is_state('input_boolean.vacuum_upstairsbathroom_21_cleaned_today', 'on') else 'mdi:checkbox-blank-circle'}}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_upstairsbathroom_21_night_enable
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_upstairsbathroom_21_night_enable