type: custom:auto-entities
card:
  type: entities
  title: Recent Automations
  show_header_toggle: false
filter:
  include:
    - domain: automation
      not:
        attributes:
          current: 0
      options:
        type: custom:template-entity-row
        active: true
        secondary: '{{ relative_time(state_attr(config.entity, ''last_triggered'')) }} ago'
        state: '{{ state_attr(config.entity, ''current'') }} Running'
        hold_action: |
          {
            "action": "navigate",
            "navigation_path": "/config/automation/trace/{{ config.entity.split('.')[1] }}"
          }
    - domain: automation
      last_triggered: < 5
      options:
        type: custom:template-entity-row
        active: '{{ (state_attr(config.entity, ''current'') | int) > 0 }}'
        secondary: |
          {%- if state_attr(config.entity, 'last_triggered') -%}
            {{ relative_time(state_attr(config.entity, 'last_triggered')) }} ago
          {%- else -%}
            Never triggered
          {%- endif -%}
        state: Not Running
        hold_action: |
          {
            "action": "navigate",
            "navigation_path": "/config/automation/trace/{{ config.entity.split('.')[1] }}"
          }
show_empty: false
unique: entity
sort:
  method: last_triggered
  reverse: true