title: Vacuum
type: custom:stack-in-card
cards:
  - type: entities
    canary_style:
      margin: '0px 0px -32px'
    entities:
      - name: Next Room
        type: custom:multiple-entity-row
        entity: switch.vacuum_run
        toggle: true
        state_color: true
        entities:
          - entity: sensor.vacuum_next_room_to_clean
            attribute: display_name
            name: false
          - entity: sensor.vacuum_next_room_to_clean
            attribute: label
            name: false
      - entity: input_number.vacuum_rooms_cleaned_since_being_emptied
        name: Rooms Cleaned Since Being Emptied
      - entity: input_number.vacuum_max_rooms_cleaned_before_emptying
        type: custom:numberbox-card
        name: Max Rooms Cleaned Before Emptying
      - entity: input_number.run_vacuum_after_away_min
        type: custom:numberbox-card
        name: Run Vacuum After Away For (Min)
      - entity: input_number.run_vacuum_after_asleep_min
        type: custom:numberbox-card
        name: Run Vacuum After Asleep For (Min)
  - type: horizontal-stack
    cards:
      - type: entities
        entities:
          - entity: input_select.vacuum_fan_speed_day
            name: Fan Speed (Day)
      - type: entities
        entities:
          - entity: input_select.vacuum_fan_speed_night
            name: Fan Speed (Night)
  - type: entities
    canary_style:
      margin: '-30px 0px 0px'
    entities:
      - entity: input_datetime.vacuum_night_cleaning_end_time
        name: Night Cleaning End Time
      - entity: input_datetime.vacuum_room_cleaned_today_reset_time
        name: Cleaned Today Reset Time
      - name: All Rooms
        type: custom:multiple-entity-row
        entity: group.vacuum_enable_all_rooms_night
        state_header: Night
        toggle: true
        secondary_info:
          entity: sensor.vacuum_next_room_to_clean
          attribute: display_name
          name: false
        entities:
          - entity: switch.vacuum_run
            name: Start/Stop
            toggle: true
          - entity: group.vacuum_enable_all_rooms_day
            name: Day
            toggle: true
      - type: divider
      - type: custom:multiple-entity-row
        name: Game Room
        entity: switch.vacuum_gameroom_16_night_enable
        toggle: true
        secondary_info:
          entity: sensor.vacuum_gameroom_16_last_cleaned
          name: false
        entities:
          - entity: input_boolean.vacuum_gameroom_16_day_enable
            name: false
            toggle: true
      - type: custom:multiple-entity-row
        name: Hallway
        entity: switch.vacuum_hallway_17_night_enable
        toggle: true
        secondary_info:
          entity: sensor.vacuum_hallway_17_last_cleaned
          name: false
        entities:
          - entity: input_boolean.vacuum_hallway_17_day_enable
            name: false
            toggle: true
      - type: custom:multiple-entity-row
        name: Bedroom
        entity: switch.vacuum_bedroom_18_night_enable
        toggle: true
        secondary_info:
          entity: sensor.vacuum_bedroom_18_last_cleaned
          name: false
        entities:
          - entity: input_boolean.vacuum_bedroom_18_day_enable
            name: false
            toggle: true
      - type: custom:multiple-entity-row
        name: Living Room
        entity: switch.vacuum_livingroom_19_night_enable
        toggle: true
        secondary_info:
          entity: sensor.vacuum_livingroom_19_last_cleaned
          name: false
        entities:
          - entity: input_boolean.vacuum_livingroom_19_day_enable
            name: false
            toggle: true
      - type: custom:multiple-entity-row
        name: Kitchen
        entity: switch.vacuum_kitchen_20_night_enable
        toggle: true
        secondary_info:
          entity: sensor.vacuum_kitchen_20_last_cleaned
          name: false
        entities:
          - entity: input_boolean.vacuum_kitchen_20_day_enable
            name: false
            toggle: true
      - type: custom:multiple-entity-row
        name: Dining Room
        entity: switch.vacuum_diningroom_21_night_enable
        toggle: true
        secondary_info:
          entity: sensor.vacuum_diningroom_21_last_cleaned
          name: false
        entities:
          - entity: input_boolean.vacuum_diningroom_21_day_enable
            name: false
            toggle: true
      - type: custom:multiple-entity-row
        name: Office
        entity: switch.vacuum_office_22_night_enable
        toggle: true
        secondary_info:
          entity: sensor.vacuum_office_22_last_cleaned
          name: false
        entities:
          - entity: input_boolean.vacuum_office_22_day_enable
            name: false
            toggle: true
      - type: custom:multiple-entity-row
        name: Upstairs Bathroom
        entity: switch.vacuum_upstairsbathroom_23_night_enable
        toggle: true
        secondary_info:
          entity: sensor.vacuum_upstairsbathroom_23_last_cleaned
          name: false
        entities:
          - entity: input_boolean.vacuum_upstairsbathroom_23_day_enable
            name: false
            toggle: true