automation:
  - alias: Living Room - Fireplace Nightlight
    id: living_room_fireplace_nightlight
    mode: queued
    triggers:
      - trigger: state
        entity_id: binary_sensor.living_room_presence_all_zones
        to:
          - 'off'
          - 'on'
      - trigger: state
        entity_id: sun.sun
        to: below_horizon
    conditions:
      - or:
        - condition: state
          entity_id: sun.sun
          state: below_horizon
        - condition: state
          entity_id: binary_sensor.living_room_presence_all_zones
          state: 'off'
    actions:
      - action: light.turn_{{ states('binary_sensor.living_room_presence_all_zones') }}
        entity_id: light.fireplace_night_light

  - alias: Living Room - Turn On Fireplace
    id: living_room_turn_on_fireplace
    mode: queued
    triggers:
      - trigger: state
        entity_id: binary_sensor.living_room_presence_couch_zone
        to: 'on'
        for:
          seconds: "{{ states('input_number.living_room_fireplace_on_delay') }}"
      - trigger: numeric_state
        entity_id: sensor.living_room_temperature_sensor_air_temperature
        below: input_number.living_room_fireplace_temperature_on_threshold
    conditions:
      - condition: state
        entity_id: light.fireplace_flame
        state: 'off'
      - condition: state
        entity_id: person.mike
        state: home
      - condition: state
        entity_id: binary_sensor.living_room_presence_couch_zone
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.living_room_temperature_sensor_air_temperature
        below: input_number.living_room_fireplace_temperature_on_threshold
      - condition: state
        entity_id: sensor.last_hvac_state
        state: heating
      - condition: numeric_state
        entity_id: sensor.front_porch_sensor_air_temperature
        below: input_number.living_room_fireplace_outside_temperature_on_threshold
    actions:
      - action: light.turn_on
        entity_id: light.fireplace_flame
        data:
          brightness_pct: 100

  - alias: Living Room - Turn Off Fireplace
    id: living_room_turn_off_fireplace
    mode: queued
    triggers:
      - trigger: state
        entity_id: binary_sensor.living_room_presence_couch_zone
        to: 'off'
        for:
          seconds: "{{ states('input_number.living_room_fireplace_off_delay') }}"
      - trigger: numeric_state
        entity_id: sensor.living_room_temperature_sensor_air_temperature
        above: input_number.living_room_fireplace_temperature_off_threshold
    conditions:
      - condition: state
        entity_id: light.fireplace_flame
        state: 'on'
    actions:
      - action: light.turn_off
        entity_id: light.fireplace_flame

  - alias: Living Room - Toggle Fireplace Blower
    id: living_room_turn_on_fireplace_blower
    mode: queued
    triggers:
      - trigger: state
        entity_id: light.fireplace_flame
        to:
          - 'on'
          - 'off'
    actions:
      - if: "{{ trigger.to_state.state == 'on' }}"
        then:
          - action: fan.turn_on
            entity_id: fan.fireplace_blower
            data:
              percentage: 50
        else:
          - action: fan.turn_off
            entity_id: fan.fireplace_blower

input_number:
  living_room_fireplace_off_delay: &delay
    min: 0
    max: 5000
    mode: box
    unit_of_measurement: s
  living_room_fireplace_on_delay: *delay
  living_room_fireplace_temperature_on_threshold: &temp
    min: 30
    max: 90
    mode: box
    unit_of_measurement: °F
  living_room_fireplace_temperature_off_threshold: *temp
  living_room_fireplace_outside_temperature_on_threshold: *temp