automation:
  - alias: Living Room - Fireplace Nightlight
    id: living_room_fireplace_nightlight
    mode: queued
    variables:
      do_this: >
        {% if is_state('binary_sensor.living_room_presence_all_zones', 'on') and is_state('sun.sun', 'below_horizon') %}
          on
        {% else %}
          off
        {% endif %}
    triggers:
      - trigger: state
        entity_id: binary_sensor.living_room_presence_all_zones
        to: ['off', 'on']
      - trigger: state
        entity_id: sun.sun
        to: ['above_horizon', 'below_horizon']
    actions:
      - action: light.turn_{{ do_this }}
        entity_id: light.fireplace_night_light

  - alias: Living Room - Turn On Fireplace
    id: living_room_turn_on_fireplace
    mode: queued
    variables:
      room_temp: "{{ states('sensor.living_room_temperature_sensor_air_temperature') | float }}"
      outside_temp: "{{ states('sensor.front_porch_sensor_air_temperature') | float }}"
      on_threshold_temp: "{{ states('input_number.living_room_fireplace_on_temperature_threshold') | float }}"
      on_outside_threshold_temp: "{{ states('input_number.living_room_fireplace_on_outside_temperature_threshold') | float }}"
    triggers:
      - trigger: state
        entity_id: binary_sensor.living_room_presence_couch_zone
        to: 'on'
        for:
          seconds: "{{ states('input_number.living_room_fireplace_on_delay') }}"
      - trigger: state
        entity_id: sensor.living_room_temperature_sensor_air_temperature
    conditions: >
      {{     is_state('light.fireplace_flame', 'off')
          and is_state('person.mike', 'home')
          and is_state('binary_sensor.living_room_presence_couch_zone', 'on')
          and is_state('sensor.last_hvac_state', 'heating')
          and room_temp <= on_threshold_temp
          and outside_temp <= on_outside_threshold_temp }}
    actions:
      - action: light.turn_on
        entity_id: light.fireplace_flame
        data:
          brightness_pct: 100

  - alias: Living Room - Turn Off Fireplace
    id: living_room_turn_off_fireplace
    mode: queued
    triggers:
      - trigger: state
        entity_id: binary_sensor.living_room_presence_couch_zone
        to: 'off'
        for:
          seconds: "{{ states('input_number.living_room_fireplace_off_delay') }}"
      - trigger: numeric_state
        entity_id: sensor.living_room_temperature_sensor_air_temperature
        above: input_number.living_room_fireplace_off_temperature_threshold
    actions:
      - action: light.turn_off
        entity_id: light.fireplace_flame

  - alias: Living Room - Toggle Fireplace Blower
    id: living_room_turn_on_fireplace_blower
    mode: queued
    triggers:
      - trigger: state
        entity_id: light.fireplace_flame
        to: ['off', 'on']
    actions:
      - variables:
          current_state: "{{ states('light.fireplace_flame') }}"
      - action: fan.turn_{{ current_state }}
        data: >
          {% if current_state == 'on' %}
            {"percentage": {{ states('input_number.livingroom_fireplace_blower_default_speed') }} }
          {% else %}
            {}
          {% endif %}

input_number:
  livingroom_fireplace_blower_default_speed:
    min: 0
    max: 100
    mode: box
    unit_of_measurement: "%"
  living_room_fireplace_off_delay: &delay
    min: 0
    max: 5000
    mode: box
    unit_of_measurement: s
  living_room_fireplace_on_delay: *delay
  living_room_fireplace_off_temperature_threshold: &temp
    min: 30
    max: 90
    mode: box
    unit_of_measurement: °F
  living_room_fireplace_on_outside_temperature_threshold: *temp
  living_room_fireplace_on_temperature_threshold: *temp