blueprint:
  name: Occupancy - Off
  description: Turn off occupancy input boolean after motion timeout
  domain: automation
  input:
    motion_group:
variables:
  motion_group: !input motion_group
  room: "{{ motion_group.split('.')[1].split('_')[0] }}"
trigger:
    platform: state
    entity_id: !input motion_group
    to: 'off'
    for: 
      minutes: "{{ states('input_number.occupancy_' + room + '_motion_timeout_minutes') | int > 0 }}"
      seconds: "{{ states('input_number.occupancy_' + room + '_motion_timeout_seconds') | int > 0 }}"
condition:
  - condition: or
    conditions:
      - "{{ states('input_number.occupancy_' + room + '_motion_timeout_minutes') | int > 0 }}"
      - "{{ states('input_number.occupancy_' + room + '_motion_timeout_seconds') | int > 0 }}"
  - condition: state
    entity_id: input_boolean.single_occupancy_mode
    state: 'off'
action:
  service: input_boolean.turn_off
  target:
    entity_id: "input_boolean.{{ room }}_occupancy"