blueprint:
  name: Occupancy - On
  description: Turn on occupancy input boolean when motion is detected in a room
  domain: automation
  input:
    room:
variables:
  room_name: !input room
trigger:
  platform: state
  entity_id: "group.{{ room_name }}_motion"
  to: 'on'
action:
  service: input_boolean.turn_on
  entity_id: "input_boolean.{{ room_name }}_occupancy"