blueprint:
  name: Occupancy - On
  description: Turn on occupancy input boolean when motion is detected in a room
  domain: automation
  input:
    motion_group:
variables:
  motion_group: !input motion_group
trigger:
  platform: state
  entity_id: !input motion_group
  to: 'on'
action:
  service: input_boolean.turn_on
  target:
    entity_id: "input_boolean.{{ motion_group.split('.')[1].split('_')[0] }}_occupancy"