- alias: 'Occupancy: Game Room - On'
  id: occupancy_gameroom_on
  trigger:
    platform: state
    entity_id: group.gameroom_motion
    to: 'on'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.gameroom_occupancy

- alias: 'Occupancy: Game Room - Off'
  id: occupancy_gameroom_off
  trigger:
    platform: state
    entity_id: group.gameroom_motion
    to: 'off'
    for: 
      minutes: "{{ states('input_number.occupancy_gameroom_motion_timeout_minutes') | int }}"
      seconds: "{{ states('input_number.occupancy_gameroom_motion_timeout_seconds') | int }}"
  condition:
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: input_number.occupancy_gameroom_motion_timeout_seconds
          above: 0
        - condition: numeric_state
          entity_id: input_number.occupancy_gameroom_motion_timeout_minutes
          above: 0
    - condition: state
      entity_id: input_boolean.single_occupancy_mode
      state: 'off'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.gameroom_occupancy

- alias: 'Occupancy: Game Room - Off Single Occupancy'
  id: occupancy_gameroom_off_single_occupancy
  trigger:
    platform: state
    entity_id: sensor.last_occupied_room
    for: 
      seconds: "{{ states('input_number.occupancy_gameroom_single_occupancy_timeout_seconds') }}"
  condition:
    - condition: state
      entity_id: input_boolean.single_occupancy_mode
      state: 'on'
    - condition: numeric_state
      entity_id: input_number.occupancy_gameroom_single_occupancy_timeout_seconds
      above: 0
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.gameroom_occupancy
