- alias: 'Occupancy: Office - On'
  id: occupancy_office_on
  use_blueprint:
    path: occupancy_on.yaml
    input:
      motion_group: group.office_motion

- alias: 'Occupancy: Office - Off'
  id: occupancy_office_off
  use_blueprint:
    path: occupancy_off.yaml
    input:
      motion_group: group.office_motion

- alias: 'Occupancy: Office - Off Single Occupancy'
  id: occupancy_office_off_single_occupancy
  use_blueprint:
    path: occupancy_off_single_occupancy.yaml
    input:
      room: office
