- alias: 'Occupancy: Upstairs Bathroom - On'
  id: occupancy_upstairsbathroom_on
  max_exceeded: silent
  trigger:
    platform: state
    entity_id: group.upstairsbathroom_motion
    to: 'on'
  action:
    service: input_boolean.turn_on
    target:
      entity_id: "input_boolean.upstairsbathroom_occupancy"

- alias: 'Occupancy: Upstairs Bathroom - Off'
  id: occupancy_upstairsbathroom_off
  max_exceeded: silent
  trigger:
    platform: state
    entity_id: group.upstairsbathroom_motion
    to: 'off'
    for:
      minutes: "{{ states('input_number.occupancy_upstairsbathroom_motion_timeout_minutes') }}"
      seconds: "{{ states('input_number.occupancy_upstairsbathroom_motion_timeout_seconds') }}"
  condition:
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: input_number.occupancy_upstairsbathroom_motion_timeout_minutes
          above: 0
        - condition: numeric_state
          entity_id: input_number.occupancy_upstairsbathroom_motion_timeout_seconds
          above: 0
    - condition: state
      entity_id: binary_sensor.upstairsbathroom_door
      state: 'on'
    - condition: state
      entity_id: input_boolean.single_occupancy_mode
      state: 'off'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.upstairsbathroom_occupancy

- alias: 'Occupancy: Upstairs Bathroom - Off Quickly After Door Opens'
  id: occupancy_upstairsbathroom_off_quickly_after_door_opens
  max_exceeded: silent
  trigger:
    platform: state
    entity_id: binary_sensor.upstairsbathroom_door
    to: 'on'
  condition:
    condition: numeric_state
    entity_id: input_number.occupancy_upstairsbathroom_motion_quick_timeout_seconds
    above: 0
  action:
    - wait_template: "{{ is_state('group.upstairsbathroom_motion', 'off') }}"
      timeout: 
        seconds: "{{ states('input_number.occupancy_upstairsbathroom_motion_quick_timeout_seconds') }}"
      continue_on_timeout: false
    - service: input_boolean.turn_off
      entity_id: input_boolean.upstairsbathroom_occupancy

- alias: 'Occupancy: Upstairs Bathroom - Off Single Occupancy'
  id: occupancy_upstairsbathroom_off_single_occupancy
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: sensor.last_occupied_room
      for: 
        seconds: "{{ states('input_number.occupancy_upstairsbathroom_single_occupancy_timeout_seconds') }}"
    - platform: state
      entity_id: group.upstairsbathroom_motion
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.single_occupancy_mode
      state: 'on'
    - condition: template
      value_template: "{{ states('input_number.occupancy_upstairsbathroom_single_occupancy_timeout_seconds') | int > 0 }}"
    - condition: template
      value_template: "{{ states('sensor.last_occupied_room') != 'upstairsbathroom' }}"
    - condition: state
      entity_id: group.upstairsbathroom_motion
      state: 'off'
  action:
    service: input_boolean.turn_off
    target:
      entity_id: input_boolean.upstairsbathroom_occupancy