- platform: template
  sensors:
    alexa_last_called_device:
      value_template: "{{ expand(states.group.echos) | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}"
    alexa_last_called_room:
      value_template: >-
        {% if '.' in states('sensor.alexa_last_called_device') %}
          {{ states('sensor.alexa_last_called_device').split('.')[1].split('_')[0] }}
        {% else %}
          unknown
        {% endif %}
      availability_template: "{{ 'media_player' in states('sensor.alexa_last_called_device') }}"