- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - temperature
    - precip_type
    - precip_intensity
    - precip_probability
    - apparent_temperature
    - wind_speed
    - humidity
    - precip_intensity_max
    - minutely_summary
    - hourly_summary
    - daily_summary
  units: us