- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
- platform: template
  sensors:
    time_hour:
      value_template: "{{ states.sensor.time.state.split(':')[0] }}"
      entity_id: sensor.time
    time_minute:
      value_template: "{{ states.sensor.time.state.split(':')[1] }}"
      entity_id: sensor.time
