- platform: template
  sensors:
    required_run_mileage_for_today:
      value_template: >-
        {% if state_attr('calendar.next_run', 'start_time') and state_attr('calendar.next_run', 'start_time').split()[0] == now().strftime("%Y-%m-%d") %}
          {{ state_attr('calendar.next_run', 'message').split()[0] }}
        {% else %}
          0
        {% endif %}
    required_bike_mileage_for_today:
      value_template: >-
        {% if state_attr('calendar.next_bike', 'start_time') and state_attr('calendar.next_bike', 'start_time').split()[0] == now().strftime("%Y-%m-%d") %}
          {{ state_attr('calendar.next_bike', 'message').split()[0] }}
        {% else %}
          0
        {% endif %}
    required_walk_mileage_for_today:
      value_template: >-
        {% if state_attr('calendar.next_walk', 'start_time') and state_attr('calendar.next_walk', 'start_time').split()[0] == now().strftime("%Y-%m-%d") %}
          {{ state_attr('calendar.next_walk', 'message').split()[0] }}
        {% else %}
          0
        {% endif %}

- platform: sql
  db_url: !secret fitnessdb_url
  queries:
    - name: run_mileage_today
      query: "SELECT IFNULL(SUM(distance_miles), 0) as mileage FROM garmin_activities WHERE DATE(startTimeLocal) = CURDATE() AND activityType = 'running';"
      column: mileage
      value_template: "{{ value | round(2) if value != '0' else value }}"
      unit_of_measurement: miles
    - name: bike_mileage_today
      query: "SELECT IFNULL(SUM(distance_miles), 0) as mileage FROM garmin_activities WHERE DATE(startTimeLocal) = CURDATE() AND activityType in ('cycling', 'indoor_cycling');"
      column: mileage
      value_template: "{{ value | round(2) if value != '0' else value }}"
      unit_of_measurement: miles
    - name: walk_mileage_today
      query: "SELECT IFNULL(SUM(distance_miles), 0) as mileage FROM garmin_activities WHERE DATE(startTimeLocal) = CURDATE() AND activityType = 'walking';"
      column: mileage
      value_template: "{{ value | round(2) if value != '0' else value }}"
      unit_of_measurement: miles
    - name: lifting_sessions_today
      query: "SELECT COUNT(*) as cnt FROM garmin_activities WHERE activityType = 'strength_training' AND DATE(startTimeLocal) = CURDATE() LIMIT 1;"
      column: cnt
    - name: steps_today
      query: "SELECT totalSteps FROM garmin_daily_stats WHERE calendarDate = CURDATE();"
      column: totalSteps
      value_template: "{{ value | round }}"
      unit_of_measurement: steps
    - name: step_goal_today
      query: "SELECT dailyStepGoal FROM garmin_daily_stats WHERE calendarDate = CURDATE();"
      column: dailyStepGoal
      value_template: "{{ value | round }}"
      unit_of_measurement: steps