- platform: template
  sensors:
    required_run_mileage_for_today:
      value_template: >-
        {% if state_attr('calendar.next_run', 'start_time').split()[0] == now().strftime("%Y-%m-%d") %}
          {{ state_attr('calendar.next_run', 'message').split()[0] }}
        {% else %}
          0
        {% endif %}
    required_bike_mileage_for_today:
      value_template: >-
        {% if state_attr('calendar.next_bike', 'start_time').split()[0] == now().strftime("%Y-%m-%d") %}
          {{ state_attr('calendar.next_bike', 'message').split()[0] }}
        {% else %}
          0
        {% endif %}
    required_walk_mileage_for_today:
      value_template: >-
        {% if state_attr('calendar.next_walk', 'start_time').split()[0] == now().strftime("%Y-%m-%d") %}
          {{ state_attr('calendar.next_walk', 'message').split()[0] }}
        {% else %}
          0
        {% endif %}

- platform: sql
  db_url: !secret fitnessdb_url
  queries:
    - name: run_mileage_today
      query: "SELECT IFNULL(SUM(distance_miles), 0) as mileage FROM garmin_activities WHERE DATE(startTimeLocal) = CURDATE() AND activityType = 'running';"
      column: mileage
      unit_of_measurement: miles
    - name: bike_mileage_today
      query: "SELECT IFNULL(SUM(distance_miles), 0) as mileage FROM garmin_activities WHERE DATE(startTimeLocal) = CURDATE() AND activityType in ('cycling', 'indoor_cycling');"
      column: mileage
      unit_of_measurement: miles
    - name: walk_mileage_today
      query: "SELECT IFNULL(SUM(distance_miles), 0) as mileage FROM garmin_activities WHERE DATE(startTimeLocal) = CURDATE() AND activityType = 'walking';"
      column: mileage
      unit_of_measurement: miles