- platform: rest
  name: tablet
  json_attributes:
    - batteryLevel
    - kioskMode
    - screenBrightness
    - motionDetectorState
    - maintenanceMode
    - appFreeMemory
    - appUsedMemory
    - totalFreeMemory
    - totalUsedMemory
    - hostname4
    - ip4
    - mac
    - locationLatitude
    - locationLongitude
    - locationAltitude
    - startUrl
    - currentPage
  resource: !secret tablet_rest_url
  value_template: '{{ value_json.isScreenOn }}'

- platform: template
  sensors:
    tablet_battery:
      value_template: "{{ state_attr('sensor.tablet', 'batteryLevel') }}"