- platform: github
  access_token: !secret github_access_token
  repositories:
    - path: 'grafana/grafana'
    - path: 'jacobalberty/unifi-docker'
    - path: 'zwave-js/zwavejs2mqtt'

- platform: template
  sensors:
    unifi_latest_version:
      value_template: "{{ state_attr('sensor.unifi_docker', 'latest_release_tag') }}"
    zwavejs2mqtt_latest_version:
      value_template: "{{ state_attr('sensor.zwavejs2mqtt', 'latest_release_tag')[1:] }}"