- platform: history_stats
  name: hvac_cool_on_today
  entity_id: binary_sensor.hvac_cool_on
  state: "on"
  type: time
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: hvac_heat_on_today
  entity_id: binary_sensor.hvac_heat_on
  state: "on"
  type: time
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: hvac_fan_only_on_today
  entity_id: binary_sensor.hvac_only_fan_on
  state: "on"
  type: time
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: mqtt
  name: outside_temp
  unit_of_measurement: °F
  device_class: temperature
  state_topic: rtl_433/+/devices/WG-PB12V1/6/temperature_C
  value_template: "{{ (value | float(0) * 9 / 5) + 32 | round(1) }}"