- platform: template
  sensors:
    jenkins_base_url:
      value_template: !secret jenkins_base_url

- platform: rest
  resource_template: "{{ states('sensor.jenkins_base_url') }}/job/Garmin-Connect-Update/lastBuild/api/json"
  name: jenkins_garmin_connect_update_last_build
  authentication: basic
  username: !secret jenkins_user
  password: !secret jenkins_pass
  json_attributes:
    - building
    - result
    - timestamp
