- platform: rest
  name: tablet
  json_attributes:
    - batteryLevel
    - kioskMode
    - screenBrightness
    - motionDetectorState
    - maintenanceMode
    - appFreeMemory
    - appUsedMemory
    - totalFreeMemory
    - totalUsedMemory
    - hostname4
    - ip4
    - mac
    - locationLatitude
    - locationLongitude
    - locationAltitude
    - startUrl
    - currentPage
  resource: ${LIVINGROOM_TABLET_STATS_URL}
  value_template: "{{ value_json.isScreenOn if 'isScreenOn' in value_json else 'off' }}"