- platform: rest
  name: ps5
  json_attributes:
    - code
  resource: !secret ps5_monitor_rest_url
  value_template: >
    {% if value_json.code == 200 %}
      On
    {% elif value_json.code == 620 %}
      Standby
    {% else %}
      Off
    {% endif %}