- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: last_boot
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: memory_free
    - type: memory_use_percent
    - type: memory_use
    - type: processor_use
    - type: swap_use_percent
    - type: swap_use
    - type: swap_free
