- platform: template
  sensors:
    truck_fuel_level:
      entity_id: device_tracker.truck
      value_template: "{{ state_attr('device_tracker.truck', '12F') }}"
    truck_rpm:
      entity_id: device_tracker.truck
      value_template: "{{ state_attr('device_tracker.truck', '10C') }}"
    truck_status:
      entity_id: device_tracker.truck
      value_template: "{{ state_attr('device_tracker.truck', 'status') }}"