- platform: snmp
  name: truenas_uptime
  host: ${TRUENAS_IP}
  baseoid: 1.3.6.1.2.1.1.3.0
  accept_errors: true
  unit_of_measurement: "minutes"
  value_template: "{{ ((value | int(0)) / 6000) | int(0) }}"
- platform: snmp
  name: truenas_cpu_load_1m
  host: ${TRUENAS_IP}
  baseoid: 1.3.6.1.4.1.2021.10.1.3.1
  accept_errors: true
  unit_of_measurement: "%"
- platform: snmp
  name: truenas_cpu_load_5m
  host: ${TRUENAS_IP}
  baseoid: 1.3.6.1.4.1.2021.10.1.3.2
  accept_errors: true
  unit_of_measurement: "%"
- platform: snmp
  name: truenas_cpu_load_15m
  host: ${TRUENAS_IP}
  baseoid: 1.3.6.1.4.1.2021.10.1.3.3
  accept_errors: true
  unit_of_measurement: "%"