- platform: command_line
  name: latest_grafana_docker_hub_tag_query
  command: "curl https://hub.docker.com/v2/repositories/grafana/grafana/tags/{{ states('sensor.grafana_latest_version') }}"
  json_attributes:
    - message
    - tag_status