- alias: Turn off everything after leaving
  id: turn_off_everything_after_leaving
  trigger:
    platform: state
    entity_id: person.mike
    to: not_home
  action:
    - service: homeassistant.turn_off
      entity_id: group.everything
    - condition: state
      entity_id: cover.garage_door
      state: open
    - service: cover.close_cover
      entity_id: cover.garage_door
