- alias: 'Bedroom light off'
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.basement_motion
        - binary_sensor.dining_room_motion
        - binary_sensor.office_motion
      to: 'on'
    - platform: state
      entity_id: 
        - sensor.basement_door
        - sensor.garage_inner_door
        - sensor.sliding_side_door
  action:
    service: light.turn_off
    entity_id: light.bedroom_light
    
- alias: 'Bedroom light on'
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_motion
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-01:00:00'
      - condition: time
        before: '20:30:00'
  action:
    service: light.turn_on
    entity_id: light.bedroom_light