- alias: 'Bedtime routine'
  trigger:
    - platform: numeric_state
      entity_id: sensor.bedroom_phone_charger_power
      above: 1
    - platform: state
      entity_id: 
        - binary_sensor.sleepnumber_master_bed_mike_is_in_bed
        - switch.watch_charging_in_bedroom
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.bedroom_phone_charger_power
      above: 1
    - condition: state
      entity_id: binary_sensor.sleepnumber_master_bed_mike_is_in_bed
      state: 'on'
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: switch.watch_charging_in_bedroom
              state: 'off'
          sequence:
            - service: notify.alexa_media_bedroom_echo_dot
              data:
                message: You forgot to charge your watch
                data:
                  type: tts
      default:
        - service: switch.turn_on
          entity_id:
            - switch.bedroom_fan
            - switch.bedroom_noise_machine
        - service: light.turn_off
          entity_id:
            - light.bedroom_lamps
            - light.bedroom_overhead