- alias: 'Turn off HVAC if any doors or windows are open'
  id: turn_off_hvac_if_any_doors_or_windows_are_open
  trigger:
    platform: state
    entity_id: group.exterior_doors_and_windows
    to: 'on'
    for:
      minutes: 5
  action:
    service: climate.turn_off
    entity_id: climate.thermostat

- alias: 'Turn on HVAC when all doors and windows are closed'
  id: turn_on_hvac_when_all_doors_and_windows_are_closed
  trigger:
    platform: state
    entity_id: group.exterior_doors_and_windows
    to: 'off'
  action:
    service: climate.turn_on
    entity_id: climate.thermostat

- alias: 'Set thermostat temperature'
  id: set_thermostat_temperature
  trigger:
    platform: state
    entity_id:
      - sensor.target_temp_heating
      - sensor.target_temp_cooling
  action:
    service: climate.set_temperature
    entity_id: climate.thermostat
    data:
      temperature: >-
        {% if is_state('climate.thermostat', 'heat') %}
          {{ states('sensor.target_temp_heating') }}
        {% else %}
          {{ states('sensor.target_temp_cooling') }}
        {% endif %}
