- alias: 'Climate: Turn off HVAC if any doors or windows are open'
  id: climate_turn_off_hvac_if_any_doors_or_windows_are_open
  trigger:
    platform: state
    entity_id: group.hvac_off
    to: 'on'
    for:
      minutes: 5
  action:
    service: climate.turn_off
    entity_id: climate.thermostat

- alias: 'Climate: Turn on HVAC when all doors and windows are closed'
  id: climate_turn_on_hvac_when_all_doors_and_windows_are_closed
  trigger:
    platform: state
    entity_id: group.hvac_off
    to: 'off'
  action:
    service: climate.turn_on
    entity_id: climate.thermostat

- alias: 'Climate: Set thermostat temperature'
  id: climate_set_thermostat_temperature
  mode: restart
  trigger:
    platform: state
    entity_id:
      - sensor.target_temp_heating
      - sensor.target_temp_cooling
  condition:
    conditon: not
    conditions:
      condition: state
      entity_id:
        - sensor.target_temp_cooling
        - sensor.target_temp_heating
      state: unknown
  action:
    service: climate.set_temperature
    entity_id: climate.thermostat
    data:
      temperature: >-
        {% if is_state('climate.thermostat', 'heat') %}
          {{ states('sensor.target_temp_heating') }}
        {% else %}
          {{ states('sensor.target_temp_cooling') }}
        {% endif %}

- alias: 'Climate: Alert if exterior doors/windows are open when outside temp is above inside'
  id: climate_alert_exterior_open_when_outside_temp_above_inside
  trigger:
    - platform: state
      entity_id:
        - sensor.hvac_current_temperature
        - sensor.outside_temp
    - platform: state
      entity_id: group.exterior_doors_and_windows
      to: 'on'
      for:
        minutes: 5
  condition: 
    - condition: template
      value_template: "{{ (states('sensor.outside_temp') | int) > (states('sensor.hvac_current_temperature') | int) - 2  }}"
    - condition: state
      entity_id: group.exterior_doors_and_windows
      state: 'on'
      for:
        minutes: 5
    - condition: not
      conditions:
        - condition: state
          entity_id: 
            - sensor.hvac_current_temperature
            - sensor.outside_temp
          state: unknown
  action:
    service: notify.mobile_app_sm_g981u1
    data:
      message: "Outside temp ({{states('sensor.outside_temp')}}) is approaching inside temp ({{states('sensor.hvac_current_temperature')}})"
      data:
        sticky: 'true'
        tag: climate-alert

- alias: 'Climate: Clear warning to close doors and windows'
  id: climate_clear_warning_to_close_doors_and_windows
  trigger:
    - platform: state
      entity_id:
        - sensor.hvac_current_temperature
        - sensor.outside_temp
    - platform: state
      entity_id: group.exterior_doors_and_windows
      to: 'off'
  condition: 
    condition: or
    conditions:
      - condition: template
        value_template: "{{ (states('sensor.outside_temp') | int) <= (states('sensor.hvac_current_temperature') | int) - 2  }}"
      - condition: state
        entity_id: group.exterior_doors_and_windows
        state: 'off'
  action:
    service: notify.mobile_app_sm_g981u1
    data:
      message: clear_notification
      data:
        tag: climate-alert