- alias: 'Turn on dehumidifier if above threshold'
  trigger:
    - platform: state
      entity_id: sensor.basement_humidity
    - platform: state
      entity_id: 
        - binary_sensor.basement_motion
        - input_boolean.workout_mode
        - media_player.basement_tv
        - switch.basement_stereo
      to: 'off'
  condition:
    - condition: numeric_state
      entity_id: sensor.basement_humidity
      above: input_number.dehumidifier_on_threshold
    - condition: state
      entity_id: 
        - binary_sensor.basement_motion
        - input_boolean.workout_mode
        - media_player.basement_tv
        - switch.basement_stereo
      state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.dehumidifier

- alias: 'Turn off dehumidifier if below threshold or basement occupied'
  trigger:
    - platform: state
      entity_id: sensor.basement_humidity
    - platform: state
      entity_id: 
        - binary_sensor.basement_motion
        - input_boolean.workout_mode
        - media_player.basement_tv
        - switch.basement_stereo
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: numeric_state
        entity_id: sensor.basement_humidity
        below: input_number.dehumidifier_off_threshold
      - condition: state
        entity_id: binary_sensor.basement_motion
        state: 'on'
      - condition: state
        entity_id: input_boolean.workout_mode
        state: 'on'
      - condition: state
        entity_id: media_player.basement_tv
        state: 'on'
      - condition: state
        entity_id: switch.basement_stereo
        state: 'on'
  action:
    service: switch.turn_off
    entity_id: switch.dehumidifier

- alias: 'Notification to empty dehumidifier'
  mode: restart
  trigger:
    - platform: state
      entity_id: sensor.dehumidifier_power
  action:
    - choose:
        conditions:
          - condition: state
            entity_id: switch.dehumidifier
            state: 'on'
          - condition: numeric_state
            entity_id: sensor.dehumidifier_power
            below: 0.5
        sequence:
          - service: notify.mobile_app_sm_g981u1
            data: 
              message: "Empty the basement dehumidifier"
              data:
                sticky: 'true'
                tag: dehumidifier
      default:
        - service: notify.mobile_app_sm_g981u1
          data:
            message: clear_notification
            data:
              tag: dehumidifier