- alias: 'Turn on dehumidifier if above threshold'
  trigger:
    - platform: state
      entity_id: binary_sensor.basement_humidity_above_threshold
      to: 'on'
    - platform: state
      entity_id: 
        - binary_sensor.basement_motion
        - input_boolean.workout_mode
        - media_player.basement_tv
        - switch.basement_stereo
      to: 'off'
  condition:
    - condition: state
      entity_id: binary_sensor.basement_humidity_above_threshold
      state: 'on'
    - condition: state
      entity_id: binary_sensor.basement_motion
      state: 'off'
    - condition: state
      entity_id: input_boolean.workout_mode
      state: 'off'
    - condition: state
      entity_id: media_player.basement_tv
      state: 'off'
    - condition: state
      entity_id: switch.basement_stereo
      state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.basement_dehumidifier

- alias: 'Turn off dehumidifier if below threshold or basement occupied'
  trigger:
    platform: state
    entity_id: 
      - binary_sensor.basement_humidity_below_threshold
      - binary_sensor.basement_motion
      - input_boolean.workout_mode
      - media_player.basement_tv
      - switch.basement_stereo
    to: 'on'
  action:
    service: switch.turn_off
    entity_id: switch.basement_dehumidifier