- alias: Workout mode on
  id: workout_mode_on
  trigger:
    platform: state
    entity_id: input_boolean.workout_mode
    to: "on"
  action:
    - service: light.turn_on
      entity_id: light.basement
    - service: rest_command.basement_squeezebox_liked_songs_playlist
    - service: switch.turn_on
      target:
        entity_id: switch.basement_stereo

- alias: Workout mode off
  id: workout_mode_off
  trigger:
    platform: state
    entity_id: input_boolean.workout_mode
    to: "off"
  action:
    - service: homeassistant.turn_off
      entity_id: group.basement
    - service: media_player.clear_playlist
      entity_id: media_player.basement_squeezebox

- alias: Workout mode - Turn off everything else when motion detected
  id: workout_mode_turn_off_everything_else_when_motion_detected
  trigger:
    platform: state
    entity_id: group.basement_occupancy
    to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.workout_mode
      state: "on"
    - condition: state
      entity_id: input_boolean.single_occupancy_mode
      state: "on"
  action:
    service: light.turn_off
    target:
      entity_id:
        - light.diningroom
        - light.entry_light
        - light.gameroom_lamp
        - light.gameroom_overhead
        - light.livingroom_lamp
        - light.patio
