- alias: 'Workout mode on'
  id: workout_mode_on
  trigger:
    platform: state
    entity_id: input_boolean.workout_mode
    to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.basement
    - service: shell_command.curl
      data:
        url: !secret workout_music_url
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.workout_mode_available
    - service: switch.turn_on
      target:
        entity_id: switch.basement_stereo
    - condition: state
      entity_id: climate.thermostat
      state: heat
    - service: climate.set_temperature
      target:
        entity_id: climate.thermostat
      data:
        temperature: "{{ states('input_number.climate_heat_away_temp') }}"
        
- alias: 'Workout mode off delayed'
  id: workout_mode_off_delayed
  trigger:
    platform: webhook
    webhook_id: !secret workout_mode_off_webhook
  condition:
    condition: state
    entity_id: input_boolean.workout_mode
    state: 'on'
  action:
    - wait_template: "{{ is_state('binary_sensor.basement_door', 'on') }}"
      timeout: '01:00:00'
    - wait_template: "{{ is_state('binary_sensor.basement_door', 'off') }}"
      timeout: '01:00:00'
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.workout_mode

- alias: 'Workout mode off'
  id: workout_mode_off
  trigger:
    platform: state
    entity_id: input_boolean.workout_mode
    to: 'off'
  action:
    - service: homeassistant.turn_off
      target:
        entity_id: group.basement
    - service: media_player.clear_playlist
      target:
        entity_id: media_player.picoreplayer
    - condition: state
      entity_id: climate.thermostat
      state: heat
    - service: climate.set_temperature
      target:
        entity_id: climate.thermostat
      data:
        temperature: "{{ states('input_number.climate_heat_home_temp') }}"

- alias: 'Run Garmin Update in Jenkins'
  id: run_garmin_update_in_jenkins
  trigger:
    - platform: state
      entity_id: sensor.sm_g981u1_last_notification
      to: 'Your activity is ready to view.'
    - platform: homeassistant
      event: start
  action:
    service: shell_command.curl
    data:
      url: !secret jenkins_garmin_update_url