- alias: 'Workout mode on'
  id: workout_mode_on
  trigger:
    platform: state
    entity_id: input_boolean.workout_mode
    to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.basement
    - service: shell_command.curl
      data:
        url: ${LMS_URL}/plugins/spotty/index.html?action=playall&index=8.1&player=b8%3A27%3Aeb%3Ad3%3A90%3A9b&sess=&start=
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.workout_mode_available
    - service: switch.turn_on
      target:
        entity_id: switch.basement_stereo
    - condition: state
      entity_id: climate.thermostat
      state: heat
    - service: climate.set_temperature
      target:
        entity_id: climate.thermostat
      data:
        temperature: "{{ states('input_number.climate_heat_away_temp') }}"

- alias: 'Workout mode off'
  id: workout_mode_off
  trigger:
    platform: state
    entity_id: input_boolean.workout_mode
    to: 'off'
  action:
    - service: homeassistant.turn_off
      target:
        entity_id: group.basement
    - service: media_player.clear_playlist
      target:
        entity_id: media_player.picoreplayer
    - condition: state
      entity_id: climate.thermostat
      state: heat
    - service: climate.set_temperature
      target:
        entity_id: climate.thermostat
      data:
        temperature: "{{ states('input_number.climate_heat_home_temp') }}"

- alias: 'Run Garmin Update in Jenkins'
  id: run_garmin_update_in_jenkins
  trigger:
    - platform: state
      entity_id: sensor.sm_g981u1_last_notification
      to: 'Your activity is ready to view.'
    - platform: homeassistant
      event: start
  action:
    service: shell_command.curl
    data:
      url: http://${TRUENAS_DOCKER_IP}:${JENKINS_PORT}/generic-webhook-trigger/invoke?token=${JENKINS_GARMIN_UPDATE_TOKEN}

- alias: 'Workout mode: Turn off everything else when motion detected'
  id: workout_mode_turn_off_everything_else_when_motion_detected
  trigger:
    platform: state
    entity_id: group.basement_occupancy
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.workout_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.single_occupancy_mode
      state: 'off'
  action:
    service: light.turn_off
    target:
      entity_id:
        - light.bedroom_lamps
        - light.bedroom_overhead
        - light.diningroom
        - light.entry_light
        - light.gameroom_lamp
        - light.gameroom_overhead
        - light.laundryroom
        - light.livingroom_lamp
        - light.office
        - light.patio
        - light.upstairsbathroom