- alias: 'Game room config button x1 - toggle tv and receiver'
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 6
      property_key: '003'
      value: KeyPressed
  action:
    service: media_player.toggle
    entity_id:
      - media_player.gameroom_tv
      - media_player.gameroom_receiver