- alias: Close garage door after leaving
  id: close_garage_door_after_leaving
  trigger:
    platform: state
    entity_id: person.mike
    to: not_home
  condition:
    condition: state
    entity_id: binary_sensor.garage_door
    state: "on"
  action:
    - service: notify.mobile_app_sm_g981u1
      data:
        message: Closing garage door because you left {{ states.sensor.date.state }} {{ states.sensor.time.state}}
        data:
          tag: garage
    - service: cover.close_cover
      target:
        entity_id: cover.garage_door

- alias: Open garage door when arriving then close
  id: open_garage_door_when_arriving_then_close
  trigger:
    platform: state
    entity_id: person.mike
    to: home
  condition:
    condition: state
    entity_id: binary_sensor.garage_door
    state: "off"
  action:
    - service: notify.mobile_app_sm_g981u1
      data:
        message: Opening garage door (arrival) {{ states.sensor.date.state }} {{ states.sensor.time.state}}
        data:
          tag: garage
    - service: cover.open_cover
      target:
        entity_id: cover.garage_door
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.garage_inner_door
          to: "on"
      timeout:
        minutes: 15
    - service: cover.close_cover
      target:
        entity_id: cover.garage_door
    - service: notify.mobile_app_sm_g981u1
      data:
        message: clear_notification
        data:
          tag: garage
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - service: switch.turn_on
      target:
        entity_id: switch.entry_light

- alias: Garage door relay shut off
  id: garage_door_relay_shut_off
  trigger:
    platform: state
    entity_id: switch.garage_door_relay
    to: "on"
    for: 00:00:02
  action:
    service: switch.turn_off
    target:
      entity_id: switch.garage_door_relay
