- alias: 'Close garage door after leaving'
  trigger:
    platform: state
    entity_id: person.mike
    to: 'not_home'
  condition:
    condition: state
    entity_id: binary_sensor.garage_door
    state: 'on'
  action:
    - service: notify.mobile_app_sm_g981u1
      data: 
        message: "Closing garage door because you left {{ states.sensor.date.state }} {{ states.sensor.time.state}}"
        data:
          tag: garage
    - service: cover.close_cover
      entity_id: cover.garage_door

- alias: 'Open garage door when arriving then close'
  trigger:
    platform: state
    entity_id: person.mike
    to: 'home'
  condition:
    condition: state
    entity_id: binary_sensor.garage_door
    state: 'off'
  action:
    - service: notify.mobile_app_sm_g981u1
      data:
        message: "Opening garage door (arrival) {{ states.sensor.date.state }} {{ states.sensor.time.state}}"
        data:
          tag: garage
    - service: cover.open_cover
      entity_id: cover.garage_door
    - wait_template: "{{ is_state('binary_sensor.garage_inner_door', 'on') }}"
      timeout: 00:10:00
      continue_on_timeout: 'false'
    - service: cover.close_cover
      entity_id: cover.garage_door
    - service: notify.mobile_app_sm_g981u1
      data:
        message: clear_notification
        data:
          tag: garage

- alias: 'Garage door relay shut off'
  trigger:
    platform: state
    entity_id: switch.garage_door_relay
    to: 'on'
    for: '00:00:02'
  action:
    service: switch.turn_off
    entity_id: switch.garage_door_relay