- alias: 'Appdaemon Git Pull'
  id: appdaemon_git_pull
  trigger:
    platform: webhook
    webhook_id: !secret appdaemon_git_pull_webhook
  action:
    event: APPDAEMON_GIT_PULL
    
- alias: 'Appdaemon Sleepyq Update'
  id: appdaemon_sleepyq_update
  trigger:
    platform: webhook
    webhook_id: !secret appdaemon_sleepyq_update_webhook
  action:
    event: APPDAEMON_UPDATE_SLEEPYQ
    
- alias: 'HASS Config Update'
  id: hass_config_update
  trigger:
    platform: webhook
    webhook_id: !secret hass_repo_update_webhook
  action:
    - service: shell_command.git_pull
    - delay: 00:00:10
    - service: automation.reload
    - service: frontend.reload_themes
    - service: group.reload
    - service: input_boolean.reload
    - service: input_number.reload
    - service: input_select.reload
    - service: lovelace.reload_resources
    - service: person.reload
    - service: script.reload
    - service: zone.reload