- alias: 'Set inovelli light switch led effect'
  id: set_inovelli_light_switch_led_effect
  trigger:
    platform: state
    entity_id: 
      - group.led_red
      - group.led_yellow
      - group.led_purple
      - group.led_chase
      - group.led_blink
      - group.led_solid
  action:
    service: zwave_js.bulk_set_partial_config_parameters
    target:
      entity_id:
        - light.basement
        - light.diningroom
        - light.gameroom_overhead
        - light.laundryroom
        - light.livingroom_wall_switch_1
        - light.livingroom_wall_switch_2
        - light.patio
    data:
      parameter: 16
      value: 
        # Color:
        255: >-
          {% if is_state('group.led_red', 'on') %}
            0
          {% elif is_state('group.led_purple', 'on') %}
            212
          {% elif is_state('group.led_yellow', 'on') %}
            42
          {% else %}
            170
          {% endif %}

        # Brightness
        65280: 10

        # Duration (forever)
        16711680: 255

        # Effect type
        2130706432: >-
          {% if is_state('group.led_chase', 'on') %}
            2
          {% elif is_state('group.led_blink', 'on') %}
            4
          {% elif is_state('group.led_solid', 'on') %}
            1
          {% else %}
            0
          {% endif %}
