- alias: 'Start living room volume up automation on hold'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.livingroom_switch_1
        scene_id: 2
        scene_data: 7800
  condition:
    condition: state
    entity_id: media_player.living_room_receiver
    state: 'on'
  action:
    service: automation.turn_on
    entity_id: automation.living_room_volume_up
        
- alias: 'Stop living room volume up automation on release'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.livingroom_switch_1
        scene_id: 2
        scene_data: 7740
  action:
    service: automation.turn_off
    entity_id: automation.living_room_volume_up

- alias: 'Living room volume up'
  initial_state: false
  trigger:
    platform: time_pattern
    seconds: "*"
  action:
    service: media_player.volume_up
    entity_id: media_player.living_room_receiver
    
- alias: 'Start living room volume down automation on hold'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.livingroom_switch_1
        scene_id: 1
        scene_data: 7800
  condition:
    condition: state
    entity_id: media_player.living_room_receiver
    state: 'on'
  action:
    service: automation.turn_on
    entity_id: automation.living_room_volume_down
        
- alias: 'Stop living room volume down automation on release'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.livingroom_switch_1
        scene_id: 1
        scene_data: 7740
  action:
    service: automation.turn_off
    entity_id: automation.living_room_volume_down

- alias: 'Living room volume down'
  initial_state: false
  trigger:
    platform: time_pattern
    seconds: "*"
  action:
    service: media_player.volume_down
    entity_id: media_player.living_room_receiver