- alias: 'Mouse trap triggered notification'
  id: mouse_trap_triggered_notification
  trigger:
    platform: state
    entity_id: binary_sensor.mousetrap_triggered
    to: 'on'
  action:
    service: notify.email
    data: 
      message: "Mouse trap activated! {{ states.sensor.date.state }} {{ states.sensor.time.state}}"
      data:
        sticky: 'true'
        tag: mouse_trap

- alias: 'Mouse trap triggered clear notification'
  id: mouse_trap_triggered_clear_notification
  trigger:
    platform: state
    entity_id: binary_sensor.mousetrap_triggered
    to: 'off'
  action:
    service: notify.mobile_app_sm_g981u1
    data:
      message: clear_notification
      data:
        tag: mouse_trap