- alias: LMS next track fix
  id: lms_next_track_fix
  trigger:
    platform: state
    entity_id: media_player.livingroom_squeezebox
    attribute: media_position
    for: "00:00:15"
  condition:
    - condition: state
      entity_id: media_player.livingroom_squeezebox
      state: playing
    - "{{ (state_attr('media_player.livingroom_squeezebox', 'media_position') | int) >= (state_attr('media_player.livingroom_squeezebox', 'media_duration'))}}"
  action:
    service: media_player.media_next_track
    entity_id: media_player.livingroom_squeezebox

- alias: Music - Skip track with config buttons
  id: music_skip_track_with_config_buttons
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      property_key: "003"
      value: KeyPressed
  condition: "{{ trigger.event.data.node_id != 40 }}"
  action:
    service: media_player.media_next_track
    entity_id: media_player.spotify_stukabombr1