- alias: 'Turn up patio volume when motion is detected'
  id: turn_on_patio_music_when_motion_is_detected
  trigger:
    platform: state
    entity_id: binary_sensor.patio_motion_1
    to: 'on'
  condition:
    condition: state
    entity_id: media_player.patio_squeezelite
    state: playing
  action:
    service: media_player.volume_set
    target:
      entity_id: media_player.patio_squeezelite
    data:
      volume_level: 0.32

- alias: 'Patio config button x1 - Turn off patio volume'
  id: turn_off_patio_volume_when_not_in_use
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 22
      property_key: '003'
      value: KeyPressed
  action:
    service: media_player.volume_set
    target:
      entity_id: media_player.patio_squeezelite
    data:
      volume_level: 0