- alias: 'Office light off'
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.basement_motion
        - binary_sensor.bedroom_motion
        - binary_sensor.dining_room_motion
      to: 'on'
    - platform: state
      entity_id: 
        - sensor.basement_door
        - sensor.garage_inner_door
        - sensor.sliding_side_door
  action:
    service: light.turn_off
    entity_id: light.office_light
    
- alias: 'Office light on'
  trigger:
    platform: state
    entity_id: binary_sensor.office_motion
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.office_light