- alias: 'Patio switch double tap up - turn on lamp'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.patio_light
        scene_id: 2
        scene_data: 7860
  action:
    service: light.turn_on
    entity_id: light.living_room_lamp
      
- alias: 'Patio switch double tap down - turn on lamp'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.patio_light
        scene_id: 1
        scene_data: 7860
  action:
    service: light.turn_off
    entity_id: light.living_room_lamp
    
- alias: 'Patio switch triple tap up - cycle lamp color'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.patio_light
        scene_id: 2
        scene_data: 7920
  action:
    service: input_select.select_next
    entity_id: input_select.living_room_lamp_color
      
- alias: 'Patio switch triple tap down - cycle lamp color'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.patio_light
        scene_id: 1
        scene_data: 7920
  action:
    service: input_select.select_previous
    entity_id: input_select.living_room_lamp_color