- alias: 'Garage Door Open For 20 Minutes'
  trigger:
    platform: state
    entity_id: sensor.garage_door
    to: 'open'
    for: 00:20:00
  action:
    service: notify.email
    data_template: 
      title: 'Garage door is open'
      message: "Garage door is open! {{ states.sensor.date.state }} {{ states.sensor.time.state}}"
- alias: 'Door Alarm'
  trigger:
    platform: state
    entity_id: 
      - sensor.basement_door
      - sensor.front_door
      - sensor.garage_door
      - sensor.garage_inner_door
      - sensor.sliding_side_door
      - sensor.kitchen_window
    to: 'open'
  condition:
    condition: template
    value_template: "{{ not is_state('person.mike', 'home') }}"
  action:
    service: notify.email
    data_template: 
      title: 'Door or window sensor triggered'
      message: "Sensor triggered! {{trigger.entity_id}} {{states.sensor.date.state}} {{states.sensor.time.state}}"
- alias: 'Motion detected'
  trigger:
    platform: state
    entity_id:
      - binary_sensor.basement_motion
      - binary_sensor.bedroom_motion
      - binary_sensor.dining_room_motion
      - binary_sensor.office_motion
  condition:
    condition: template
    value_template: "{{ not is_state('person.mike', 'home') }}"
  action:
    service: notify.email
    data_template: 
      title: 'Motion detected'
      message: "Motion detected! {{trigger.entity_id}} {{states.sensor.date.state}} {{states.sensor.time.state}}"