- alias: Single Occupancy Mode - With Guests
  id: single_occupancy_mode_turn_off_when_guests_arrive
  trigger:
    - platform: state
      entity_id: group.guest_devices
    - platform: state
      entity_id: input_boolean.single_occupancy_mode_lock
      to: "off"
  condition:
    condition: state
    entity_id: input_boolean.single_occupancy_mode_lock
    state: "off"
  action:
    service: input_boolean.turn_{{ "off" if is_state("group.guest_devices", "home") else "on" }}
    target:
      entity_id: input_boolean.single_occupancy_mode

- alias: Single Occupancy Mode - Lock/Unlock
  id: single_occupancy_mode_lock_unlock
  trigger:
    platform: state
    entity_id: input_boolean.single_occupancy_mode
  condition: "{{ trigger.to_state.context.user_id != 'null' }}"
  action:
    service: input_boolean.turn_{{ "off" if trigger.to_state.state == "on" else "on" }}
    target:
      entity_id: input_boolean.single_occupancy_mode_lock

- alias: Dummy Guest Device Tracker
  id: dummy_guest_device_tracker
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_boolean.dummy_guest
  action:
    service: device_tracker.see
    data:
      mac: dummy_guest
      location_name: "{{ 'home' if is_state('input_boolean.dummy_guest', 'on') else 'not_home' }}"
