- alias: Living Room Tablet Charging - Off
  id: livingroom_tablet_charging_off
  trigger:
    - platform: numeric_state
      entity_id: sensor.livingroom_tablet_battery
      above: 85
    - platform: homeassistant
      event: start
  condition:
    condition: numeric_state
    entity_id: sensor.livingroom_tablet_battery
    above: 85
  action:
    service: switch.turn_off
    entity_id: switch.kitchen_tablet

- alias: Living Room Tablet Charging - On
  id: livingroom_tablet_charging_on
  trigger:
    - platform: numeric_state
      entity_id: sensor.livingroom_tablet_battery
      below: 20
    - platform: homeassistant
      event: start
  condition:
    condition: numeric_state
    entity_id: sensor.livingroom_tablet_battery
    below: 20
  action:
    service: switch.turn_on
    entity_id: switch.kitchen_tablet
