- alias: 'Reset medication task'
  id: reset_medication_task
  trigger:
    platform: time
    at: '05:00:00'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.take_medication

- alias: 'Task notification'
  id: task_notification
  trigger:
    platform: state
    entity_id: 
      - input_boolean.take_medication
    to: 'on'
  action:
    service: notify.mobile_app_sm_g981u1
    data:
      message: "{{ trigger.entity_id.split('.')[1].replace('_', ' ').capitalize() }}"
      data:
        sticky: 'true'
        tag: "{{ trigger.entity_id }}"
        actions:
          - action: "{{ trigger.entity_id }}"
            title: Mark as Complete

- alias: 'Clear task notification'
  id: clear_task_notification
  trigger:
    platform: event
    event_type: mobile_app_notification_action
  action:
    - service: notify.mobile_app_sm_g981u1
      data:
        message: clear_notification
        data:
          tag: "{{ trigger.event.data.action }}"
    - service: input_boolean.turn_off
      entity_id: "{{ trigger.event.data.action }}"
