- alias: 'Reset medication task'
  id: reset_medication_task
  trigger:
    platform: time
    at: '05:00:00'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.take_medication

- alias: 'Task notification'
  id: task_notification
  trigger:
    platform: state
    entity_id: 
      - input_boolean.take_medication
  action:
    service: notify.mobile_app_sm_g981u1
    data:
      message: >-
        {% if trigger.to_state.state == 'on' %}
          {{ trigger.entity_id.split('.')[1].replace('_', ' ').capitalize() }}
        {% else %}
          clear_notification
        {% endif %}
      data:
        sticky: 'true'
        tag: "{{ trigger.entity_id }}"
        actions:
          - action: "{{ trigger.entity_id }}"
            title: Mark as Complete

- alias: 'Mark task as complete'
  id: mark_task_as_complete
  trigger:
    platform: event
    event_type: mobile_app_notification_action
  action:
    service: input_boolean.turn_off
    target:
      entity_id: "{{ trigger.event.data.action }}"
