- alias: 'Set thermostat temperature'
  trigger:
    platform: state
    entity_id:
      - sensor.target_temp_heating
      - sensor.target_temp_cooling
  action:
    service: climate.set_temperature
    entity_id: climate.thermostat
    data:
      temperature: >-
        {% if is_state('climate.thermostat', 'heat') %}
          {{ states('sensor.target_temp_heating') }}
        {% else %}
          {{ states('sensor.target_temp_cooling') }}
        {% endif %}