- alias: 'Truck started rpm'
  trigger:
    platform: state
    entity_id: sensor.truck_rpm
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.truck_running_rpm
    
- alias: 'Truck stopped rpm'
  trigger:
    platform: state
    entity_id: binary_sensor.truck_rpm_not_changing
    to: 'on'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.truck_running_rpm
    
- alias: 'Truck started status'
  trigger:
    platform: state
    entity_id: sensor.truck_status
    to: online
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.truck_running_status 
    
- alias: 'Truck stopped status'
  trigger:
    platform: state
    entity_id: sensor.truck_status
    to: unknown
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.truck_running_status 