- alias: Turn on living room receiver when tv turns on
  id: turn_on_living_room_receiver_when_tv_turns_on
  trigger:
    platform: state
    entity_id: media_player.livingroom_tv
    to: "on"
  action:
    - service: media_player.turn_on
      entity_id: media_player.livingroom_receiver
    - delay: 00:00:03
    - service: media_player.select_source
      entity_id: media_player.livingroom_receiver
      data:
        source: tv/cd

- alias: Turn off living room receiver when tv turns off
  id: turn_off_living_room_receiver_when_tv_turns_off
  trigger:
    platform: state
    entity_id: media_player.livingroom_tv
    to: "off"
  condition:
    condition: template
    value_template: >-
      {{ state_attr('media_player.livingroom_receiver', 'source') == 'cd_tv/cd' }}
  action:
    service: media_player.turn_off
    entity_id: media_player.livingroom_receiver

- alias: Sync basement stereo to tv
  id: sync_basement_stereo_to_tv
  trigger:
    platform: state
    entity_id: media_player.basement_tv
  condition:
    condition: state
    entity_id: input_boolean.workout_mode
    state: "off"
  action:
    service: switch.turn_{{ trigger.to_state.state }}
    entity_id: switch.basement_stereo

- alias: Turn On Game Room TV with WakeOnLan
  trigger:
    - platform: webostv.turn_on
      entity_id: media_player.gameroom_tv
  action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: ${GAMEROOM_TV_MAC}
