- alias: 'Appdaemon Git Pull'
  trigger:
    platform: webhook
    webhook_id: !secret appdaemon_git_pull_webhook
  action:
    event: APPDAEMON_GIT_PULL
    
- alias: 'Appdaemon Sleepyq Update'
  trigger:
    platform: webhook
    webhook_id: !secret appdaemon_sleepyq_update_webhook
  action:
    event: APPDAEMON_UPDATE_SLEEPYQ