- alias: 'Upstairs bathroom occupied'
  id: upstairs_bathroom_occupied
  trigger:
    platform: state
    entity_id: binary_sensor.upstairsbathroom_motion
    to: 'on'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.upstairsbathroom_occupancy

- alias: 'Upstairs bathroom unoccupied'
  id: upstairs_bathroom_unoccupied
  trigger:
    - platform: state
      entity_id: binary_sensor.upstairsbathroom_motion
      to: 'off'
    - platform: state
      entity_id: binary_sensor.upstairsbathroom_door
      to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.upstairsbathroom_door
    state: 'on'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.upstairsbathroom_occupancy

- alias: 'Upstairs bathroom lights on'
  id: upstairs_bathroom_lights_on
  trigger:
    platform: state
    entity_id: input_boolean.upstairsbathroom_occupancy
    to: 'on'
  condition:
    condition: state
    entity_id: light.upstairsbathroom
    state: 'off'
  action:
    service: light.turn_on
    entity_id: light.upstairsbathroom
    data:
      brightness: "{{ states('input_number.upstairsbathroom_light_brightness')}}"
      transition: "{{ states('input_number.upstairsbathroom_light_transition')}}"

- alias: 'Upstairs bathroom lights off'
  id: upstairs_bathroom_lights_off
  trigger: 
    platform: state
    entity_id: input_boolean.upstairsbathroom_occupancy
    to: 'off'
    for: 
      minutes: "{{ states('input_number.upstairsbathroom_occupancy_timeout_min') | int }}"
      seconds: "{{ states('input_number.upstairsbathroom_occupancy_timeout_sec') | int }}"
  action:
    service: light.turn_off
    entity_id: light.upstairsbathroom

- alias: 'Upstairs bathroom vent control'
  id: upstairs_bathroom_vent_control
  trigger:
    platform: state
    entity_id: binary_sensor.upstairsbathroom_door
  action:
    service: >-
      {% if trigger.to_state.state == 'on' %}
        switch.turn_off
      {% else %}
        switch.turn_on
      {% endif %}
    entity_id: switch.upstairsbathroom_vent

- alias: 'Set upstairs bathroom light brightness'
  id: set_upstairs_bathroom_light_brightness
  trigger:
    platform: state
    entity_id:
      - input_boolean.sleep_mode
      - sun.sun
  action:
    service: input_number.set_value
    entity_id: input_number.upstairsbathroom_light_brightness
    data:
      value: >-
        {% if is_state('input_boolean.sleep_mode', 'on') %}
          {{ states('input_number.upstairsbathroom_light_sleeping_brightness') }}
        {% elif is_state('sun.sun', 'above_horizon') %}
          {{ states('input_number.upstairsbathroom_light_day_brightness') }}
        {% else %}
          {{ states('input_number.upstairsbathroom_light_night_brightness') }}
        {% endif %}

- alias: 'Upstairs bathroom all off if no motion'
  id: upstairs_bathroom_all_off_if_no_motion
  trigger:
    platform: state
    entity_id: binary_sensor.upstairsbathroom_motion
    to: 'off'
    for: 
      minutes: "{{ states('input_number.upstairsbathroom_no_motion_timeout_min') | int }}"
  action:
    service: homeassistant.turn_off
    entity_id:
      - light.upstairsbathroom
      - switch.upstairsbathroom_vent
      - input_boolean.upstairsbathroom_occupancy

