- alias: Vacuum - Run
  id: vacuum_run
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: person.mike
      to: not_home
      for:
        minutes: "{{ states('input_number.run_vacuum_after_away_min') }}"
    - platform: state
      entity_id:
        - input_boolean.workout_mode
        - input_boolean.vacuum_gameroom_23_day_enable
        - input_boolean.vacuum_hallway_20_day_enable
        - input_boolean.vacuum_bedroom_22_day_enable
        - input_boolean.vacuum_livingroom_16_day_enable
        - input_boolean.vacuum_kitchen_18_day_enable
        - input_boolean.vacuum_diningroom_17_day_enable
        - input_boolean.vacuum_office_19_day_enable
        - input_boolean.vacuum_upstairsbathroom_21_day_enable
        - input_boolean.vacuum_gameroom_23_night_enable
        - input_boolean.vacuum_hallway_20_night_enable
        - input_boolean.vacuum_bedroom_22_night_enable
        - input_boolean.vacuum_livingroom_16_night_enable
        - input_boolean.vacuum_kitchen_18_night_enable
        - input_boolean.vacuum_diningroom_17_night_enable
        - input_boolean.vacuum_office_19_night_enable
        - input_boolean.vacuum_upstairsbathroom_21_night_enable
      to: "on"
    - platform: state
      entity_id: vacuum.roborock_s6_pure
      to: docked
    - platform: state
      entity_id: input_boolean.sleep_mode
      to: "on"
      for:
        minutes: "{{ states('input_number.run_vacuum_after_asleep_min') }}"
    - platform: state
      entity_id: input_number.vacuum_rooms_cleaned_since_being_emptied
      to: "0.0"
  condition:
    - condition: "{{ states('sensor.vacuum_next_rooms_to_clean_list') | from_json | length > 0}}"
    - condition: state
      entity_id: vacuum.roborock_s6_pure
      state: docked
    - condition: or
      conditions:
        - condition: state
          entity_id: person.mike
          state: not_home
        - condition: state
          entity_id: input_boolean.workout_mode
          state: "on"
        - condition: and
          conditions:
            - condition: state
              entity_id:
                - input_boolean.sleep_mode
                - switch.bedroom_fan
              state: "on"
            - condition: state
              entity_id: binary_sensor.bedroom_door
              state: "off"
  action:
    - service: xiaomi_miio.vacuum_clean_segment
      target:
        entity_id: vacuum.roborock_s6_pure
      data:
        segments: "{{ states('sensor.vacuum_next_rooms_to_clean') }}"
    - repeat:
      while: "{{ states('sensor.vacuum_next_rooms_to_clean') | from_json | length > 0 }}"
      sequence:
        - service: input_number.increment
          entity_id: input_number.vacuum_rooms_cleaned_since_being_emptied
        - service: input_datetime.set_datetime
          entity_id: >-
            {% set id = (states('sensor.vacuum_next_rooms_to_clean') | from_json)[0] | int(0) %}
            {% for state in states.input_number %}
              {% if state.entity_id.endswith('_id') and (state.state | int(0)) == id %}
                input_datetime.vacuum_{{ state.entity_id.split('_')[2] }}_last_cleaned
              {% endif %}
            {% endfor %}
          data:
            timestamp: "{{ now().timestamp() }}"

- alias: Vacuum - Empty bin notification
  id: vacuum_empty_bin_notification
  trigger:
    platform: state
    entity_id: vacuum.roborock_s6_pure
    to: docked
  condition: "{{ (states('input_number.vacuum_rooms_cleaned_since_being_emptied') | int(0)) >= (states('input_number.vacuum_max_rooms_cleaned_before_emptying') | int(0))}}"
  action:
    service: input_boolean.turn_on
    target:
      entity_id: input_boolean.empty_vacuum

- alias: Vacuum - Reset rooms cleaned counter
  id: vacuum_reset_rooms_cleaned_counter
  trigger:
    platform: state
    entity_id: input_boolean.empty_vacuum
    to: "off"
  action:
    service: input_number.set_value
    target:
      entity_id: input_number.vacuum_rooms_cleaned_since_being_emptied
    data:
      value: 0

- alias: Vacuum - Error notification
  id: vacuum_error_notification
  trigger:
    platform: state
    entity_id: vacuum.roborock_s6_pure
    to: error
  action:
    service: notify.mobile_app_sm_g981u1
    data:
      message: Vacuum Error
      data:
        tag: vacuum_error

- alias: Vacuum - Clear error notification
  id: vacuum_clear_error_notification
  trigger:
    platform: state
    entity_id: vacuum.roborock_s6_pure
    from: error
  action:
    service: notify.mobile_app_sm_g981u1
    data:
      message: clear_notification
      data:
        tag: vacuum_error

- alias: Vacuum - Set fan speed
  id: vacuum_set_fan_speed
  trigger:
    - platform: state
      entity_id:
        - input_boolean.sleep_mode
        - input_select.vacuum_fan_speed_day
        - input_select.vacuum_fan_speed_night
  action:
    service: vacuum.set_fan_speed
    entity_id: vacuum.roborock_s6_pure
    data:
      fan_speed: >-
        {% if is_state('input_boolean.sleep_mode', 'on') %}
          {{ states('input_select.vacuum_fan_speed_night') }}
        {% else %}
          {{ states('input_select.vacuum_fan_speed_day') }}
        {% endif %}
