- alias: 'Workout mode on'
  trigger:
    platform: state
    entity_id: input_boolean.workout_mode
    to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.basement
    - service: media_player.shuffle_set
      target:
        entity_id: media_player.spotify_stukabombr1
      data:
        shuffle: true
    - service: media_player.select_source
      target:
        entity_id: media_player.spotify_stukabombr1
      data:
        source: 'livingroom_squeezelite, garage & basement_squeezelite'
    - service: media_player.play_media
      target:
        entity_id: media_player.spotify_stukabombr1
      data:
        media_content_type: playlist
        media_content_id: "https://open.spotify.com/playlist/0B6eaVFw7FpYuQIFiQb0bF?si=ia1wgc10TbmXSBm-JD3wwg"
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.workout_mode_available
    - service: switch.turn_on
      target:
        entity_id: switch.basement_stereo
    - condition: state
      entity_id: climate.thermostat
      state: heat
    - service: climate.set_temperature
      target:
        entity_id: climate.thermostat
      data:
        temperature: "{{ states('input_number.climate_heat_away_temp') }}"
        
- alias: 'Workout mode off delayed'
  trigger:
    platform: webhook
    webhook_id: !secret workout_mode_off_webhook
  condition:
    condition: state
    entity_id: input_boolean.workout_mode
    state: 'on'
  action:
    - wait_template: "{{ is_state('binary_sensor.basement_door', 'on') }}"
      timeout: '01:00:00'
    - wait_template: "{{ is_state('binary_sensor.basement_door', 'off') }}"
      timeout: '01:00:00'
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.workout_mode

- alias: 'Workout mode off'
  trigger:
    platform: state
    entity_id: input_boolean.workout_mode
    to: 'off'
  action:
    - service: homeassistant.turn_off
      target:
        entity_id: group.basement
    - service: media_player.media_pause
      target:
        entity_id: media_player.spotify_stukabombr1
    - condition: state
      entity_id: climate.thermostat
      state: heat
    - service: climate.set_temperature
      target:
        entity_id: climate.thermostat
      data:
        temperature: "{{ states('input_number.climate_heat_home_temp') }}"