- alias: Basement - Lights On
  id: basement_lights_on
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: sensor.basement_aqara_fp1_presence_event
      to:
        - enter
        - left_enter
        - right_enter
        - approach
    - platform: state
      entity_id: binary_sensor.basement_aqara_fp1_presence
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.someone_is_home
      state: 'on'
  action:
    service: light.turn_on
    target:
      entity_id: light.basement

- alias: Basement - Lights Off
  id: basement_lights_off
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: binary_sensor.basement_aqara_fp1_presence
      to: 'off'
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
  condition:
    condition: state
    entity_id: binary_sensor.basement_aqara_fp1_presence
    state: 'off'
  action:
    service: light.turn_off
    target:
      entity_id: light.basement

- alias: Basement - Dehumidifier - On if above threshold
  id: basement_dehumidifier_on_if_above_threshold
  trigger:
    - platform: state
      entity_id: sensor.basement_humidity
    - platform: state
      entity_id:
        - binary_sensor.basement_aqara_fp1_presence
        - input_boolean.workout_mode
        - media_player.basement_tv
        - switch.basement_stereo
      to: "off"
  condition:
    - condition: numeric_state
      entity_id: sensor.basement_humidity
      above: input_number.dehumidifier_on_threshold
    - condition: state
      entity_id:
        - binary_sensor.basement_aqara_fp1_presence
        - input_boolean.workout_mode
        - media_player.basement_tv
        - switch.basement_stereo
      state: "off"
  action:
    service: switch.turn_on
    entity_id: switch.dehumidifier

- alias: Basement - Dehumidifier - Off if below threshold or basement occupied
  id: basement_dehumidifier_off_if_below_threshold_or_basement_occupied
  trigger:
    - platform: state
      entity_id: sensor.basement_humidity
    - platform: state
      entity_id:
        - binary_sensor.basement_aqara_fp1_presence
        - input_boolean.workout_mode
        - media_player.basement_tv
        - switch.basement_stereo
      to: "on"
  condition:
    condition: or
    conditions:
      - condition: numeric_state
        entity_id: sensor.basement_humidity
        below: input_number.dehumidifier_off_threshold
      - condition: state
        entity_id:
          - binary_sensor.basement_aqara_fp1_presence
          - input_boolean.workout_mode
          - media_player.basement_tv
          - switch.basement_stereo
        state: "on"
        match: any
  action:
    service: switch.turn_off
    entity_id: switch.dehumidifier

- alias: Basement - Dehumidifier - Empty Notification
  id: basement_dehumidifier_empty_notification
  mode: restart
  trigger:
    - platform: state
      entity_id:
        - sensor.dehumidifier_power
        - switch.dehumidifier
    - platform: state
      entity_id: switch.dehumidifier
      to: "on"
      for: 00:02:00
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: switch.dehumidifier
              state: "on"
              for: 00:02:00
            - condition: numeric_state
              entity_id: sensor.dehumidifier_power
              below: 0.5
          sequence:
            - service: input_boolean.turn_on
              entity_id: input_boolean.empty_dehumidifier
        - conditions:
            - condition: state
              entity_id: switch.dehumidifier
              state: "on"
            - condition: numeric_state
              entity_id: sensor.dehumidifier_power
              above: 20
          sequence:
            - service: input_boolean.turn_off
              entity_id: input_boolean.empty_dehumidifier
