- alias: First Floor Bathroom - Lights On
  id: first_floor_bathroom_lights_on
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: binary_sensor.firstfloorbathroom_presence_sensor_presence
      to: 'on'
    - platform: state
      entity_id: sensor.firstfloorbathroom_presence_sensor_presence_event
      to:
        - enter
        - approach
  action:
    - service: light.turn_on
      entity_id: light.firstfloorbathroom
      data:
        brightness: "{{ states('sensor.firstfloorbathroom_light_brightness') | int(default=255) }}"
        transition: "{{ states('sensor.firstfloorbathroom_light_transition') | int(default=0) }}"
    - delay: 10
    - if:
        - condition: state
          entity_id: binary_sensor.firstfloorbathroom_presence_sensor_presence
          state: 'off'
      then:
        - service: automation.trigger
          entity_id: automation.first_floor_bathroom_lights_off

- alias: First Floor Bathroom - Lights Off
  id: first_floor_bathroom_lights_off
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.firstfloorbathroom_presence_sensor_presence
      to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.firstfloorbathroom
      data:
        transition: "{{ states('sensor.firstfloorbathroom_light_transition') | int(default=0) }}"
    