- alias: First Floor Bathroom - Lights On
  id: first_floor_bathroom_lights_on
  max_exceeded: silent
  trigger:
    - platform: device
      type: action
      subtype: region_1_enter
      domain: mqtt
      device_id: 29db958fa5c12c5ef7f9fe1133565c5b
      discovery_id: 0x54ef44100053c7af action_region_1_enter
    - platform: device
      type: action
      subtype: region_1_occupied
      domain: mqtt
      device_id: 29db958fa5c12c5ef7f9fe1133565c5b
      discovery_id: 0x54ef44100053c7af action_region_1_occupied
  action:
    service: light.turn_on
    entity_id: light.firstfloorbathroom
    data:
      brightness: "{{ states('sensor.firstfloorbathroom_light_brightness') | int(default=255) }}"
      transition: "{{ states('sensor.firstfloorbathroom_light_transition') | int(default=0) }}"

- alias: First Floor Bathroom - Lights Off
  id: first_floor_bathroom_lights_off
  max_exceeded: silent
  trigger:
    - platform: device
      type: action
      subtype: region_1_leave
      domain: mqtt
      device_id: 29db958fa5c12c5ef7f9fe1133565c5b
      discovery_id: 0x54ef44100053c7af action_region_1_leave
    - platform: device
      type: action
      subtype: region_1_unoccupied
      domain: mqtt
      device_id: 29db958fa5c12c5ef7f9fe1133565c5b
      discovery_id: 0x54ef44100053c7af action_region_1_unoccupied
  action:
    service: light.turn_off
    entity_id: light.firstfloorbathroom
    data:
      transition: "{{ states('sensor.firstfloorbathroom_light_transition') | int(default=0) }}"
