- alias: Game room config button x1 - toggle tv and receiver
  id: game_room_config_button_x1_toggle_tv_and_receiver
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 6
      property_key: "003"
      value: KeyPressed
  action:
    service: media_player.toggle
    entity_id:
      - media_player.gameroom_tv
      - media_player.gameroom_receiver

- alias: Game Room - Lights On
  id: game_room_lights_on
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: sensor.gameroom_aqara_fp1_presence_event
      to:
        - enter
        - left_enter
        - right_enter
        - approach
    - platform: state
      entity_id: binary_sensor.gameroom_aqara_fp1_presence
      to: "on"
  condition:
    - condition: state
      entity_id: media_player.gameroom_tv
      state: "off"
    - condition: state
      entity_id: binary_sensor.someone_is_home
      state: "on"
  action:
    service: light.turn_on
    target:
      entity_id: light.gameroom_overhead

- alias: Game Room - Lights Off
  id: game_room_lights_off
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: sensor.gameroom_aqara_fp1_presence_event
      to:
        - leave
        - left_leave
        - right_leave
        - away
    - platform: state
      entity_id: binary_sensor.gameroom_aqara_fp1_presence
      to: "off"
    - platform: state
      entity_id: media_player.gameroom_tv
      to: "on"
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.gameroom_aqara_fp1_presence
        state: "off"
      - condition: state
        entity_id: media_player.gameroom_tv
        state: "on"
  action:
    service: light.turn_off
    target:
      entity_id: light.gameroom_overhead
