- alias: Garage inner scene main button - toggle arcade
  id: garage_inner_scene_main_button_toggle_arcade
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 40
      property_key: "005"
      value: KeyPressed
  action:
    service: switch.toggle
    entity_id:
      - switch.arcade_cabinet_computer
      - switch.arcade_cabinet_monitor
      - switch.arcade_cabinet_audio
      - switch.arcade_cabinet_marquee_light

- alias: Garage switches - toggle air hockey fan
  id: garage_switches_toggle_air_hockey_fan
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 40
        property_key: "002"
        value: KeyPressed
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 37
        property_key: "003"
        value: KeyPressed
  action:
    service: switch.toggle
    entity_id: switch.air_hockey

- alias: Garage switches - open garage door
  id: garage_switches_open_garage_door
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 37
        property_key: "002"
        value: KeyPressed3x
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 43
        property_key: "002"
        value: KeyPressed3x
  action:
    service: cover.open_cover
    entity_id: cover.garage_door_left

- alias: Garage switches - close garage door
  id: garage_switches_close_garage_door
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 37
        property_key: "002"
        value: KeyPressed3x
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 43
        property_key: "002"
        value: KeyPressed3x
  action:
    service: cover.close_cover
    entity_id: cover.garage_door_left

- alias: Garage switches up 1x - light on
  id: garage_switches_up_1x_light_on
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 37
        property_key: "002"
        value: KeyPressed
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 43
        property_key: "002"
        value: KeyPressed
  action:
    service: light.turn_on
    entity_id: light.garage

- alias: Garage switches down 1x - light off
  id: garage_switches_down_1x_light_off
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 37
        property_key: "002"
        value: KeyPressed
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 43
        property_key: "002"
        value: KeyPressed
  action:
    service: light.turn_on
    entity_id: light.garage