- alias: Garage outer config button x1 - toggle air hockey
  id: garage_outer_config_button_x1_toggle_air_hockey
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 37
      property_key: "003"
      value: KeyPressed
  action:
    service: switch.toggle
    entity_id: switch.air_hockey

- alias: Garage inner scene main button - toggle arcade
  id: garage_inner_scene_main_button_toggle_arcade
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 40
      label: "Scene 005"
      value: KeyPressed
  action:
    service: switch.toggle
    entity_id:
      - switch.arcade_cabinet_computer
      - switch.arcade_cabinet_monitor
      - switch.arcade_cabinet_audio
      - switch.arcade_cabinet_marquee_light