- alias: Laundry Room - Lights On
  id: laundry_room_light_on
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: sensor.laundryroom_aqara_fp1_presence_event
      to:
        - enter
        - left_enter
        - right_enter
        - approach
    - platform: state
      entity_id: 
        - binary_sensor.laundryroom_aqara_fp1_presence
        - binary_sensor.laundryroom_door
      to: "on"
  condition:
    condition: state
    entity_id: 
      - binary_sensor.someone_is_home
      - binary_sensor.laundryroom_door
    state: "on"
  action:
    service: light.turn_on
    entity_id: light.laundryroom

- alias: Laundry Room - Lights Off
  id: laundry_room_light_off
  trigger:
    - platform: state
      entity_id: sensor.laundryroom_aqara_fp1_presence_event
      to:
        - leave
        - left_leave
        - right_leave
        - away
    - platform: state
      entity_id: 
        - binary_sensor.laundryroom_aqara_fp1_presence
        - binary_sensor.laundryroom_door
      to: "off"
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
  condition:
    condition: state
    entity_id: binary_sensor.laundryroom_aqara_fp1_presence
    state: "off"
  action:
    service: light.turn_off
    entity_id: light.laundryroom
