- alias: Living Room - Turn on TV with WakeOnLan
  id: living_room_turn_on_tv_with_wakeonlan
  trigger:
    platform: webostv.turn_on
    entity_id: media_player.livingroom_tv
  action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: 78:5D:C8:12:91:49