- alias: Office - Play Spotify
  id: office_play_spotify
  trigger:
    platform: state
    entity_id:
      - switch.laptop
      - binary_sensor.laptop_in_use
      - group.office_occupancy
      - sensor.last_occupied_room
  condition:
    condition: and
    conditions:
      - "{{ is_state('switch.laptop', 'on') }}"
      - "{{ is_state('group.office_occupancy', 'on') }}"
      - "{{ not is_state('media_player.spotify_stukabombr1', 'playing') }}"
  action:
    - choose:
        - conditions: "{{ not is_state_attr('media_player.spotify_stukabombr1', 'source', '13204-MFUGATE') }}"
          sequence:
            - service: media_player.select_source
              entity_id: media_player.spotify_stukabombr1
              data:
                source: T480S-10-12813
            - delay: 2
    - service: media_player.media_play
      entity_id: media_player.spotify_stukabombr1

- alias: Office - Pause Spotify
  id: office_pause_spotify
  trigger:
    - platform: state
      entity_id:
        - media_player.gameroom_tv
        - media_player.livingroom_tv
      to: 'on'
    - platform: state
      entity_id:
        - switch.laptop
        - binary_sensor.laptop_in_use
        - group.office_occupancy
        - sensor.last_occupied_room
  condition: 
    condition: or
    conditions:
      - condition: and
        conditions:
          - "{{ is_state('switch.laptop', 'on') }}"
          - "{{ is_state('media_player.spotify_stukabombr1', 'playing') }}"
          - "{{ is_state('group.office_occupancy', 'off') }}"
          - "{{ is_state_attr('media_player.spotify_stukabombr1', 'source', '13204-MFUGATE') }}"
          - "{{ not is_state('sensor.last_occupied_room', 'office') }}"
      - "{{ trigger.entity_id.startswith('media_player') }}"
  action:
    service: media_player.media_pause
    entity_id: media_player.spotify_stukabombr1

- alias: Office - Lights On
  id: office_lights_on
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id:
        - sensor.office_aqara_fp1_presence_event
        - sensor.office_aqara_fp1_2_presence_event
      to:
        - enter
        - left_enter
        - right_enter
        - approach
    - platform: state
      entity_id:
        - binary_sensor.office_aqara_fp1_presence
        - binary_sensor.office_aqara_fp1_2_presence
      to: 'on'
  action:
    service: light.turn_on
    entity_id: light.office

- alias: Office - Lights Off
  id: office_lights_off
  mode: restart
  trigger:
    platform: state
    entity_id:
      - binary_sensor.office_aqara_fp1_presence
      - binary_sensor.office_aqara_fp1_2_presence
    to: 'off'
  condition:
    condition: state
    entity_id:
      - binary_sensor.office_aqara_fp1_presence
      - binary_sensor.office_aqara_fp1_2_presence
    state: 'off'
  action:
    service: light.turn_off
    target:
      entity_id: light.office
