- alias: 'Office lights on'
  id: office_lights_on
  trigger:
    platform: state
    entity_id: group.office_occupancy
    to: 'on'
  condition:
    - condition: state
      entity_id: person.mike
      state: home
  action:
    service: light.turn_on
    target:
      entity_id: light.office

- alias: 'Office lights off'
  id: office_lights_off
  trigger:
    - platform: state
      entity_id: group.office_occupancy
      to: 'off'
      for: 
        minutes: "{{ states('input_number.office_occupancy_timeout_minutes') | int }}"
        seconds: "{{ states('input_number.office_occupancy_timeout_seconds') | int }}"
    - platform: state
      entity_id: sensor.last_occupied_room
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: sensor.last_occupied_room
        state: office
  action:
    service: light.turn_off
    target:
      entity_id: light.office