- alias: Office - Lights On
  id: office_lights_on
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id:
        - sensor.office_aqara_fp1_presence_event
        - sensor.office_aqara_fp1_2_presence_event
      to:
        - enter
        - left_enter
        - right_enter
        - approach
    - platform: state
      entity_id:
        - binary_sensor.office_aqara_fp1_presence
        - binary_sensor.office_aqara_fp1_2_presence
      to: 'on'
  action:
    service: light.turn_on
    entity_id: light.office

- alias: Office - Lights Off
  id: office_lights_off
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.office_aqara_fp1_presence
        - binary_sensor.office_aqara_fp1_2_presence
      to: 'off'
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
  condition:
    condition: state
    entity_id:
      - binary_sensor.office_aqara_fp1_presence
      - binary_sensor.office_aqara_fp1_2_presence
    state: 'off'
  action:
    service: light.turn_off
    target:
      entity_id: light.office
