- alias: Porch - Light On at Sunset
  id: porch_light_on_at_sunset
  trigger:
    - platform: sun
      event: sunset
  action:
    service: light.turn_on
    entity_id: light.porch_light
- alias: Porch - Light Off at Sunrise
  id: porch_light_on_at_sunrise
  trigger:
    - platform: sun
      event: sunrise
  action:
    service: light.turn_off
    entity_id: light.porch_light