- alias: Porch - Light On at Sunset
  id: porch_light_on_at_sunset
  triggers:
    - trigger: sun
      event: sunset
  actions:
    - action: light.turn_on
      entity_id: light.porch_light
- alias: Porch - Light Off at Sunrise
  id: porch_light_on_at_sunrise
  triggers:
    - trigger: sun
      event: sunrise
  actions:
    - action: light.turn_off
      entity_id: light.porch_light