- alias: Upstairs Bathroom - Lights On
  id: upstairs_bathroom_lights_on
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: sensor.upstairsbathroom_aqara_fp1_presence_event
      to:
        - enter
        - left_enter
        - right_enter
        - approach
    - platform: state
      entity_id:
        - binary_sensor.upstairsbathroom_motion_1
        - binary_sensor.upstairsbathroom_aqara_fp1_presence
      to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.someone_is_home
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.upstairsbathroom
    data:
      brightness: "{{ states('sensor.upstairsbathroom_light_brightness')}}"
      transition: "{{ states('input_number.upstairsbathroom_light_transition')}}"

- alias: Upstairs Bathroom - Lights Off
  id: upstairs_bathroom_lights_off
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: sensor.upstairsbathroom_aqara_fp1_presence_event
      to:
        - leave
        - left_leave
        - right_leave
        - away
    - platform: state
      entity_id:
        - binary_sensor.upstairsbathroom_motion_1
        - binary_sensor.upstairsbathroom_aqara_fp1_presence
      to: 'off'
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
  condition:
    - condition: state
      entity_id: binary_sensor.upstairsbathroom_door
      state: 'on'
    - condition: state
      entity_id:
        - binary_sensor.upstairsbathroom_motion_1
        - binary_sensor.upstairsbathroom_aqara_fp1_presence
      state: 'off'
  action:
    service: light.turn_off
    entity_id: light.upstairsbathroom

- alias: Upstairs Bathroom - Vent Control
  id: upstairs_bathroom_vent_control
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: binary_sensor.upstairsbathroom_door
    - platform: event
      event_type: automation_reloaded
    - platform: homeassistant
      event: start
  condition:
    condition: not
    conditions:
      - condition: or
        conditions:
          - "{{ is_state('binary_sensor.upstairsbathroom_door', 'unavailable') }}"
  action:
    service: "switch.turn_{{ 'off' if is_state('binary_sensor.upstairsbathroom_door', 'on') else 'on' }}"
    entity_id: switch.upstairsbathroom_vent
