automation:

  - alias: Guest Room (Single) Tablet - Screen
    id: guest_room_single_tablet_screen
    trigger:
      - platform: state
        entity_id: binary_sensor.guest_room_single_presence_tablet_zone
        to: 'on'
      - platform: state
        entity_id: binary_sensor.guest_room_single_presence_tablet_zone
        to: 'off'
        for:
          seconds: "{{ states('input_number.guest_room_single_tablet_screen_timeout') | int(5) }}"
    action:
      service: switch.turn_{{ trigger.to_state.state }}
      entity_id: switch.guest_room_single_tablet_screen

  - alias: Guest Room (Single) Tablet - Keep Fully Kiosk in Foreground
    id: guest_room_single_tablet_keep_fully_foreground
    trigger:
      platform: state
      entity_id: sensor.guest_room_single_tablet_foreground_app
      not_to: de.ozerov.fully
    action:
      service: button.press
      entity_id: button.guest_room_single_tablet_bring_to_foreground

input_number:

  guest_room_single_tablet_screen_timeout:
    min: 0
    max: 600
    mode: box
    unit_of_measurement: s