automation:

  - alias: Guest Room (Single) - Close Back Shade When TV is On
    id: guest_room_single_close_shades_when_tv_is_on
    mode: queued
    triggers:
      - trigger: state
        entity_id: 
          - binary_sensor.guest_room_single_tv
          - switch.guest_room_single_ps4
        to: 'on'
    conditions:
      - condition: numeric_state
        entity_id: cover.guest_room_single_shade_back
        attribute: current_position
        above: 0
    actions:
      - action: cover.close_cover
        entity_id: cover.guest_room_single_shade_back

  - alias: Guest Room (Single) - Open Back Shade When TV is Off
    id: guest_room_single_open_side_shade_when_tv_is_off
    mode: queued
    triggers:
      - trigger: state
        entity_id: 
          - binary_sensor.guest_room_single_tv
          - switch.guest_room_single_ps4
        to: 'off'
    conditions:
      - condition: numeric_state
        entity_id: cover.guest_room_single_shade_back
        attribute: current_position
        below: 100
      - condition: state
        entity_id: sun.sun
        state: above_horizon
    actions:
      - action: cover.open_cover
        entity_id: cover.guest_room_single_shade_back