automation:

  - alias: Guest Room (Single) Tablet - Screen
    id: guest_room_single_tablet_screen
    mode: queued
    trigger:
      - id: 'on'
        platform: state
        entity_id: binary_sensor.guest_room_single_presence_tablet_zone
        to: 'on'
      - id: 'off'
        platform: state
        entity_id: binary_sensor.guest_room_single_presence_tablet_zone
        to: 'off'
        for:
          seconds: "{{ states('input_number.guest_room_single_tablet_screen_timeout') | int(30) }}"
      - id: 'off'
        platform: state
        entity_id: binary_sensor.guest_room_single_presence_bed_zone
        to: 'on'
        for:
          seconds: "{{ states('input_number.guest_room_single_tablet_screen_bed_timeout') | int(5) }}"
    action:
      - service: switch.turn_{{ trigger.id }}
        entity_id: switch.guest_room_single_tablet_screen

  - alias: Guest Room (Single) Tablet - Turn On Charging
    id: guest_room_single_tablet_turn_on_charging
    trigger:
      - platform: numeric_state
        entity_id: sensor.guest_room_single_tablet_battery
        below: input_number.guest_room_single_tablet_charging_threshold_low
    action:
      - service: switch.turn_on
        entity_id: switch.guest_room_single_tablet_charging_switch

  - alias: Guest Room (Single) Tablet - Turn Off Charging
    id: guest_room_single_tablet_turn_off_charging
    mode: queued
    trigger:
      - platform: numeric_state
        entity_id: sensor.guest_room_single_tablet_battery
        above: input_number.guest_room_single_tablet_charging_threshold_high
      - platform: homeassistant
        event: start
    condition:
      - condition: numeric_state
        entity_id: sensor.guest_room_single_tablet_battery
        above: input_number.guest_room_single_tablet_charging_threshold_high
    action:
      - service: switch.turn_off
        entity_id: switch.guest_room_single_tablet_charging_switch

  - alias: Guest Room (Single) Tablet - Turn Off Screen When Charging Status Changes
    id: guest_room_single_tablet_turn_off_screen_when_charging_status_changes
    mode: queued
    trigger:
      - platform: state
        entity_id: binary_sensor.guest_room_single_tablet_plugged_in
    condition:
      - condition: state
        entity_id: switch.guest_room_single_tablet_screen
        state: 'on'
      - condition: state
        entity_id: binary_sensor.guest_room_single_presence_tablet_zone
        state: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.guest_room_single_tablet_screen

input_number:

  guest_room_single_tablet_screen_timeout:
    min: 0
    max: 600
    mode: box
    unit_of_measurement: s

  guest_room_single_tablet_screen_bed_timeout:
    min: 0
    max: 600
    mode: box
    unit_of_measurement: s

  guest_room_single_tablet_charging_threshold_high:
    min: 0
    max: 100
    mode: box
    unit_of_measurement: "%"

  guest_room_single_tablet_charging_threshold_low:
    min: 0
    max: 100
    mode: box
    unit_of_measurement: "%"

  guest_room_single_tablet_screen_fix_wait_timeout:
    min: 0
    max: 100
    mode: box
    unit_of_measurement: m