- platform: universal
  name: livingroom_universal_media_player
  unique_id: livingroom_universal_media_player
  commands:
    turn_on:
      parallel:
        - service: media_player.turn_on
          target:
            entity_id: media_player.livingroom_receiver
        - service: automation.trigger
          target:
            entity_id: automation.living_room_turn_on_tv_with_wakeonlan
    turn_off:
      service: media_player.turn_off
      target:
        entity_id:
          - media_player.livingroom_tv
          - media_player.livingroom_receiver
  attributes:
    source_list: PS5,Hulu,Netflix