- platform: universal
  name: livingroom_media
  children:
    - media_player.livingroom_roku
    - media_player.playstation_4_office
    - media_player.livingroom_squeezelite
    - media_player.livingroom_receiver
    - media_player.livingroom_tv
  commands:
    turn_off:
      service: media_player.turn_off
      data:
        entity_id: 
          - media_player.livingroom_tv
          - media_player.livingroom_receiver
    turn_on:
      service: media_player.turn_on
      data:
        entity_id: 
          - media_player.livingroom_tv
          - media_player.livingroom_receiver
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: media_player.livingroom_receiver
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: media_player.livingroom_receiver
    volume_set:
      service: media_player.volume_set
      data:
        entity_id: media_player.livingroom_receiver
    volume_mute:
      service: media_player.volume_mute
      data:
        entity_id: media_player.livingroom_receiver
  attributes:
    state: media_player.livingroom_receiver
    volume_level: media_player.livingroom_receiver|volume_level
    is_volume_muted: media_player.livingroom_receiver|is_volume_muted