- platform: universal
  name: Living Room Media
  children:
    - media_player.living_room_roku
    - media_player.livingroom
    - media_player.living_room_receiver
  commands:
    turn_off:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.living_room_media
    turn_on:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.living_room_media
    select_source:
      service: input_select.select_option
      data_template:
        entity_id: input_select.living_room_source
        option: "{{ source }}"
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: media_player.living_room_receiver
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: media_player.living_room_receiver
    volume_set:
      service: media_player.volume_set
      data:
        entity_id: media_player.living_room_receiver
    volume_mute:
      service: media_player.volume_mute
      data:
        entity_id: media_player.living_room_receiver
  attributes:
    source: input_select.living_room_source
    source_list: input_select.living_room_source|options
    state: media_player.living_room_receiver
    volume_level: media_player.living_room_receiver|volume_level
    is_volume_muted: media_player.living_room_receiver|is_volume_muted