- platform: onkyo
  host: ${LIVINGROOM-RECEIVER-IP}
  name: livingroom_receiver
  receiver_max_volume: 78
- platform: onkyo
  host: ${GAMEROOM-RECEIVER-IP}
  name: gameroom_receiver
  receiver_max_volume: 100
- platform: aquostv
  host: ${LIVINGROOM-TV-IP}
  name: livingroom_tv
  power_on_enabled: true
- platform: aquostv
  host: ${BASEMENT-TV-IP}
  name: basement_tv
  power_on_enabled: true