- platform: onkyo
  host: !secret living_room_receiver_ip
  name: Living Room Receiver
- platform: onkyo
  host: !secret game_room_receiver_ip
  name: Game Room Receiver
- platform: aquostv
  host: !secret living_room_tv_ip
  name: Living Room TV
  power_on_enabled: true
- platform: aquostv
  host: !secret basement_tv_ip
  name: Basement TV
  power_on_enabled: true