- platform: onkyo
  host: ${LIVINGROOM_RECEIVER_IP}
  name: livingroom_receiver
  receiver_max_volume: 78
- platform: onkyo
  host: ${GAMEROOM_RECEIVER_IP}
  name: gameroom_receiver
  receiver_max_volume: 100
- platform: aquostv
  host: ${LIVINGROOM_TV_IP}
  name: livingroom_tv
  power_on_enabled: true
- platform: aquostv
  host: ${BASEMENT_TV_IP}
  name: basement_tv
  power_on_enabled: true
