automation:
  - alias: Voice - Adjust Speaker Volume
    id: voice_adjust_speaker_volume
    mode: parallel
    triggers:
      - trigger: conversation
        command:
          - "(turn|bump) the volume {direction}"
          - "(turn|bump) the volume {direction} by {volume_adjustment}"
          - "(turn|bump) {direction} the volume"
          - "(turn|bump) {direction} the volume by {volume_adjustment}"
          - "set the volume to {set_volume_to} [percent]"
    actions:
      - variables:
          input_number_entity: >
            {% set select = dict (
              office='input_number.office_music_adjust_volume_for_presence_level_on',
              bedroom='input_number.office_music_adjust_volume_for_presence_level_off'
            ) %}
            {{ select[trigger.device_id | area_id] | default('unknown') }}
          current_vol: "{{ states(input_number_entity) | int }}"
          direction: "{{ trigger.slots.direction.lower() if 'direction' in trigger.slots and trigger.slots.direction.lower() in ['up', 'down'] else 'unknown' }}"
          multiplier: "{{ 1 if direction == 'up' else -1 }}"
          volume_adjustment: "{{ trigger.slots.volume_adjustment | replace('%', '') | int if 'volume_adjustment' in trigger.slots else -1 }}"
          set_volume_to: "{{ trigger.slots.set_volume_to | replace('%', '') | int if 'set_volume_to' in trigger.slots else -1 }}"
          final_value: >
            {% if set_volume_to != -1 %}
              {{ set_volume_to }}
            {% elif volume_adjustment != -1 %}
              {{ current_vol + (multiplier * volume_adjustment)}}
            {% else %}
              -1
            {% endif %}
      - choose:
          - conditions: "{{ input_number_entity == 'unknown' }}"
            sequence:
              - set_conversation_response: Sorry, I can't control the volume in this room.
          - conditions: "{{ final_value == -1 }}"
            sequence:
              - set_conversation_response: Sorry, I wasn't able to parse that.
          - conditions: "{{ direction == 'unknown' and volume_adjustment != -1 }}"
            sequence:
              - set_conversation_response: >
                  It sounds like you're trying to adjust the volume up or down by {{ volume_adjustment }}
                  percent, but I couldn't parse the direction. Try saying 'Turn the volume up by 
                  {{ volume_adjustment }}%' or 'Turn the volume down by {{ volume_adjustment }}%'
        default:
          - action: input_number.set_value
            target:
              entity_id: "{{ input_number_entity }}"
            data:
              value: "{{ final_value }}"
          - set_conversation_response: "setting the volume to {{ final_value }} percent"