automation:
  - alias: Climate - Lower Temperature Before Bed
    id: climate_lower_temperature_before_bed
    triggers:
      - trigger: time
        at: input_datetime.climate_lower_temperature_before_bed
    conditions:
      - condition: state
        entity_id: person.mike
        state: home
      - condition: state
        entity_id: sensor.last_hvac_state
        state: cooling
      - condition: numeric_state
        entity_id: sensor.master_bedroom_sensor_air_temperature
        above: input_number.climate_lower_temperature_before_bed_bedroom_temperature_min
    actions:
      - action: climate.set_temperature
        entity_id: climate.thermostat
        data:
          target_temp_high: "{{ states('input_number.climate_temperature_before_bed') | int(72) }}"
          target_temp_low: "{{ state_attr('climate.thermostat', 'target_temp_low') | int(60) }}"

  - alias: Climate - Raise Temperature After Waking Up
    id: climate_raise_temperature_after_waking_up
    triggers:
      - trigger: state
        entity_id: input_boolean.master_bedroom_sleep_mode
        from: 'on'
        to: 'off'
    conditions:
      - condition: state
        entity_id: sensor.last_hvac_state
        state: cooling
    actions:
      - action: climate.set_temperature
        entity_id: climate.thermostat
        data:
          target_temp_high: "{{ states('input_number.climate_temperature_after_waking_up') | int(74) }}"
          target_temp_low: "{{ state_attr('climate.thermostat', 'target_temp_low') | int(60) }}"

  - alias: Climate - Alert If Heat Not Working
    id: wmLC0aDdMIw2NQy5P3hKoO0or01wlF
    mode: restart
    variables:
      current_temp: "{{ states('sensor.thermostat_air_temperature') | float }}"
      target_temp_low: "{{ state_attr('climate.thermostat', 'target_temp_low') | float }}"
      differential: "{{ states('input_number.climate_alert_heat_not_working_differential') | float }}"
    triggers:
      - trigger: state
        entity_id: 
          - sensor.thermostat_air_temperature
          - input_number.climate_alert_heat_not_working_differential
    conditions: >
      {{ is_state('sensor.last_hvac_state', 'heating') and
         target_temp_low - current_temp > differential }}
    actions:
      - action: notify.mobile_app_sm_g981u1
        data:
          message: "WARNING! The current thermostat temperature is more than {{ differential }}°F below the target temperature."
      
input_datetime:
  climate_lower_temperature_before_bed:
    has_date: false
    has_time: true

input_number:
  climate_alert_heat_not_working_differential:
    min: 0
    max: 10
    mode: box
    unit_of_measurement: °F
  climate_lower_temperature_before_bed_bedroom_temperature_min:
    min: 60
    max: 90
    mode: box
    unit_of_measurement: °F
  climate_temperature_before_bed:
    min: 60
    max: 90
    mode: box
    unit_of_measurement: °F
  climate_temperature_after_waking_up:
    min: 60
    max: 90
    mode: box
    unit_of_measurement: °F

sensor:
  - platform: history_stats
    name: hvac_cooling_time_daily
    unique_id: hvac_cooling_time_daily
    entity_id: sensor.hvac_action
    state: cooling
    type: time
    start: "{{ today_at() }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: hvac_cooling_sessions_daily
    unique_id: hvac_cooling_sessions_daily
    entity_id: sensor.hvac_action
    state: cooling
    type: count
    start: "{{ today_at() }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: hvac_heating_time_daily
    unique_id: hvac_heating_time_daily
    entity_id: sensor.hvac_action
    state: heating
    type: time
    start: "{{ today_at() }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: hvac_heating_sessions_daily
    unique_id: hvac_heating_sessions_daily
    entity_id: sensor.hvac_action
    state: heating
    type: count
    start: "{{ today_at() }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: hvac_cooling_time_weekly
    unique_id: hvac_cooling_time_weekly
    entity_id: sensor.hvac_action
    state: cooling
    type: time
    start: "{{ today_at() - timedelta(days=now().weekday()) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: hvac_cooling_sessions_weekly
    unique_id: hvac_cooling_sessions_weekly
    entity_id: sensor.hvac_action
    state: cooling
    type: count
    start: "{{ today_at() - timedelta(days=now().weekday()) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: hvac_heating_time_weekly
    unique_id: hvac_heating_time_weekly
    entity_id: sensor.hvac_action
    state: heating
    type: time
    start: "{{ today_at() - timedelta(days=now().weekday()) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: hvac_heating_sessions_weekly
    unique_id: hvac_heating_sessions_weekly
    entity_id: sensor.hvac_action
    state: heating
    type: count
    start: "{{ today_at() - timedelta(days=now().weekday()) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: hvac_cooling_time_monthly
    unique_id: hvac_cooling_time_monthly
    entity_id: sensor.hvac_action
    state: cooling
    type: time
    start: "{{ today_at().replace(day=1) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: hvac_cooling_sessions_monthly
    unique_id: hvac_cooling_sessions_monthly
    entity_id: sensor.hvac_action
    state: cooling
    type: count
    start: "{{ today_at().replace(day=1) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: hvac_heating_time_monthly
    unique_id: hvac_heating_time_monthly
    entity_id: sensor.hvac_action
    state: heating
    type: time
    start: "{{ today_at().replace(day=1) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: hvac_heating_sessions_monthly
    unique_id: hvac_heating_sessions_monthly
    entity_id: sensor.hvac_action
    state: heating
    type: count
    start: "{{ today_at().replace(day=1) }}"
    end: "{{ now() }}"

template:
  - trigger:
    - trigger: state
      entity_id: climate.thermostat
      attribute: hvac_action
      to:
        - heating
        - cooling
    sensor:
    - name: last_hvac_state
      state: "{{ trigger.to_state.attributes.hvac_action }}"

  - sensor:
    - name: hvac_action
      state: "{{ state_attr('climate.thermostat', 'hvac_action') }}"
