template:
  - select:
    - name: active_config_card_room
      unique_id: QSnUAhUvS3yGkFhu6IGByFufO0kInU
      state: "{{ states('input_text.active_config_card_rooms') }}"
      options: "{{ ['Bedroom', 'Hall of Holes', 'Living Room'] }}"
      select_option:
        - action: input_text.set_value
          target:
            entity_id: input_text.active_config_card_devices
          data:
            value: ''
        - action: input_text.set_value
          target:
            entity_id: input_text.active_config_card_rooms
          data:
            value: "{{ option }}"
    - name: active_config_card_devices
      unique_id: f8VKiFnkwkBku2UPioQ24o3nUw8jpV
      state: "{{ states('input_text.active_config_card_devices') }}"
      options: >
        {% if is_state('select.active_config_card_room', 'Living Room') %}
          {{ ['', 'Audio', 'Video', 'Fireplace', 'Lighting'] }}
        {% elif is_state('select.active_config_card_room', 'Hall of Holes') %}
          {{ ['', 'Garage Door'] }}
        {% else %}
          {{ ['Unknown Room'] }}
        {% endif %}
      select_option:
        - action: input_text.set_value
          target:
            entity_id: input_text.active_config_card_devices
          data:
            value: "{{ option }}"

input_text:
  active_config_card_rooms:
  active_config_card_devices: