automation:
  - alias: Spotify - Next Track if Stuck
    id: spotify_next_track_if_stuck
    max_exceeded: silent
    trigger:
      platform: state
      entity_id: media_player.spotify_stukabombr1
      attribute: media_position
    condition: >
      {{ state_attr('media_player.spotify_stukabombr1', 'media_duration') == state_attr('media_player.spotify_stukabombr1', 'media_position') 
         and is_state('media_player.spotify_stukabombr1', 'playing') }}"
    action:
      service: media_player.media_next_track
      entity_id: media_player.spotify_stukabombr1

input_text:
  garage_receiver_music_source:

input_number:
  spotify_source_change_delay:
    min: 0
    max: 15
    unit_of_measurement: s

input_select:
  spotify_playlists:
    options:
      - Liked Songs
      - Sarah

script:
  spotify_play_playlist:
    alias: Spotify - Play playlist
    description: Plays the selected spotify playlist
    mode: queued
    sequence:
      - variables:
          spotify_entity: media_player.spotify_stukabombr1
          playlist: "{{ states('input_select.spotify_playlists') }}"
          playlist_id: >
            {% if playlist == 'Liked Songs' %}
              7e2eaM4Ux8Fq7iWWaR5kHC
            {% elif playlist == 'Sarah' %}
              2teQZuFcZrPRCuKCrGLQTP
            {% endif %}
      - if: "{{ not is_state(spotify_entity, 'playing') or not is_state_attr(spotify_entity, 'media_playlist', playlist)}}"
        then:
          service: media_player.play_media
          entity_id: spotify_entity
          data:
            media_content_id: "spotify:playlist:{{ playlist_id }}"
            media_content_type: playlist

template:
  - sensor:
      # Since the name of the Squeezebox group can change in spotify, this sensor
      # is used to always return the current name of it (or unavailable if the source
      # is missing)
      - name: spotify_whole_house_source_name
        state: >
          {% set ns = namespace(found=False) %}
          {% for i in state_attr('media_player.spotify_stukabombr1', 'source_list') %}
            {% if '&' in i and ',' in i %}
              {{ i }}
              {% set ns.found = True %}
            {% endif %}
          {% endfor %}
          {% if not ns.found %}
            unavailable
          {% endif %}

      # A list of rooms that synced music is currently playing in
      - name: active_music_rooms
        state: use_the_attribute
        attributes:
          rooms: >
            {% set ns = namespace(rooms=[]) %}
            {% if is_state('media_player.livingroom_receiver', 'on') 
              and is_state_attr('media_player.livingroom_receiver', 'source', states('select.livingroom_receiver_music_source'))
              and is_state('media_player.livingroom_squeezebox', 'playing') %}
                {% set ns.rooms = ns.rooms + ['livingroom'] %}
            {% endif %}
            {% if is_state('media_player.garage_receiver', 'on') 
              and is_state_attr('media_player.garage_receiver', 'source', states('select.garage_receiver_music_source'))
              and is_state('media_player.garage_squeezebox', 'playing') %}
                {% set ns.rooms = ns.rooms + ['garage'] %}
            {% endif %}
            {{ ns.rooms }}

  - select:
      - name: garage_receiver_music_source
        unique_id: garage_receiver_music_source
        state: "{{ states('input_text.garage_receiver_music_source') }}"
        options: "{{ state_attr('media_player.garage_receiver', 'source_list') }}"
        select_option:
          service: input_text.set_value
          entity_id: input_text.garage_receiver_music_source
          data:
            value: "{{ option }}"