automation:
  - alias: Inovelli Switches - Set base color from HVAC status
    id: inovelli_switches_set_base_color_from_hvac_status
    triggers:
      - trigger: state
        entity_id: sensor.last_hvac_state
        to:
          - heating
          - cooling
    actions:
      - action: zwave_js.multicast_set_value
        target:
          entity_id: >-
            {% set entities = namespace(ids=[]) %}
            {% for state in states.light %}
              {% if is_device_attr(state.entity_id, 'model', 'LZW31-SN') %}
                {% set entities.ids = entities.ids + [state.entity_id] %}
              {% endif %}
            {% endfor %}
            {{ entities.ids }}
        data:
          command_class: "112"
          property: "13"
          value: "{{ is_state('sensor.last_hvac_state', 'heating') | iif('21', '170') }}"