automation:
  - alias: 'Christmas tree on at sunset'
    id: christmas_tree_on_at_sunset
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: -2.0
    action:
      service: switch.turn_on
      target:
        entity_id: switch.christmas_tree
        
sensor:
  - platform: rest
    name: tablet
    json_attributes:
      - batteryLevel
      - kioskMode
      - screenBrightness
      - motionDetectorState
      - maintenanceMode
      - appFreeMemory
      - appUsedMemory
      - totalFreeMemory
      - totalUsedMemory
      - hostname4
      - ip4
      - mac
      - locationLatitude
      - locationLongitude
      - locationAltitude
      - startUrl
      - currentPage
    resource: ${LIVINGROOM-TABLET-STATS-URL}
    value_template: "{{ value_json.isScreenOn if 'isScreenOn' in value_json else 'off' }}"

template:
  - sensor:
    - name: battery_livingroom_tablet
      state: "{{ state_attr('sensor.tablet', 'batteryLevel') }}"
  - binary_sensor:
    - name: livingroom_roku_media_active
      state: "{{ is_state('media_player.livingroom_tv', 'on') and is_state_attr('media_player.livingroom_tv', 'source', 'HDMI_IN_3') }}"
    - name: livingroom_roku_available
      state: "{{ not is_state('media_player.livingroom_tv', 'unavailable') and not is_state('media_player.livingroom_roku', 'unavailable') }}"