automation:
  - alias: Master Bedroom - Ceiling Light On
    description: Turn the ceiling light on when someone enters the bedroom.
    id: master_bedroom_ceiling_light_on
    max_exceeded: silent
    trigger:
      platform: state
      entity_id: group.presence_master_bedroom
      to: 'on'
    condition:
      - condition: state
        entity_id: group.presence_master_bedroom_bed
        state: 'off'
        for:
          minutes: "{{ states('input_number.masterbedroom_ceiling_light_bed_not_occupied_delay') | int(15) }}"
      - condition: state
        entity_id: binary_sensor.someone_is_home
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.master_bedroom_light_level_1
        below: input_number.masterbedroom_ceiling_light_on_threshold
      - condition: state
        entity_id: input_boolean.masterbedroom_sleep_mode
        state: 'off'
    action:
      service: light.turn_on
      entity_id: light.masterbedroom_ceiling_light_yellow

  - alias: Master Bedroom - Lights Off
    description: Turn all the bedroom lights off if the room is unoccupied.
    id: master_bedroom_lights_off
    max_exceeded: silent
    trigger:
      platform: state
      entity_id: group.presence_master_bedroom
      to: 'off'
      for:
        seconds: "{{ states('input_number.masterbedroom_lights_off_timeout') | int(60) }}"
    action:
      service: light.turn_off
      entity_id:
        - light.masterbedroom_ceiling_light_yellow
        - light.masterbedroom_ceiling_light_white
        - light.bedroom_lamps

  - alias: Master Bedroom - Ensure Nothing is On After Power Outage
    description: >
      Sometimes after a power outage, one of the overhead lights turns on. This automation checks that there is
      someone in the room if a light or fan turns on, and if not, turns them back off.
    id: master_bedroom_ensure_nothing_is_on_after_power_outage
    max_exceeded: silent
    trigger:
      platform: state
      entity_id:
        - light.masterbedroom_ceiling_light_yellow
        - light.masterbedroom_ceiling_light_white
        - light.bedroom_lamps
        - fan.masterbedroom_ceiling_fan
      to: 'on'
    condition:
      condition: state
      entity_id: group.presence_master_bedroom
      state: 'off'
    action:
      - service: light.turn_off
        entity_id:
          - light.masterbedroom_ceiling_light_yellow
          - light.masterbedroom_ceiling_light_white
          - light.bedroom_lamps
      - service: fan.turn_off
        entity_id: fan.masterbedroom_ceiling_fan

  - alias: Master Bedroom - Switch To Lamps For Sleep Mode
    description: When sleep mode activates and the ceiling light is on, turn the lamps on and turn the ceiling light off.
    id: master_bedroom_switch_to_lamps_for_sleep_mode
    max_exceeded: silent
    trigger:
      platform: state
      entity_id: input_boolean.masterbedroom_sleep_mode
      to: "on"
    condition:
      - condition: state
        entity_id:
          - light.masterbedroom_ceiling_light_yellow
          - light.masterbedroom_ceiling_light_white
        state: "on"
        match: any
      - condition: state
        entity_id: binary_sensor.someone_is_home
        state: 'on'
    action:
      - service: light.turn_on
        entity_id: light.bedroom_lamps
      - delay: 2
      - service: light.turn_off
        entity_id:
          - light.masterbedroom_ceiling_light_yellow
          - light.masterbedroom_ceiling_light_white
      - delay: "{{ states('input_number.masterbedroom_lamps_off_sleep_mode_delay') | int(20) }}"
      - service: light.turn_off
        entity_id: light.bedroom_lamps

  - alias: Master Bedroom - Turn On Fan For Sleep Mode
    description: Turns on the ceiling fan when sleep mode is activated.
    id: master_bedroom_turn_on_fan_for_sleep_mode
    max_exceeded: silent
    trigger:
      platform: state
      entity_id: input_boolean.masterbedroom_sleep_mode
      to: "on"
    condition:
      - condition: state
        entity_id: binary_sensor.someone_is_home
        state: 'on'
      - condition: state
        entity_id: input_boolean.masterbedroom_disable_fan_during_sleep_mode
        state: 'off'
    action:
      - service: fan.turn_on
        entity_id: fan.masterbedroom_ceiling_fan
        data:
          percentage: "{{ states('input_number.masterbedroom_fan_speed_for_sleep_mode') | int(100) }}"
      - service: fan.set_percentage
        entity_id: fan.masterbedroom_ceiling_fan
        data:
          percentage: "{{ states('input_number.masterbedroom_fan_speed_for_sleep_mode') | int(100) }}"

  - alias: Master Bedroom - Turn Off Fan For Sleep Mode
    description: Turns off the ceiling fan when sleep mode is deactivated.
    id: master_bedroom_turn_off_fan_for_sleep_mode
    max_exceeded: silent
    trigger:
      platform: state
      entity_id: input_boolean.masterbedroom_sleep_mode
      to: "off"
    action:
      service: fan.turn_off
      entity_id: fan.masterbedroom_ceiling_fan

  - alias: Master Bedroom - Turn On Sleep Mode
    description: Turns on sleep mode when the bed has been occupied for certain number of seconds.
    id: master_bedroom_turn_on_sleep_mode
    max_exceeded: silent
    trigger:
      platform: state
      entity_id: group.presence_master_bedroom_bed
      to: "on"
      for:
        seconds: "{{ states('input_number.masterbedroom_sleep_mode_on_delay') | int(10) }}"
    condition:
      condition: state
      entity_id: input_boolean.masterbedroom_disable_sleep_mode
      state: 'off'
    action:
      service: input_boolean.turn_on
      entity_id: input_boolean.masterbedroom_sleep_mode

  - alias: Master Bedroom - Turn Off Sleep Mode
    description: Turns off sleep mode when the bed has been unoccupied for certain number of seconds.
    id: master_bedroom_turn_off_sleep_mode
    max_exceeded: silent
    trigger:
      platform: state
      entity_id: group.presence_master_bedroom_bed
      to: "off"
      for:
        seconds: "{{ states('input_number.masterbedroom_sleep_mode_off_delay') | int(60) }}"
    action:
      service: input_boolean.turn_off
      entity_id: input_boolean.masterbedroom_sleep_mode

  - alias: Master Bedroom - Enable/Disable Fan During Sleep Mode
    description: If the fan is turned on or off manually during sleep mode, preserve that choice.
    id: master_bedroom_enable_masterbedroom_disable_fan_during_sleep_mode
    max_exceeded: silent
    trigger:
      platform: state
      entity_id: fan.masterbedroom_ceiling_fan
    condition:
      condition: state
      entity_id: input_boolean.masterbedroom_sleep_mode
      state: 'on'
    action:
      service: >
        {% if trigger.to_state.state == 'off' %}
          input_boolean.turn_on
        {% else %}
          input_boolean.turn_off
        {% endif %}
      entity_id: input_boolean.masterbedroom_disable_fan_during_sleep_mode
  
input_boolean:
  masterbedroom_disable_fan_during_sleep_mode:
  masterbedroom_disable_sleep_mode:
  masterbedroom_sleep_mode:

input_datetime:
  masterbedroom_sleep_mode_disable_time:
    has_date: false
    has_time: true
  masterbedroom_sleep_mode_enable_time:
    has_date: false
    has_time: true

input_number:

  # The speed (as a percentage) to set the fan to when sleep mode turns on
  masterbedroom_fan_speed_for_sleep_mode:
    min: 10
    max: 100
    step: 10
    mode: box
    unit_of_measurement: "%"

  # How long the lamps stay on after sleep mode turns on
  masterbedroom_lamps_off_sleep_mode_delay:
    min: 1
    max: 500
    mode: box
    unit_of_measurement: s
    
  # The amount of time the bedroom must be unoccupied before lights turn off
  masterbedroom_lights_off_timeout:
    min: 1
    max: 100
    mode: box
    unit_of_measurement: s
  
  # The amount of time the bed must be unoccupied before the ceiling light can be turned on
  masterbedroom_ceiling_light_bed_not_occupied_delay:
    min: 1
    max: 50
    mode: box
    unit_of_measurement: m

  # The light level in the room must be under this threshold for lights to turn on
  masterbedroom_ceiling_light_on_threshold:
    min: 0
    max: 500
    mode: box
    unit_of_measurement: lx

  # The amount of time the bed must be unoccupied for sleep mode to turn off
  masterbedroom_sleep_mode_off_delay:
    min: 1
    max: 500
    mode: box
    unit_of_measurement: s

  # The amount of time the bed must be occupied for sleep mode to turn on
  masterbedroom_sleep_mode_on_delay:
    min: 1
    max: 500
    mode: box
    unit_of_measurement: s
  
light:
  - platform: group
    name: Bedroom Lamps
    entities:
      - light.masterbedroom_left_lamp
      - light.masterbedroom_right_lamp