automation:
  - alias: Security Alert
    id: security_alert
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.back_door
          - binary_sensor.front_door
          - binary_sensor.garage_door_left
          - binary_sensor.garage_inner_door_left
        to: "on"
    conditions:
      - condition: state
        entity_id: person.mike
        state: not_home
    actions:
      - action: notify.mobile_app_sm_g981u1
        data:
          message: Security alert! {{trigger.entity_id}} {{states.sensor.date.state}} {{states.sensor.time.state}}