automation:
  - alias: Security Alert
    id: security_alert
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.back_sliding_door
          - binary_sensor.front_door
          - binary_sensor.garage_door_left
          - binary_sensor.garage_inner_door_left
        to: "on"
    conditions:
      - condition: state
        entity_id: person.mike
        state: not_home
    actions:
      - action: notify.mobile_app_sm_g981u1
        data:
          message: Security alert! {{trigger.entity_id}} {{states.sensor.date.state}} {{states.sensor.time.state}}

  - alias: Security - Object detected in driveway
    id: security_object_detected_in_driveway
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.driveway_car_occupancy
          - binary_sensor.driveway_person_occupancy
        to: "on"
    actions:
      - action: notify.mobile_app_sm_g981u1
        data:
          message: >-
            {{ trigger.entity_id.split('_')[2].capitalize() }} detected in driveway
          data:
            image: >-
              /api/camera_proxy/camera.driveway