binary_sensor:
  - platform: rest
    name: latest_certbot_image_available_on_docker_hub
    resource_template: https://hub.docker.com/v2/repositories/certbot/certbot/tags/{{ states('sensor.certbot_latest_version') }}
    value_template: "{% if value_json.tag_status == 'active' %} on {% else %} off {% endif %}"
  - platform: rest
    name: latest_zwavejs2mqtt_image_available_on_docker_hub
    resource_template: https://hub.docker.com/v2/repositories/zwavejs/zwavejs2mqtt/tags/{{ states('sensor.zwavejs2mqtt_latest_version') }}
    value_template: "{% if value_json.tag_status == 'active' %} on {% else %} off {% endif %}"

group:
  update_available:
    icon: mdi:update
    entities:
      - binary_sensor.updater
      - binary_sensor.certbot_updater
      - binary_sensor.zwavejs2mqtt_updater

template:
  - sensor:
      - name: certbot_latest_version
        state: "{{ state_attr('sensor.certbot_certbot_latest_release', 'tag') }}"
      - name: zwavejs2mqtt_latest_version
        state: "{{ state_attr('sensor.zwave_js_zwavejs2mqtt_latest_release', 'tag')[1:] }}"
  - binary_sensor:
      - name: certbot_updater
        state: "{{ states('sensor.certbot_latest_version') != state_attr('sensor.docker_certbot', 'image').split(':')[1] and is_state('binary_sensor.latest_certbot_image_available_on_docker_hub', 'on') }}"
        attributes:
          newest_version: "{{ states('sensor.certbot_latest_version') }}"
      - name: zwavejs2mqtt_updater
        state: "{{ states('sensor.zwavejs2mqtt_latest_version') != state_attr('sensor.office_raspi4_zwavejs', 'image').split(':')[1] and is_state('binary_sensor.latest_zwavejs2mqtt_image_available_on_docker_hub', 'on') }}"
        attributes:
          newest_version: "{{ states('sensor.zwavejs2mqtt_latest_version') }}"
