binary_sensor:
  - platform: rest
    name: latest_zwavejs2mqtt_image_available_on_docker_hub
    resource_template: https://hub.docker.com/v2/repositories/zwavejs/zwavejs2mqtt/tags/{{ states('sensor.zwavejs2mqtt_latest_version') }}
    value_template: "{% if value_json.tag_status == 'active' %} on {% else %} off {% endif %}"

group:
  update_available:
    icon: mdi:update
    entities:
      - binary_sensor.updater
      - binary_sensor.unifi_update_available
      - binary_sensor.zwavejs2mqtt_update_available

sensor:
  - platform: github
    access_token: ${GITHUB_PASSWORD}
    repositories:
      - path: zwave-js/zwavejs2mqtt

template:
  - sensor:
      - name: zwavejs2mqtt_latest_version
        state: "{{ state_attr('sensor.zwavejs2mqtt', 'latest_release_tag')[1:] }}"
  - binary_sensor:
      - name: zwavejs2mqtt_update_available
        state: "{{ states('sensor.zwavejs2mqtt_latest_version') != state_attr('sensor.office_raspi4_zwavejs', 'image').split(':')[1] and is_state('binary_sensor.latest_zwavejs2mqtt_image_available_on_docker_hub', 'on') }}"
