group:
  upstairsbathroom:
    entities:
      - light.upstairsbathroom
      - switch.upstairsbathroom_vent
  upstairsbathroom_occupancy:
    name: Upstairs Bathroom
    icon: hass:walk
    entities:
      - binary_sensor.upstairsbathroom_motion_1
      - binary_sensor.upstairsbathroom_motion_2
      - binary_sensor.upstairsbathroom_motion_3

automation:
  - alias: Upstairs bathroom lights on
    id: upstairs_bathroom_lights_on
    trigger:
      platform: state
      entity_id: group.upstairsbathroom_occupancy
      to: "on"
    condition:
      - condition: state
        entity_id: light.upstairsbathroom
        state: "off"
      - condition: state
        entity_id: person.mike
        state: home
    action:
      service: light.turn_on
      entity_id: light.upstairsbathroom
      data:
        brightness: >-
          {% if is_state('input_boolean.sleep_mode', 'on') %}
            {{ states('input_number.upstairsbathroom_light_sleeping_brightness') | int(0) }}
          {% elif is_state('sun.sun', 'above_horizon') %}
            {{ states('input_number.upstairsbathroom_light_day_brightness') | int(0) }}
          {% else %}
            {{ states('input_number.upstairsbathroom_light_night_brightness') | int(0) }}
          {% endif %}
        transition: "{{ states('input_number.upstairsbathroom_light_transition')}}"

  - alias: Upstairs bathroom lights off
    id: upstairs_bathroom_lights_off
    trigger:
      - platform: state
        entity_id: group.upstairsbathroom_occupancy
        to: "off"
        for:
          seconds: "{{ states('input_number.upstairsbathroom_occupancy_timeout_seconds') | int(0) }}"
      - platform: state
        entity_id: group.upstairsbathroom_occupancy
        to: "off"
        for:
          minutes: "{{ states('input_number.upstairsbathroom_door_closed_occupancy_timeout_minutes') | int(0) }}"
      - platform: state
        entity_id: binary_sensor.upstairsbathroom_door
        to: "on"
      - platform: state
        entity_id: sensor.last_occupied_room
    condition:
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.upstairsbathroom_door
                state: "on"
              - condition: template
                value_template: >-
                  {% set timeout = states('input_number.upstairsbathroom_occupancy_timeout_seconds') | int(0) %}
                  {{ (now() - states.group.upstairsbathroom_occupancy.last_updated).total_seconds() >= timeout }}
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.upstairsbathroom_door
                state: "off"
              - condition: template
                value_template: >-
                  {% set timeout = (states('input_number.upstairsbathroom_door_closed_occupancy_timeout_minutes') | int(0)) * 60 %}
                  {{ (now() - states.group.upstairsbathroom_occupancy.last_updated).total_seconds() >= timeout }}
      - condition: state
        entity_id: group.upstairsbathroom_occupancy
        state: "off"
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.last_occupied_room
            state: upstairsbathroom
    action:
      service: light.turn_off
      entity_id: light.upstairsbathroom

  - alias: Upstairs bathroom vent control
    id: upstairs_bathroom_vent_control
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.upstairsbathroom_door
          - sensor.upstairsbathroom_humidity
          - input_number.upstairsbathroom_vent_humidity_threshold
    action:
      service: >-
        {% if is_state('binary_sensor.upstairsbathroom_door', 'on') and (states('sensor.upstairsbathroom_humidity') | int(0)) < (states('input_number.upstairsbathroom_vent_humidity_threshold') | int(0)) %}
          switch.turn_off
        {% else %}
          switch.turn_on
        {% endif %}
      entity_id: switch.upstairsbathroom_vent

input_number:
  upstairsbathroom_vent_humidity_threshold:
    name: Humidity Threshold
    icon: mdi:water-percent
    min: 50
    max: 100
    mode: box
  upstairsbathroom_occupancy_timeout_seconds:
    name: Occupancy Timeout
    icon: mdi:clock-outline
    min: 0
    max: 360
    mode: box
  upstairsbathroom_door_closed_occupancy_timeout_minutes:
    name: Occupancy Timeout (Door Closed)
    icon: mdi:clock-outline
    min: 1
    max: 60
    mode: box
  upstairsbathroom_light_sleeping_brightness:
    name: Sleeping Brightness
    icon: mdi:sleep
    min: 1
    max: 255
    mode: box
  upstairsbathroom_light_day_brightness:
    name: Daytime Brightness
    icon: mdi:brightness-5
    min: 1
    max: 255
    mode: box
  upstairsbathroom_light_night_brightness:
    name: Nighttime Brightness
    icon: mdi:brightness-4
    min: 1
    max: 255
    mode: box
  upstairsbathroom_light_transition:
    name: Transition
    icon: mdi:arrow-right
    min: 1
    max: 10
    mode: box
