automation:

  - alias: Vacuum - Basement (Remus)
    id: vacuum_basement
    trigger:
      platform: time
      at: input_datetime.vacuum_basement_time
    action:
      - wait_template: >
          {{ is_state('binary_sensor.entire_laundry_room_zone', 'off') and
             is_state('binary_sensor.presence_workout_room_zone_1', 'off') }}
        timeout: '01:00:00'
        continue_on_timeout: false
      - service: vacuum.start
        entity_id: vacuum.remus

  - alias: Vacuum - Garage (Chester)
    id: vacuum_garage
    trigger:
      platform: time
      at: input_datetime.vacuum_garage_time
    action:
      - wait_template: "{{ is_state('binary_sensor.presence_garage_zone_1', 'off') }}"
        timeout: '01:00:00'
        continue_on_timeout: false
      - service: vacuum.start
        entity_id: vacuum.chester

  - alias: Vacuum - First Floor Unoccupied (Romulus)
    id: vacuum_first_floor_unoccupied
    trigger:
      platform: time
      at: input_datetime.vacuum_first_floor_unoccupied_time
    condition:
      condition: state
      entity_id: input_boolean.sarah_remote_week_with_kids
      state: 'on'
    action:
      - wait_template: >
          {{ is_state('binary_sensor.living_room_presence', 'off') and
             is_state('binary_sensor.kitchen_back_presence_sensor_all_zones', 'off') and
             is_state('binary_sensor.kitchen_zone_1', 'off') }}
        timeout: '01:00:00'
        continue_on_timeout: false
      - service: vacuum.start
        entity_id: vacuum.romulus

  - alias: Vacuum - Second Floor Unoccupied (Ricky)
    id: vacuum_second_floor_unoccupied
    trigger:
      platform: time
      at: input_datetime.vacuum_second_floor_unoccupied_time
    condition:
      condition: state
      entity_id: input_boolean.sarah_remote_week_with_kids
      state: 'on'
    action:
      - wait_template: >
          {{ is_state('binary_sensor.office_zone_1', 'off') and
             is_state('group.masterbedroom_occupied', 'off') }}
        timeout: '01:00:00'
        continue_on_timeout: false
      - service: vacuum.start
        entity_id: vacuum.ricky

input_datetime:
  vacuum_basement_time:
    has_date: false
    has_time: true
  vacuum_garage_time:
    has_date: false
    has_time: true
  vacuum_first_floor_unoccupied_time:
    has_date: false
    has_time: true
  vacuum_second_floor_unoccupied_time:
    has_date: false
    has_time: true