automation:

  - alias: Vacuum - Basement (Remus)
    id: vacuum_basement
    trigger:
      platform: time
      at: input_datetime.vacuum_basement_time
    action:
      - wait_template: "{{ is_state('group.presence_basement', 'off') }}"
        timeout: '01:00:00'
        continue_on_timeout: false
      - service: vacuum.start
        entity_id: vacuum.remus

  - alias: Vacuum - Garage (Chester)
    id: vacuum_garage
    trigger:
      platform: time
      at: input_datetime.vacuum_garage_time
    action:
      - wait_template: "{{ is_state('binary_sensor.garage_presence_all_zones', 'off') }}"
        timeout: '01:00:00'
        continue_on_timeout: false
      - service: vacuum.start
        entity_id: vacuum.chester

  - alias: Vacuum - First Floor Unoccupied (Romulus)
    id: vacuum_first_floor_unoccupied
    trigger:
      platform: time
      at: input_datetime.vacuum_first_floor_unoccupied_time
    condition:
      - condition: state
        entity_id: input_boolean.sarah_remote_week_with_kids
        state: 'on'
      - condition: state
        entity_id: person.mike
        state: not_home
    action:
      - wait_template: "{{ is_state('group.presence_first_floor', 'off') }}"
        timeout: '01:00:00'
        continue_on_timeout: false
      - service: vacuum.start
        entity_id: vacuum.romulus

template:
  - trigger:
      - platform: state
        entity_id: vacuum.ricky
        to: cleaning
    sensor:
      - name: ricky_last_cleaned
        device_class: timestamp
        state: "{{ now() }}"
  - trigger:
      - platform: state
        entity_id: vacuum.romulus
        to: cleaning
    sensor:
      - name: romulus_last_cleaned
        device_class: timestamp
        state: "{{ now() }}"


input_datetime:
  vacuum_basement_time:
    has_date: false
    has_time: true
  vacuum_garage_time:
    has_date: false
    has_time: true
  vacuum_first_floor_unoccupied_time:
    has_date: false
    has_time: true
  vacuum_second_floor_unoccupied_time:
    has_date: false
    has_time: true
  vacuum_second_floor_occupied_time:
    has_date: false
    has_time: true