automation:

  - alias: Workout Room - Lights On
    description: Turn the workout room lights on when the room is occupied.
    id: workout_room_lights_on
    max_exceeded: silent
    mode: queued
    trigger:
      platform: state
      entity_id: 
        - binary_sensor.presence_workout_room_zone_1
        - binary_sensor.workout_room_entrance_zone
      to: 'on'
    action:
      service: light.turn_on
      entity_id: light.workout_room_lights

  - alias: Workout Room - Lights Off
    description: Turn the workout room lights off when the room is unoccupied.
    id: workout_room_lights_off
    max_exceeded: silent
    mode: queued
    trigger:
      platform: state
      entity_id: 
        - binary_sensor.presence_workout_room_zone_1
        - binary_sensor.entire_laundry_room_zone
      to: 'off'
      for:
        seconds: "{{ states('input_number.workoutroom_lights_off_timeout') | int }}"
    condition:
      condition: state
      entity_id: 
        - binary_sensor.presence_workout_room_zone_1
        - binary_sensor.entire_laundry_room_zone
      state: 'off'
    action:
      service: light.turn_off
      entity_id: light.workout_room_lights

input_number:

  # The amount of time the bedroom must be unoccupied before lights turn off
  workoutroom_lights_off_timeout:
    min: 0
    max: 600
    mode: box
    unit_of_measurement: s