# Automatically create a pull request for branches other than main
# The PR should automatically merge once it passes all status checks

name: 'Create Pull Request'
on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  create-pull-request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/get-keyvault-secrets@v1
        with: 
          keyvault: overlord-vault
          secrets: GITHUB
        id: az
      - uses: actions/checkout@v2
      - id: create-pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ steps.az.outputs.GITHUB }}
          pull-request-number: ${{ steps.create-pull-request.outputs.pr_number }}
          merge-method: merge
