# Automatically create a pull request for branches other than main
# The PR should automatically merge once it passes all status checks

name: 'Create Pull Request'
on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  create-pull-request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
