name: Run Playbook
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  run-playbook:
    name: Run Playbook
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/get-keyvault-secrets@v1
        with: 
          keyvault: overlord-vault
          secrets: >
            OVERLORD-URL,
            RUN-ANSIBLE-PLAYBOOK-TOKEN
        id: az
      - run: "curl ${{ steps.az.outputs.OVERLORD-URL }}/jenkins-webhook-truenas?token=${{ steps.az.outputs.RUN-ANSIBLE-PLAYBOOK-TOKEN }} -X POST -d '{}'"