name: YAML Lint
on: [push]
jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |
            rules:
              document-start: disable
              line-length:
                max: 150
